// End-to-end walk through every screen against e2e/mock-supabase.mjs.
//   1. node e2e/mock-supabase.mjs &
//   2. NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321 NEXT_PUBLIC_SUPABASE_ANON_KEY=anon-mock NEXT_PUBLIC_SITE_URL=http://localhost:3000 npx next build
//   3. ANTHROPIC_API_KEY=mock ANTHROPIC_BASE_URL=http://localhost:54321/anthropic npx next start -p 3000 &
//   4. node e2e/run.mjs [screenshot-dir]
import { createRequire } from 'node:module';
import zlib from 'node:zlib';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright'); // dev-only; resolved from NODE_PATH or a local install

const BASE = process.env.E2E_BASE || 'http://localhost:3000';
const SHOTS = process.argv[2] || null;
if (SHOTS) fs.mkdirSync(SHOTS, { recursive: true });

function png(w = 64, h = 64) {
  const crcT = Array.from({ length: 256 }, (_, n) => { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; return c >>> 0; });
  const crc = (b) => { let c = 0xffffffff; for (const x of b) c = crcT[(c ^ x) & 255] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; };
  const chunk = (t, d) => { const l = Buffer.alloc(4); l.writeUInt32BE(d.length); const td = Buffer.concat([Buffer.from(t), d]); const c = Buffer.alloc(4); c.writeUInt32BE(crc(td)); return Buffer.concat([l, td, c]); };
  const ihdr = Buffer.alloc(13); ihdr.writeUInt32BE(w, 0); ihdr.writeUInt32BE(h, 4); ihdr[8] = 8; ihdr[9] = 2;
  const raw = Buffer.alloc((w * 3 + 1) * h); for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) { const o = y * (w * 3 + 1) + 1 + x * 3; raw[o] = 230; raw[o + 1] = 160 + (x % 40); raw[o + 2] = 80; }
  return Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk('IHDR', ihdr), chunk('IDAT', zlib.deflateSync(raw)), chunk('IEND', Buffer.alloc(0))]);
}
const photo = { name: 'plate.png', mimeType: 'image/png', buffer: png() };

const results = [];
const check = (name, ok, detail = '') => { results.push([ok ? 'PASS' : 'FAIL', name, detail]); console.log(ok ? 'PASS' : 'FAIL', name, detail); };
const problems = [];

const browser = await chromium.launch({ args: ['--use-gl=swiftshader', '--enable-webgl', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, timezoneId: 'America/New_York' });
const page = await ctx.newPage();
page.setDefaultTimeout(12000);
page.on('console', (m) => { if (m.type() === 'error' && !/Failed to load resource/.test(m.text())) problems.push(`console: ${m.text()}`); });
page.on('pageerror', (e) => problems.push(`pageerror: ${e.message}`));
page.on('response', (r) => { if (r.status() >= 400 && !/api\/barcode/.test(r.url())) problems.push(`HTTP ${r.status()} ${r.request().method()} ${r.url()}`); });
const shot = async (n) => { if (SHOTS) await page.screenshot({ path: path.join(SHOTS, `${n}.png`), fullPage: true }); };
const step = async (name, fn) => { try { await fn(); } catch (e) { check(name, false, e.message.split('\n')[0]); await shot(`fail-${name.replace(/\W+/g, '-')}`); } };
const nav = (n) => page.getByRole('navigation').getByRole('link', { name: n, exact: true }).click();
const closePopups = async () => { await page.locator('.popup-scrim').first().waitFor({ timeout: 3000 }).catch(() => {}); for (let i = 0; i < 4; i++) { const x = page.locator('.popup-scrim [aria-label=Close]').first(); const leave = page.locator('.popup-scrim').getByRole('button', { name: 'Leave' }).first(); if (await x.count()) await x.click(); else if (await leave.count()) await leave.click(); else break; await page.waitForTimeout(400); } };

await step('signed-out redirect', async () => { await page.goto(`${BASE}/home`); check('signed-out /home redirects to /login', page.url().includes('/login')); });
await step('log in', async () => {
  check('no account: no email, no password, no Google', (await page.locator('input[type=password], input[type=email], #email, #password').count()) === 0 && (await page.getByText(/Google/).count()) === 0 && (await page.getByRole('button', { name: 'Start playing' }).count()) === 1);
  check('a plain-words disclaimer says what is recorded', /records what you do in the app/.test(await page.locator('.disclaimer').innerText()));
  check('Start stays off until you Accept or Decline', await page.getByRole('button', { name: 'Start playing' }).isDisabled());
  await page.getByRole('radio', { name: 'Decline' }).click();
  check('Decline says you can still play, nothing recorded', /still play everything, and nothing you do is recorded/.test(await page.locator('.disclaimer').innerText()));
  await page.getByRole('radio', { name: 'Accept' }).click();
  await shot('00-login');
  await page.getByRole('button', { name: 'Start playing' }).click(); await page.waitForURL('**/cook', { timeout: 15000 });
  check('Start playing makes a phone-only game and lands on Cook', (await (await fetch('http://localhost:54321/__e2e/anon-signups')).json()).n === 1);
  check('no second cookie popup: the Accept from the start screen was saved to the game', (await page.locator('.cc-scrim').count()) === 0);
  // No tour: you land straight in the app; Chef explains each thing the first time you tap it.
  check('no walkthrough: nothing covers the app on first open', (await page.locator('.coach, .tour-scrim').count()) === 0);
  await page.locator('.tip-card').waitFor({ timeout: 6000 });
  check('Chef says hello once, in one line, with no step numbers', /Welcome to the kitchen/.test(await page.locator('.tip-card').innerText()) && !/\b\d+ of \d+\b/.test(await page.locator('.tip-card').innerText()));
  await page.locator('.hud-hello.on').waitFor({ timeout: 6000 }).catch(() => {});
  check('the greeting shows in the top bar', /Welcome to Whisk/.test(await page.locator('.hud-hello').innerText()));
  await shot('00b-welcome-tip');
  await page.locator('.nav a[href="/pantry"]').click(); await page.waitForURL('**/pantry');
  await page.locator('.tip-card', { hasText: 'Pantry' }).waitFor({ timeout: 4000 });
  check('tapping a new tab still opens it, and Chef explains it', page.url().includes('/pantry') && /real kitchen/.test(await page.locator('.tip-card').innerText()));
  const tipBox = await page.locator('.tip-card').boundingBox(); const add = await page.locator('[data-tour="add"]').boundingBox();
  check('the tip sits at the top, clear of the buttons', tipBox.y < 200 && tipBox.y + tipBox.height < add.y);
  await page.locator('#p-name').click();
  await page.locator('.tip-card').waitFor({ state: 'detached', timeout: 3000 });
  check('tapping anything else puts the tip away', true);
  await page.locator('.nav a[href="/cook"]').click(); await page.waitForURL('**/cook'); await page.locator('.tip-card', { hasText: 'Cook' }).waitFor({ timeout: 4000 }); await page.locator('.tip-ok').click();
  await page.locator('.nav a[href="/pantry"]').click(); await page.waitForURL('**/pantry'); await page.waitForTimeout(700);
  check('each tip shows only once', (await page.locator('.tip-card').count()) === 0);
  await page.fill('#p-name', 'Bananas'); await page.locator('[data-tour="add"]').click();
  await page.locator('.tip-card', { hasText: 'Add to pantry' }).waitFor({ timeout: 4000 });
  check('first Add explains XP; the item is still added', await page.locator('main').getByText('Bananas', { exact: true }).first().waitFor({ timeout: 6000 }).then(() => true, () => false));
  // name + the first shirt (no tour now: from the Me page)
  await page.locator('.nav a[href="/me"]').click(); await page.waitForURL('**/me');
  await page.locator('.namebtn').click(); await page.locator('#nm').fill('Jai'); await page.locator('#nm').press('Enter');
  await page.waitForFunction(() => document.querySelector('.namebtn h1')?.textContent === 'Jai', null, { timeout: 6000 });
  check('name set from the Me page', true);
  const coins0 = Number((await page.locator('header .pill').nth(1).innerText()).replace(/\D/g, ''));
  await page.locator('.closet-grid .tile.locked').filter({ hasText: 'Lifeguard Shirt' }).click();
  await page.locator('[data-tour="buy"]').click();
  await page.waitForFunction((c0) => Number((document.querySelectorAll('header .pill')[1]?.textContent || '').replace(/\D/g, '')) !== c0, coins0, { timeout: 6000 }).catch(() => {});
  const coins1 = Number((await page.locator('header .pill').nth(1).innerText()).replace(/\D/g, ''));
  check('a 1,500 shirt (Lifeguard) can be bought with the starting coins', coins0 - coins1 === 1500, `${coins0} → ${coins1}`);
  await page.locator('.tip-ok').click().catch(() => {});
  // the cook: arms down, a Dance button that starts and stops
  check('Dance button on the cook', (await page.getByRole('button', { name: 'Dance' }).count()) === 1);
  await page.getByRole('button', { name: 'Dance' }).click();
  check('Dance turns into Stop while dancing', (await page.getByRole('button', { name: 'Stop' }).getAttribute('aria-pressed')) === 'true');
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }); document.dispatchEvent(new Event('visibilitychange')); });
  await page.getByRole('button', { name: 'Dance' }).waitFor({ timeout: 3000 });
  check('the dance stops when the screen goes off / app is in the background', true);
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => false }); document.dispatchEvent(new Event('visibilitychange')); });
  await shot('00c-me-dance');
  await nav('Home');
});
await step('home', async () => {
  await page.getByRole('heading', { name: 'Almost ready' }).waitFor();
  check('home shows Almost ready', true);
  check('home has no challenges or Fridge Raid', (await page.getByText('This week’s challenges').count()) === 0 && (await page.getByText('Fridge Raid').count()) === 0);
  await page.getByText('Ground beef is frozen').waitFor();
  check('home reminds you to defrost frozen ground beef', true);
  await page.locator('.src a').first().waitFor();
  check('almost-ready recipes link to their source site', /^https:\/\//.test(await page.locator('.src a').first().getAttribute('href')));
  check('home: just a "Full recipe" link (no "From"), no recipe count, no "items away" on the cards', (await page.locator('.src', { hasText: /^From/ }).count()) === 0 && (await page.locator('.src a', { hasText: 'Full recipe' }).count()) > 0 && !/\d+ recipes?$/.test(await page.locator('.page-title').first().innerText()) && (await page.locator('main .card .eyebrow', { hasText: /away/ }).count()) === 0);
  for (let i = 0; i < 8 && (await page.locator('.away-h').count()) < 2; i++) { const more = page.getByRole('button', { name: 'Show more' }); if (!(await more.count())) break; await more.click(); await page.waitForTimeout(150); }
  check('almost ready is grouped by items missing, closest first, no limit', (await page.locator('.away-h').count()) >= 2 && /1 item away/i.test(await page.locator('.away-h').first().innerText()) && /2 items away/i.test(await page.locator('.away-h').nth(1).innerText()));
  await page.evaluate(() => window.scrollTo(0, 0));
  check('pantry hint is the short version', (await page.getByText('Whisk reads').count()) === 0);
  // open one: tap a single missing ingredient under "What you have" to put it in the pantry
  const card0 = page.locator('main .card', { has: page.getByRole('button', { name: 'Open recipe' }) }).first();
  const cuisine0 = (await card0.locator('.eyebrow').innerText()).trim();
  await card0.getByRole('button', { name: 'Open recipe' }).click();
  const sheet = page.locator('[role=dialog].sheet');
  const miss = sheet.locator('button.add-ing').first(); const missName = (await miss.innerText()).replace(/^\+\s*/, '').trim();
  await miss.click();
  await sheet.locator('.chip.have', { hasText: missName }).waitFor({ timeout: 6000 });
  check('tap one missing ingredient: it turns ✓ and goes in the pantry', (await page.locator('.toast').innerText()).includes('is in your pantry'), missName);
  check('the recipe gets a soft cultural backdrop for its cuisine', (await sheet.getAttribute('class')).includes('cx') && !!(await sheet.getAttribute('data-motif')) && (await sheet.getAttribute('data-motif')) !== 'dots', `${cuisine0} → ${await sheet.getAttribute('data-motif')}`);
  await shot('01b-recipe-culture');
  await sheet.getByRole('button', { name: 'Close' }).click();
  await shot('01-home');
});
await step('pantry draft is remembered', async () => {
  await nav('Pantry');
  await page.fill('#p-name', 'Frozen pork chops'); await page.waitForTimeout(1600);
  await page.reload(); await page.waitForTimeout(1500); await closePopups();
  check('reopening starts on Cook', page.url().includes('/cook'), page.url());
  await nav('Pantry'); await page.locator('#p-name').waitFor();
  check('half-typed item survives a reload', (await page.inputValue('#p-name')) === 'Frozen pork chops');
  await page.click('text=Add to pantry');
  await page.getByText('frozen meat, remember to defrost').waitFor();
  check('frozen meat is detected from the name (auto category)', true);
  await page.getByRole('button', { name: /Frozen meat · tap to start thawing/ }).first().click();
  await page.getByText(/is thawing in the fridge/).waitFor();
  check('start thawing from the pantry', true);
  // Quick add: star a staple, then one tap restocks it
  const eggs = page.locator('main .card', { hasText: /^Eggs/ }).first();
  await eggs.getByRole('button', { name: 'Put Eggs in Quick add' }).click();
  await page.locator('.quick-chip', { hasText: 'Eggs' }).waitFor();
  check('★ puts an item in Quick add', true);
  await eggs.getByRole('button', { name: /^Eggs:/ }).click(); await page.waitForTimeout(300);   // stocked → low
  await page.locator('.quick-chip', { hasText: 'Eggs' }).click(); await page.waitForTimeout(500);
  check('one tap on a Quick add chip restocks it', (await page.locator('.quick-chip.have', { hasText: 'Eggs' }).count()) === 1);
  // Undo a delete
  const before = await page.locator('main .card button[aria-label^="Remove "]').count();
  const victim = (await page.locator('main .card button[aria-label^="Remove "]').first().getAttribute('aria-label')).replace('Remove ', '');
  await page.locator('main .card button[aria-label^="Remove "]').first().click();
  await page.locator('.toast.act').getByRole('button', { name: 'Undo' }).click(); await page.waitForTimeout(6000);
  await page.reload(); await page.waitForTimeout(1500); await closePopups(); await nav('Pantry'); await page.locator('#p-name').waitFor(); await page.waitForTimeout(800);
  check('Undo brings a deleted item back (and it stays)', (await page.locator('main .card button[aria-label^="Remove "]').count()) === before && (await page.locator(`main .card button[aria-label="Remove ${victim}"]`).count()) === 1, victim);
  await shot('02-pantry');
});
await step('cook', async () => {
  await nav('Cook');
  await page.click('text=What can I make?');
  await page.getByText(/recipes? you can make/).waitFor();
  const n = await page.locator('main button.card:has(.chip.have)').count();
  check('cook shows web recipes the pantry can make', n >= 5, `${n} recipes`);
  check('no "Find more online" searches', (await page.getByText('Find more online').count()) === 0 && (await page.getByText('Only real recipes').count()) === 0);
  check('saved recipes moved off Cook', (await page.getByText('Your saved recipes').count()) === 0);
  // Diet filter: every card left wears that tag; Any brings them all back
  const total = parseInt(await page.getByText(/recipes? you can make right now/).innerText(), 10);
  await page.getByRole('radio', { name: 'Vegetarian' }).click(); await page.waitForTimeout(300);
  const veg = await page.locator('main button.card:has(.chip.have)').count();
  const vegTotal = parseInt(await page.getByText(/recipes? you can make right now/).innerText(), 10);
  const vegTagged = await page.locator('main button.card:has(.chip.have):has(.chip.diet.veg), main button.card:has(.chip.have):has(.chip.diet.vegan)').count();
  check('Diet filter: Vegetarian keeps only vegetarian/vegan recipes', veg > 0 && vegTotal < total && veg === vegTagged, `${vegTotal} of ${total}`);
  await page.getByRole('radio', { name: 'Any' }).click(); await page.waitForTimeout(300);
  check('Diet filter: Any shows them all again', (await page.locator('main button.card:has(.chip.have)').count()) === n);
  await page.click('text=Fridge Raid (surprise me)');
  await page.getByText('Ingredients', { exact: true }).waitFor();
  check('Fridge Raid says "Ingredients" and "recipes you can make right now"', (await page.getByText('your hand').count()) === 0 && (await page.getByText(/you can make right now/).count()) >= 1);
  check('Fridge Raid deals 4 pantry items', (await page.locator('.grid2 .card').count()) === 4);
  await page.click('text=What can I make?');
  await page.getByRole('button', { name: /Poor Man's Burrito Bowls/ }).click();
  await page.getByText('Recipe from').waitFor();
  check('recipe sheet links to Budget Bytes', (await page.locator('[role=dialog] .src a').first().getAttribute('href')).includes('budgetbytes.com'));
  const dlg = page.locator('[role=dialog]');
  check('every ingredient is measured (full list from the recipe page)', (await dlg.locator('.ing-list li').count()) >= 6 && (await dlg.locator('.ing-q').filter({ hasText: /\d/ }).count()) >= 5);
  check('numbered beginner steps with measured amounts', (await dlg.locator('ol.steps li').count()) >= 6 && (await dlg.locator('ol.steps .amt').count()) >= 3);
  check('steps say which bowl or pan things go in', /bowl|skillet|pot|pan|baking dish/i.test(await dlg.locator('ol.steps').innerText()));
  check('cooking it is +20 XP', (await dlg.getByText('+20 XP when you cook it').count()) === 1);
  const amt0 = await dlg.locator('ol.steps .amt').first().innerText();
  const ing0 = await dlg.locator('.ing-q').filter({ hasText: /\d/ }).first().innerText();
  await dlg.locator('.servx-in input').fill('3');
  const amt3 = await dlg.locator('ol.steps .amt').first().innerText();
  const ing3 = await dlg.locator('.ing-q').filter({ hasText: /\d/ }).first().innerText();
  const qn = (t) => { const m = t.match(/^(\d+(?:\.\d+)?)?\s*([¼½¾⅓⅔⅛⅜⅝⅞])?/); const F = { '¼': .25, '½': .5, '¾': .75, '⅓': 1 / 3, '⅔': 2 / 3, '⅛': .125, '⅜': .375, '⅝': .625, '⅞': .875 }; return (parseFloat(m?.[1] || 0) || 0) + (F[m?.[2]] || 0); };
  check('type 3 next to the × and every amount triples', Math.abs(qn(amt3) - 3 * qn(amt0)) < .05 && Math.abs(qn(ing3) - 3 * qn(ing0)) < .05 && /x|×/.test(await dlg.locator('.servx-in').innerText()) && /= \d+ servings/.test(await dlg.locator('.servx').innerText()), `${amt0} → ${amt3}, ${ing0} → ${ing3}`);
  await shot('02b-recipe-3x');
  await dlg.locator('.servx-in input').fill('1');
  const tmr = page.locator('[role=dialog] button.timer').first();
  if (await tmr.count()) {
    await tmr.click(); await page.waitForTimeout(1300);
    check('one tap starts the step timer', /\d+:\d\d/.test(await tmr.innerText()) && (await tmr.getAttribute('class')).includes('running'));
    check('a running timer shows in the top bar', (await page.locator('header .pill').count()) === 3);
    await tmr.dblclick(); await page.waitForTimeout(300);
    check('double-tap stops and resets the timer', /min$/.test((await tmr.innerText()).trim()) && (await page.locator('header .pill').count()) === 2);
  } else check('recipe has a step timer', false);
  // Cook mode: big text, one step at a time, tap anywhere for the next step
  await dlg.getByRole('button', { name: 'Cook mode' }).click();
  const cm = page.locator('.cookmode');
  await cm.waitFor();
  check('Cook mode opens on "Get ready" with every ingredient', (await cm.locator('.cm-count').innerText()) === 'Get ready' && (await cm.locator('.cm-ready li').count()) >= 6);
  await cm.locator('.cm-page').click({ position: { x: 300, y: 200 } });
  check('tap anywhere → step 1, in big text', /^Step 1 of \d+$/.test(await cm.locator('.cm-count').innerText()) && parseFloat(await cm.locator('.cm-step p').evaluate((e) => getComputedStyle(e).fontSize)) >= 24);
  await cm.locator('.cm-page').click({ position: { x: 300, y: 200 } });
  await cm.locator('.cm-page').click({ position: { x: 20, y: 200 } });
  check('tap the left edge → back a step', /^Step 1 of/.test(await cm.locator('.cm-count').innerText()));
  await shot('02c-cook-mode');
  await cm.getByRole('button', { name: 'Leave cook mode' }).click();
  check('leaving Cook mode goes back to the recipe', (await page.locator('.cookmode').count()) === 0 && (await dlg.getByText('Recipe from').count()) === 1);
  await page.click('[role=dialog] >> text=Save · +5 XP');
  await page.getByText(/Saved to your cookbook/).waitFor();
  await page.click('[role=dialog] >> text=I cooked it');
  await page.locator('[aria-label="Log a meal"] input[type=file]').setInputFiles(photo);
  await page.click('text=Submit');
  await page.getByRole('heading', { name: 'Cooked it!' }).waitFor({ timeout: 15000 });
  check('submit photo → "Cooked it!" popup', true);
  await page.click('[aria-label="Liked it"]'); await page.waitForTimeout(500);
  await page.locator('.usedup-row').first().waitFor({ timeout: 6000 });
  const usedName = (await page.locator('.usedup-row b').first().innerText()).trim();
  check('after cooking: "Out of … now?" for what the recipe used', /^Out of .+ now\?$/.test((await page.locator('.usedup-row span').first().innerText()).trim()), usedName);
  await page.locator('.usedup-row').first().getByRole('button', { name: 'Yes' }).click();
  await page.locator('.usedup-row', { hasText: 'is out' }).waitFor();
  check('Yes marks it out and puts it on the list', true);
  await shot('03-cooked');
  await page.click('[role=dialog] >> text=Leave');
  await page.waitForTimeout(600); await closePopups();
  await nav('Pantry'); await page.getByRole('tab', { name: 'Saved recipes' }).click();
  await page.click('button.chip:has-text("Liked")');
  await page.locator('main [aria-label=Liked]').first().waitFor();
  check('liked meal shows in Pantry → Saved recipes', (await page.locator('main [aria-label=Liked]').count()) >= 1);
  await page.getByRole('tab', { name: /^Pantry/ }).click();
});
await step('compete', async () => {
  await nav('Compete');
  await page.getByText('Daily quest').waitFor();
  await page.locator('.flip .face').first().waitFor({ timeout: 15000 });
  const cards = await page.locator('.flip').count();
  check('3 challenges picked from your pantry', cards === 3, `${cards}`);
  await page.locator('.flip .face').first().click(); await page.waitForTimeout(700);
  check('tap flips the card to instructions', (await page.locator('.flip.on').count()) === 1);
  check('flipped challenge: numbered, measured steps + servings ×', (await page.locator('.flip.on ol.steps li').count()) >= 5 && (await page.locator('.flip.on ol.steps .amt').count()) >= 2 && (await page.locator('.flip.on .servx').count()) === 1 && (await page.locator('.flip.on .ing-list li').count()) >= 4);
  await page.locator('.flip.on .servx-in input').fill('2');
  check('tapping the servings box does not start the photo step', (await page.locator('[aria-label="Log a meal"]').count()) === 0);
  await shot('04-flip');
  await page.locator('.flip.on .flip-cta').click();
  await page.locator('[aria-label="Log a meal"] input[type=file]').setInputFiles(photo);
  await page.click('text=Submit');
  await page.getByRole('heading', { name: 'Cooked it!' }).waitFor({ timeout: 15000 });
  await page.click('[role=dialog] >> text=Leave'); await page.waitForTimeout(600); await closePopups();
  await page.getByText('Done · coins added').waitFor();
  check('completing a challenge pays coins', true);
  check('shop is no longer on Compete', (await page.getByRole('button', { name: 'Get coins' }).count()) === 0 && (await page.getByText('Picked from recipes').count()) === 0);
});
await step('me', async () => {
  await nav('Me');
  await page.getByRole('heading', { name: 'Passport' }).waitFor();
  check('no pose buttons on Me', (await page.getByRole('button', { name: 'We’re so back!' }).count()) === 0);
  check('closet slots are outline icons', (await page.locator('.slotbar [role=tab] svg').count()) === 5);
  await page.locator('.slotbar [role=tab]').first().click(); await page.waitForTimeout(300);
  const closet = await page.locator('.closet-grid').innerText();
  check('White chef coat is free (worn by default, not for sale)', /White chef coat\s*Free/i.test(closet) && !/White Chef Coat\s*[\d,]+/.test(closet), closet.slice(0, 120));
  check('Airline Pilot Coat is in the shop for 1,500', /Airline Pilot Coat\s*1,500/.test(closet) || (await page.locator('.closet-grid .tile', { hasText: 'Airline Pilot Coat' }).count()) === 1);
  check('accessory slot icon is a bag, not a wooden spoon', (await page.getByText(/wooden spoon/i).count()) === 0 && (await page.locator('.slotbar [role=tab]').last().getAttribute('aria-label')).startsWith('Accessory'));
  check('album has all 193 UN members, 20 a page', (await page.locator('.album .stamp').count()) === 193 && (await page.locator('.album-page').count()) === 10 && (await page.locator('.album-page').first().locator('.stamp').count()) === 20);
  check('pages are numbered', (await page.locator('.album-num').first().textContent()).includes('1'));
  check('stamps stay grey until 10 meals', (await page.locator('.album .stamp.done').count()) === 0);
  check('cooking Mexican counts toward the Mexico stamp', /Mexico, [1-9] of 10/.test(await page.locator('[aria-label^="Mexico, "]').getAttribute('aria-label')));
  const x0 = await page.locator('.album-pages').evaluate((e) => e.scrollLeft);
  await page.getByRole('button', { name: 'Next page' }).click(); await page.waitForTimeout(900);
  check('next page swipes the album across', (await page.locator('.album-pages').evaluate((e) => e.scrollLeft)) > x0 && (await page.locator('.album-dots [aria-selected=true]').getAttribute('aria-label')) === 'Page 2');
  await page.locator('[aria-label^="Mexico, "]').scrollIntoViewIfNeeded().catch(() => {});
  await page.getByRole('button', { name: 'Previous page' }).click(); await page.waitForTimeout(900);
  const stampImg = await page.locator('.album-page').first().locator('.stamp-art img').first().getAttribute('src');
  const ok = await page.evaluate(async (u) => (await fetch(u)).ok, stampImg);
  check('stamp art loads', ok, stampImg);
  check('shop is on Me: every item shown, locked ones greyed with a price', (await page.locator('.closet-grid .locked').count()) >= 5 && /\d/.test(await page.locator('.closet-grid .locked .tprice').first().innerText()));
  await page.getByRole('button', { name: 'Get coins' }).waitFor();
  check('Get coins is on Me', true);
  await page.click('[aria-label^="Edit name"]'); await page.fill('#nm', 'Chef J ✨ #1'); await page.press('#nm', 'Enter');
  await page.getByRole('heading', { name: 'Chef J ✨ #1' }).waitFor();
  check('name can be any characters', true);
  check('last device is remembered in the background (not shown)', (await page.getByText('Last played on').count()) === 0);
  await shot('05-me');
});
await step('compete layout', async () => {
  await nav('Compete'); await page.getByText('Cuisine bingo').waitFor();
  const yB = (await page.getByRole('heading', { name: 'Cuisine bingo' }).boundingBox()).y, yQ = (await page.getByText('Daily quest').boundingBox()).y;
  check('cuisine bingo is at the top of Compete', yB < yQ, `${yB} < ${yQ}`);
  check('bingo has no text under the title any more (no "Get four in a row", no own timer)', (await page.locator('section[aria-labelledby=bingo-h] p').count()) === 0 && (await page.getByText('Get four in a row').count()) === 0 && (await page.locator('section[aria-labelledby=bingo-h]').getByText(/resets|\d+d\b/i).count()) === 0);
  const wantD = (() => { const n = new Date(); const d = (8 - n.getDay()) % 7 || 7; const mon = new Date(n.getFullYear(), n.getMonth(), n.getDate() + d); return Math.max(1, Math.ceil((mon - n) / 864e5)); })();
  check('one reset timer at the top, counting to Monday like the challenges', (await page.getByText(/^Resets in \d+d$/).count()) === 1 && (await page.getByText(`Resets in ${wantD}d`).count()) === 1);
  await nav('Me'); await page.getByRole('heading', { name: 'Passport' }).waitFor();
});
await step('buy coins with Apple Pay', async () => {
  const before = Number((await page.locator('header .pill').nth(1).innerText()).replace(/\D/g, ''));
  await page.getByRole('button', { name: 'Get coins' }).first().click();
  await page.getByText('$2.00', { exact: true }).waitFor();
  check('Get coins shows the 4 packs, Apple Pay / Google Pay / card, no Bitcoin', (await page.locator('[aria-label="Get coins"] button.card').count()) === 4 && /Apple Pay/.test(await page.locator('[aria-label="Get coins"]').innerText()) && !/bitcoin/i.test(await page.locator('[aria-label="Get coins"]').innerText()));
  await page.getByText('$2.00', { exact: true }).click();
  await page.waitForURL('**/stripe-checkout/**', { timeout: 15000 });
  check('pack opens the Stripe checkout page (Apple Pay)', /Apple Pay/.test(await page.locator('h1').innerText()));
  const ss = (await (await fetch('http://localhost:54321/__e2e/stripe-sessions')).json()).at(-1);
  check('checkout is $2.00 USD for a Whisk order', ss.amount_total === 200 && ss.currency === 'usd' && /^[0-9a-f-]{36}$/.test(ss.metadata.order_id) && ss.success_url.endsWith('/me?paid=1'), JSON.stringify(ss));
  const hook = async (body, sig) => (await fetch(`${BASE}/api/coins/webhook`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Stripe-Signature': sig }, body })).status;
  const body = JSON.stringify({ id: 'evt_test', type: 'checkout.session.completed', data: { object: { id: ss.id, object: 'checkout.session' } } });
  const sign = (b, t = Math.floor(Date.now() / 1000)) => `t=${t},v1=` + crypto.createHmac('sha256', 'whsec_e2e').update(`${t}.${b}`).digest('hex');
  check('webhook with a bad signature is rejected', (await hook(body, 't=1,v1=00')) === 401);
  check('an old (replayed) signature is rejected', (await hook(body, sign(body, Math.floor(Date.now() / 1000) - 3600))) === 401);
  check('unpaid checkout credits nothing', (await hook(body, sign(body))) === 200);
  await fetch(`http://localhost:54321/__e2e/stripe-pay/${ss.id}`);
  check('paid checkout webhook accepted', (await hook(body, sign(body))) === 200);
  await hook(body, sign(body)); // Stripe retries
  await page.goto(`${BASE}/me?paid=1`); await page.waitForTimeout(1500); await closePopups();
  const after = Number((await page.locator('header .pill').nth(1).innerText()).replace(/\D/g, ''));
  check('1,000 coins credited exactly once', after === before + 1000, `${before} → ${after}`);
});
await step('me settings', async () => {
  await nav('Me'); await page.getByText('Settings').waitFor();
  check('autosave is not shown', (await page.getByText('Autosave').count()) === 0);
  check('day counter starts at Day 1', (await page.locator('.dayno').innerText()) === 'Day 1');
  await page.getByRole('button', { name: /Cookies & privacy/ }).click();
  check('cookie choices can be reopened from Settings', await page.getByRole('dialog', { name: 'Your choices' }).isVisible());
  check('Settings shows 4 purposes incl. usage data (on, from Accept), essential locked on', (await page.locator('.cc-switch').count()) === 4 && (await page.getByText('Help improve Whisk').count()) === 1 && (await page.locator('.cc-switch.locked[aria-checked=true]').count()) === 1 && (await page.locator('.cc-switch[aria-checked=true]').count()) === 4);
  check('your time zone is used for days', (await page.locator('.cc-text em').innerText()).includes('America/New York'));
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Bigger text' }).click(); await page.waitForTimeout(200);
  check('text size goes up', (await page.locator('main').evaluate((m) => getComputedStyle(m).zoom)) === '1.1');
  await page.getByRole('button', { name: 'Smaller text' }).click(); await page.waitForTimeout(200);
  check('text size goes back down', ['1', 'normal'].includes(await page.locator('main').evaluate((m) => getComputedStyle(m).zoom)));
  check('reset game is a tiny link', (await page.getByRole('button', { name: 'Reset game' }).evaluate((b) => parseFloat(getComputedStyle(b).fontSize))) <= 12);
  check('no takeout price setting on Me', (await page.locator('#takeout').count()) === 0 && (await page.getByText('Typical takeout').count()) === 0);
  await page.getByRole('button', { name: 'Reset game' }).click();
  check('reset: type RESET (no password, no Google)', (await page.locator('[aria-label="Reset game"] input[type=password]').count()) === 0 && await page.getByRole('button', { name: 'Reset my game' }).isDisabled());
  await page.fill('#rs-word', 'reset');
  check('typing RESET unlocks the button', await page.getByRole('button', { name: 'Reset my game' }).isEnabled());
  await page.locator('[aria-label="Reset game"]').getByRole('button', { name: 'Cancel' }).last().click();
});
await step('reload keeps everything', async () => {
  await page.goto(`${BASE}/me`); await page.waitForTimeout(1800); await closePopups();
  check('every open starts on Cook', page.url().includes('/cook'), page.url());
  check('no tour or popup on later opens (first time only)', (await page.locator('.coach').count()) === 0 && (await page.locator('.popup-scrim').count()) === 0);
  check('no "Welcome back" again within 24 hours', (await page.locator('.hud-hello.on').count()) === 0);
  await nav('Me');
  check('name persisted', await page.getByRole('heading', { name: 'Chef J ✨ #1' }).waitFor({ timeout: 8000 }).then(() => true, () => false));
});
await step('free dish search', async () => {
  await nav('Cook');
  check('no country pop-up list on the search box', (await page.locator('#o-countries, datalist').count()) === 0 && (await page.locator('#o-dish').getAttribute('list')) === null);
  await page.fill('#o-dish', 'albanian food'); await page.getByRole('button', { name: 'Search dishes' }).click();
  await page.getByText('Byrek', { exact: true }).first().waitFor({ timeout: 15000 });
  check('a country (any way you write it) lists that country\'s dishes', /Dishes from Albania/i.test(await page.locator('section[aria-live] .eyebrow').first().innerText()) && (await page.locator('.dish-row:not(.skel)').count()) >= 8);
  await page.getByRole('button', { name: 'Byrek: show ingredients and video' }).click();
  const card = page.locator('.dflip.on');
  await card.locator('.ytbtn').waitFor({ timeout: 15000 });
  check('tapping a dish flips it to have / need', (await card.locator('.chip.have').count()) >= 1 && (await card.locator('.chip.need').count()) >= 1 && /you have \d+ of \d+/i.test(await card.innerText()));
  const yt = await card.locator('a.ytbtn').getAttribute('href');
  check('YouTube button: most-watched video that is really about the dish', yt === 'https://www.youtube.com/watch?v=BIGmatch001', yt);
  check('YouTube logo on the button', (await card.locator('.ytbtn svg path[fill="#FF0000"]').count()) === 1);
  await shot('07-dish-flip');
  await card.getByRole('button', { name: /Add \d+ missing to shopping list/ }).click(); await page.getByText(/Added \d+ to your shopping list/).waitFor();
  check('missing ingredients go to the shopping list', true);
  check('"I cooked it" on the card', (await card.getByRole('button', { name: 'I cooked it' }).count()) === 1);
  await card.getByRole('button', { name: 'Flip back' }).click(); await page.waitForTimeout(600);
  await page.getByRole('button', { name: 'Fli: show ingredients and video' }).click();
  await page.locator('.dflip.on .ytbtn').waitFor({ timeout: 15000 });
  check('no video about the dish on YouTube → logo greyed out', (await page.locator('.dflip.on .ytbtn.off').count()) === 1 && (await page.locator('.dflip.on a.ytbtn').count()) === 0);
  await shot('07b-dish-noyt');
  await page.locator('.dflip.on').getByRole('button', { name: 'Flip back' }).click(); await page.waitForTimeout(500);
  // the 10th Albanian meal stamps Albania and pays 5,000 coins
  await fetch('http://localhost:54321/__e2e/seed-meals?country=AL&n=9');
  const c0 = Number((await page.locator('header .pill').nth(1).innerText()).replace(/\D/g, ''));
  await page.getByRole('button', { name: 'Byrek: show ingredients and video' }).click();
  await page.locator('.dflip.on').getByRole('button', { name: 'I cooked it' }).click();
  await page.locator('[aria-label="Log a meal"] input[type=file]').setInputFiles(photo);
  check('dish counts toward its country', /Albania stamp/.test(await page.locator('[aria-label="Log a meal"]').innerText()));
  await page.locator('[aria-label="Log a meal"]').getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('heading', { name: 'Cooked it!' }).waitFor({ timeout: 15000 });
  await page.getByRole('button', { name: 'Leave' }).click();
  await page.getByRole('heading', { name: 'New stamp!' }).waitFor({ timeout: 8000 });
  await shot('07c-stamp');
  const c1 = Number((await page.locator('header .pill').nth(1).innerText()).replace(/\D/g, ''));
  check('10th meal from a country: stamp popup and +5,000 coins', /Albania is stamped/.test(await page.locator('.popup').innerText()) && c1 - c0 === 5000, `${c0} → ${c1}`);
  await page.getByRole('button', { name: 'Nice!' }).click(); await page.waitForTimeout(600);
  if (await page.getByText('Level up!', { exact: false }).count()) { await page.locator('[aria-label=Close]').first().click(); await page.waitForTimeout(400); }
  for (const [q, want] of [['pesto', 'Pesto'], ['chickpeas', 'Falafel'], ['sauce', 'Chimichurri'], ['pho', 'Pho']]) {
    await page.fill('#o-dish', q); await page.getByRole('button', { name: 'Search dishes' }).click();
    const ok = await page.getByText(want, { exact: true }).first().waitFor({ timeout: 8000 }).then(() => true, () => false);
    check(`search anything: "${q}" finds ${want}`, ok);
  }
  await page.fill('#o-dish', 'salsa macha'); await page.getByRole('button', { name: 'Search dishes' }).click();
  await page.getByText('Salsa macha', { exact: true }).first().waitFor({ timeout: 15000 });
  check('not in Whisk\'s list → free Wikipedia search, food articles only', (await page.locator('.dish-row:not(.skel)').count()) === 1 && (await page.getByText('Macha (film)').count()) === 0);
  await page.getByRole('button', { name: 'Salsa macha: show ingredients and video' }).click();
  await page.locator('.dflip.on .ytbtn').waitFor({ timeout: 15000 });
  const chips = await page.locator('.dflip.on .chip').allInnerTexts();
  check('its ingredients come from the Wikipedia infobox', chips.some((c) => /dried chiles/i.test(c)) && chips.some((c) => /garlic/i.test(c)) && chips.some((c) => /sesame seeds/i.test(c)), JSON.stringify(chips));
  const free = await (await fetch('http://localhost:54321/__e2e/free-calls')).json();
  check('no AI used for search (costs nothing)', !free.anthropic.includes('web_search') && free.wiki >= 1 && free.youtube.length >= 1, JSON.stringify(free));
  await page.evaluate(() => window.scrollTo(0, 0));
  check('just an "Add Channel" button: no heading, no explainer text, no built-in channels', (await page.locator('.channel').count()) === 0 && (await page.getByRole('button', { name: 'Add Channel' }).count()) === 1 && (await page.getByText(/Your YouTubers|They’ll be right here/).count()) === 0 && (await page.getByText(/You Suck at Cooking|Not Another Cooking Show/).count()) === 0);
  await page.getByRole('button', { name: 'Add Channel' }).click();
  const yIn = page.getByPlaceholder(/@andy_cooks/);
  await yIn.fill('javascript:alert(1)'); await page.getByRole('button', { name: 'Add', exact: true }).click();
  check('a non-YouTube link is refused', (await page.getByRole('alert').filter({ hasText: 'doesn’t look like a YouTube channel' }).count()) === 1 && (await page.locator('.channel').count()) === 0);
  await yIn.fill('https://m.youtube.com/@MockKitchen/videos'); await page.getByPlaceholder('Andy Cooks').fill('Mock Kitchen');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  check('added channel opens inside Whisk', (await page.locator('.channel a[href^="/cook/channel?u="]', { hasText: 'Mock Kitchen' }).count()) === 1);
  await page.getByRole('button', { name: 'Add Channel' }).click(); await yIn.fill('@mockkitchen'); await page.getByRole('button', { name: 'Add', exact: true }).click();
  check('the same channel can’t be added twice', (await page.getByText('Already on your list.').count()) === 1);
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.waitForTimeout(900); await page.reload(); await page.getByRole('button', { name: 'Add Channel' }).waitFor();
  check('your channels are saved with your game', (await page.locator('.channel', { hasText: 'Mock Kitchen' }).count()) === 1);
  // the channel page: cooking videos only, then cook along
  await page.route('https://www.youtube-nocookie.com/**', (r) => r.fulfill({ body: '<body style="background:#000"></body>', contentType: 'text/html' }));
  await page.locator('.channel a', { hasText: 'Mock Kitchen' }).click(); await page.waitForURL('**/cook/channel**');
  await page.locator('.vid-card:not(.skel)').first().waitFor({ timeout: 10000 });
  const titles = await page.locator('.vid-title').allInnerTexts();
  check('channel page lists its cooking videos and leaves out the Q&A', titles.includes('Crispy Honey Garlic Chicken') && titles.includes('Weeknight Carbonara') && !titles.some((t) => /Q&A/.test(t)), JSON.stringify(titles));
  check('the Cook tab stays lit on a channel page', (await page.locator('.nav a[href="/cook"][aria-current="page"]').count()) === 1);
  await page.locator('.vid-card', { hasText: 'Honey Garlic' }).click();
  const src = await page.locator('.vc-player iframe').getAttribute('src');
  check('video plays in Whisk from where the cooking starts (0:45) and stops before the taste test', /^https:\/\/www\.youtube-nocookie\.com\/embed\/RECIPEvid01\?/.test(src) && /start=45/.test(src) && /end=425/.test(src), src);
  check('steps one at a time from the description', /Step 1 of 3/.test(await page.locator('.vc-count').innerText()) && /Pat the chicken dry/.test(await page.locator('.vc-text').innerText()));
  await page.getByRole('button', { name: 'Next' }).click();
  check('big Next moves to the next step', /Step 2 of 3/.test(await page.locator('.vc-count').innerText()));
  await page.getByRole('button', { name: /Ingredients \(4\)/ }).click();
  check('ingredients from the description, grouped', /For the sauce/i.test(await page.locator('.vc-ing').innerText()) && /½ cup honey/.test(await page.locator('.vc-ing').innerText()));
  check('full written recipe links to the YouTuber’s site, not social media', (await page.locator('a', { hasText: 'Full written recipe' }).getAttribute('href')) === 'https://mockkitchen.example/recipes/honey-chicken');
  await shot('05b-cook-along');
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('.vid-card', { hasText: 'Carbonara' }).click();
  check('no written recipe: the steps are the video’s cooking chapters (intro and thanks left out)', /Step 1 of 3 · 1:12/.test(await page.locator('.vc-count').innerText()) && /Boiling the pasta/.test(await page.locator('.vc-text').innerText()));
  await page.getByRole('button', { name: 'Close' }).click();
  await page.goto(`${BASE}/cook`); await page.getByRole('button', { name: 'Add Channel' }).waitFor();
  await page.getByRole('button', { name: 'Remove Mock Kitchen' }).click();
  check('remove a channel', (await page.locator('.channel').count()) === 0);
});
await step('cook off with a friend', async () => {
  const pill = async (pg) => Number((await pg.locator('header .pill').last().innerText()).replace(/\D/g, ''));
  // your invite code (Get coins → Invite a friend)
  await nav('Me'); await page.waitForURL('**/me'); await page.getByRole('button', { name: /Get coins/ }).first().click();
  await page.locator('.invite-code b').waitFor();
  const myCode = (await page.locator('.invite-code b').innerText()).trim();
  check('Get coins has Invite a friend with your 6-letter code (1,000 each)', /^[A-Z2-9]{6}$/.test(myCode) && /1,000 each/.test(await page.locator('.invite').innerText()));
  await shot('06a-invite');
  await page.locator('[role=dialog][aria-label="Get coins"] button[aria-label="Close"]').click();
  // a friend starts Whisk from the invite link on their own phone
  const ctx2 = await browser.newContext({ viewport: { width: 390, height: 844 }, timezoneId: 'America/New_York' });
  const fr = await ctx2.newPage();
  await fr.goto(`${BASE}/login?ref=${myCode}`); await fr.getByRole('radio', { name: 'Accept' }).click(); await fr.getByRole('button', { name: 'Start playing' }).click();
  await fr.waitForURL('**/cook'); const invToast = await fr.locator('.toast', { hasText: /Invited by/ }).waitFor({ timeout: 10000 }).then(() => fr.locator('.toast').innerText(), () => '');
  check('the friend’s game picks up the invite from the link', /Invited by (?!a friend)/.test(invToast), invToast);
  // host makes a game
  const c0 = await pill(page);
  await nav('Compete'); await page.waitForURL('**/compete'); await page.locator('.co-card').waitFor();
  check('Compete has Cook Off: pick the time, make a game or join with a code', (await page.locator('.co-times [role=radio]').count()) === 4 && (await page.getByRole('button', { name: 'Make a game' }).count()) === 1 && (await page.getByPlaceholder('Game code').count()) === 1);
  await page.locator('.co-times [role=radio]', { hasText: '30 min' }).click();
  await page.getByRole('button', { name: 'Make a game' }).click(); await page.waitForURL('**/compete/cookoff?code=*');
  const code = new URL(page.url()).searchParams.get('code');
  await page.locator('.co-code b').waitFor();
  check('the lobby shows the code big, and you (host)', (await page.locator('.co-code b').innerText()) === code && /\(you\)/.test(await page.locator('.co-chip.me').innerText()) && (await page.locator('.co-chip.me svg').count()) === 1);
  // friend joins with the code
  await fr.getByRole('navigation').getByRole('link', { name: 'Compete', exact: true }).click(); await fr.waitForURL('**/compete');
  await fr.getByPlaceholder('Game code').fill(code.toLowerCase()); await fr.getByRole('button', { name: 'Join', exact: true }).click();
  await fr.waitForURL('**/compete/cookoff?code=*'); await fr.getByText('Waiting for the host to start…').waitFor();
  await page.locator('.co-chip', { hasText: /^Cook 2/ }).waitFor({ timeout: 6000 });
  check('a friend joins with the code; both screens list both cooks', (await page.locator('.co-chip').count()) === 2 && (await fr.locator('.co-chip').count()) === 2);
  await shot('06b-lobby');
  check('only the host has Start', (await fr.getByRole('button', { name: 'Start the Cook Off' }).count()) === 0);
  // a judge: someone new opens the "Invite judges" link, starts Whisk, lands in the game just to vote
  check('the lobby has "Invite judges to vote"', (await page.getByRole('button', { name: 'Invite judges to vote' }).count()) === 1);
  const ctx3 = await browser.newContext({ viewport: { width: 390, height: 844 }, timezoneId: 'America/New_York' });
  const jd = await ctx3.newPage();
  await jd.goto(`${BASE}/vote/${code}`); await jd.waitForURL('**/login?vote=*');
  check('a judge link sends someone new to the start screen with an invite note', /invited to judge a Cook Off/.test(await jd.locator('.judge-note').innerText()));
  await jd.getByRole('radio', { name: 'Accept' }).click(); await jd.getByRole('button', { name: 'Start playing' }).click();
  await jd.waitForURL('**/compete/cookoff?code=*&as=judge'); await jd.getByText('You’re a judge.', { exact: false }).waitFor({ timeout: 10000 });
  await page.locator('.co-chip.judge').waitFor({ timeout: 6000 });
  check('…and joins as a judge (no pantry needed); the host sees them under Judges', (await page.locator('.co-chip.judge').count()) === 1 && (await jd.getByRole('button', { name: 'Start the Cook Off' }).count()) === 0);
  await page.getByRole('button', { name: 'Start the Cook Off' }).click();
  await page.locator('.co-full .bw').waitFor({ timeout: 8000 });
  await fr.locator('.co-full .bw').waitFor({ timeout: 8000 });
  check('start: both phones go full screen and spin the wheel', (await page.locator('.nav').isVisible()) === true && (await page.locator('.co-full').evaluate((e) => getComputedStyle(e).position === 'fixed' && e.getBoundingClientRect().height >= innerHeight - 1)));
  await page.waitForTimeout(1500); await shot('06c-wheel');
  const blur = await page.locator('#bw-blur feGaussianBlur').getAttribute('stdDeviation');
  check('arcade drum: wooden planks with recipes roll between two arrows, motion-blurred up and down while fast', (await page.locator('.bw-plank').count()) === 24 && (await page.locator('.bw-arrow').count()) === 2 && /^0 (?!0(\.00)?$)/.test(blur), blur);
  await page.locator('.co-timer').waitFor({ timeout: 15000 }); await fr.locator('.co-timer').waitFor({ timeout: 15000 });
  const t1 = await page.locator('.co-timer').innerText(), t2 = await fr.locator('.co-timer').innerText();
  const secs = (t) => { const [m, s] = t.replace(/[^\d:]/g, '').split(':').map(Number); return m * 60 + s; };
  check('then your recipe with ingredients, steps and one shared clock', Math.abs(secs(t1) - secs(t2)) <= 2 && secs(t1) > 25 * 60 && secs(t1) <= 30 * 60 && (await page.locator('.co-cook .ing-list li').count()) > 2 && (await page.locator('.co-cook ol.steps li').count()) > 2, `${t1} / ${t2}`);
  check('the restaurant scene of that dish is behind it', (await page.locator('.co-cook .scene svg image').count()) >= 3);
  await shot('06d-cook');
  for (const pg of [page, fr]) await pg.locator('.co-snap input[type=file]').setInputFiles('e2e/plate.jpg');
  await page.locator('.co-plates').waitFor({ timeout: 15000 }); await fr.locator('.co-plates').waitFor({ timeout: 15000 });
  await jd.locator('.co-plates').waitFor({ timeout: 15000 });
  check('both plates in → voting starts on every phone, judges included', /Vote for the best plate/.test(await page.locator('.co-big').innerText()) && (await page.locator('.co-plate img').count()) === 2 && /Judge: pick the best plate/.test(await jd.locator('.co-big').innerText()));
  check('you can’t vote for your own plate', await page.locator('.co-plate', { hasText: '(you)' }).isDisabled());
  await shot('06e-vote');
  check('voting is pick, then Submit', (await page.getByRole('button', { name: 'Tap a plate to pick it' }).isDisabled()));
  for (const pg of [page, fr]) { await pg.locator('.co-plate:not([disabled])').click(); await pg.getByRole('button', { name: 'Submit vote' }).click(); }
  await jd.locator('.co-plate', { hasText: /\(you\)/ }).count();
  const hostName = (await page.locator('.co-plate', { hasText: '(you)' }).locator('b').innerText()).replace(' (you)', '');
  await jd.locator('.co-plate', { hasText: hostName }).click(); await jd.getByRole('button', { name: 'Submit vote' }).click();
  await jd.waitForURL('**/cook', { timeout: 8000 });
  check('after the judge submits, Whisk takes them to the start of the app', jd.url().endsWith('/cook'));
  await page.getByText(/It’s a tie!|wins!/).waitFor({ timeout: 10000 });
  check('everyone voted → winner screen (the judge broke the tie)', /wins!/.test(await page.locator('.co-big').innerText()));
  check('your coins: +1,000 for the win', /\+1,000 coins/.test(await page.locator('.co-reward').innerText()));
  await shot('06f-winner');
  await page.getByRole('link', { name: 'Back to Compete' }).click(); await page.waitForURL('**/compete');
  await page.waitForTimeout(800);
  const c1 = await pill(page);
  check('coins: win (+1,000) + invite reward (+1,000)', c1 - c0 === 2000, `${c0} → ${c1}`);
  await ctx2.close(); await ctx3.close();
});
await step('activity backend', async () => {
  await page.waitForTimeout(4500); await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
  const ev = await (await fetch('http://localhost:54321/__e2e/events')).json();
  check('taps, picks and searches are recorded', ev.some((e) => e.kind === 'tap') && ev.some((e) => e.kind === 'search' && e.value === 'albanian food') && ev.some((e) => e.kind === 'view'), `${ev.length} events`);
  check('typed text in other fields is not recorded', !ev.some((e) => /Frozen pork chops|Chef J/.test(e.value || '')));
  await page.goto(`${BASE}/admin`); await page.waitForTimeout(1500);
  check('backend page is closed to non-admins', await page.getByText('This page is only for Whisk admins.').isVisible());
  await fetch('http://localhost:54321/__e2e/make-admin');
  await page.reload(); await page.getByRole('heading', { name: 'Backend' }).waitFor({ timeout: 8000 });
  check('admins see the backend dashboard', (await page.locator('.adm-tiles .adm-card').count()) === 5);
  check('dashboard lists top searches and the activity feed', (await page.getByRole('cell', { name: 'albanian food' }).count()) >= 1 && (await page.locator('.adm td').count()) > 10);
  await shot('08-backend');
});
await step('never show me, vacation, streak repair note', async () => {
  await page.goto(`${BASE}/cook`); await page.waitForTimeout(1200); await closePopups();
  await page.click('text=What can I make?'); await page.getByText(/recipes? you can make right now/).waitFor();
  const n0 = parseInt(await page.getByText(/recipes? you can make right now/).innerText(), 10);
  await nav('Me'); await page.getByRole('button', { name: /Never show me/ }).click();
  const ns = page.locator('[role=dialog][aria-label="Never show me"]');
  check('Never show me: one-tap allergies + any ingredient, and a check-the-label note', (await ns.locator('.never-pick .chip').count()) === 9 && (await ns.getByText(/always check the label/).count()) === 1);
  await ns.getByRole('button', { name: 'Eggs' }).click();
  await ns.locator('#never-w').fill('Cilantro'); await ns.getByRole('button', { name: 'Add ingredient' }).click();
  await ns.getByRole('button', { name: 'Save' }).click(); await page.waitForTimeout(600);
  check('saved: the row says how many are hidden', /2 hidden/.test(await page.getByRole('button', { name: /Never show me/ }).innerText()));
  await nav('Cook'); await page.click('text=What can I make?'); await page.getByText(/recipes? you can make right now/).waitFor();
  const n1 = parseInt(await page.getByText(/recipes? you can make right now/).innerText(), 10);
  await page.locator('main button.card:has(.chip.have)').first().click(); await page.getByText('Recipe from').waitFor();
  const ingText = (await page.locator('[role=dialog] .ing-list').innerText()).toLowerCase();
  check('recipes with eggs or cilantro are gone from Cook', n1 < n0 && !/\begg|cilantro/.test(ingText), `${n0} → ${n1}`);
  await page.locator('[role=dialog] [aria-label="Close"]').first().click();
  await nav('Me'); await page.getByRole('button', { name: /Never show me/ }).click();
  await ns.getByRole('button', { name: 'Eggs' }).click(); await ns.getByRole('button', { name: 'Show cilantro again' }).click(); await ns.getByRole('button', { name: 'Save' }).click(); await page.waitForTimeout(500);
  check('clearing it shows everything again', /Allergies, dislikes/.test(await page.getByRole('button', { name: /Never show me/ }).innerText()));
  await page.getByRole('switch', { name: 'Vacation mode' }).click(); await page.waitForTimeout(600);
  check('vacation mode on: the streak pill shows a plane', (await page.getByRole('switch', { name: 'Vacation mode' }).getAttribute('aria-checked')) === 'true' && /paused/.test(await page.locator('header .pill[data-tip=streak]').getAttribute('title')));
  await page.getByRole('switch', { name: 'Vacation mode' }).click(); await page.waitForTimeout(600);
  check('vacation mode off again', (await page.getByRole('switch', { name: 'Vacation mode' }).getAttribute('aria-checked')) === 'false');
  check('streak repair is explained', (await page.getByText(/Cook twice the next day and your streak comes back/).count()) === 1);
});
await step('share the shopping list', async () => {
  await nav('Pantry'); await page.getByRole('tab', { name: /Shopping list/ }).click();
  await page.locator('#s-new').fill('Basil'); await page.locator('#s-new').press('Enter'); await page.waitForTimeout(500);
  await page.getByRole('button', { name: /Share list/ }).click();
  const link = page.getByLabel('Share link'); await page.waitForFunction(() => /\/list\/[a-f0-9]{32}$/.test(document.querySelector('[aria-label="Share link"]')?.value || ''));
  const url = await link.inputValue();
  check('Share list makes a secret link', /\/list\/[a-f0-9]{32}$/.test(url));
  await page.getByRole('dialog', { name: 'Share your list' }).getByRole('button', { name: 'Close' }).click();
  const ctx4 = await browser.newContext({ viewport: { width: 390, height: 844 } }); const sh = await ctx4.newPage();
  const resp = await sh.goto(url);
  check('the link opens with no account, is never cached, and leaks no referrer', /no-store/.test(resp.headers()['cache-control'] || '') && resp.headers()['referrer-policy'] === 'no-referrer');
  await sh.locator('.sl-item', { hasText: 'Basil' }).waitFor();
  check('the shared page shows the list by aisle', (await sh.locator('.sl-item').count()) >= 1 && (await sh.locator('.eyebrow', { hasText: 'Produce' }).count()) === 1);
  await sh.locator('.sl-item', { hasText: 'Basil' }).click(); await sh.waitForTimeout(600);
  check('anyone with the link can tick an item', (await sh.locator('.sl-item.done', { hasText: 'Basil' }).count()) === 1);
  await sh.screenshot({ path: SHOTS ? path.join(SHOTS, '09-shared-list.png') : '/dev/null' }).catch(() => {});
  await page.reload(); await page.waitForTimeout(1200); await closePopups(); await nav('Pantry'); await page.getByRole('tab', { name: /Shopping list/ }).click();
  await page.locator('.card.ticked', { hasText: 'Basil' }).waitFor({ timeout: 6000 });
  check('…and the tick shows on the owner’s list', true);
  await page.getByRole('button', { name: /Share list/ }).click(); await page.getByRole('button', { name: 'Turn the link off' }).click(); await page.waitForTimeout(500);
  await sh.reload(); await sh.getByText('This link is off').waitFor({ timeout: 6000 });
  check('turning the link off stops it working', true);
  await ctx4.close();
});
await step('delete my data', async () => {
  const ctx5 = await browser.newContext({ viewport: { width: 390, height: 844 } }); const dp = await ctx5.newPage();
  await dp.goto(`${BASE}/login`); await dp.getByRole('radio', { name: 'Accept' }).click(); await dp.getByRole('button', { name: 'Start playing' }).click(); await dp.waitForURL('**/cook');
  await dp.waitForTimeout(1500); await dp.mouse.click(5, 400);
  await dp.getByRole('navigation').getByRole('link', { name: 'Me', exact: true }).click(); await dp.waitForURL('**/me');
  const uid = await dp.locator('.mono').first().innerText();
  await dp.getByRole('button', { name: 'Delete my data' }).click();
  const del = dp.getByRole('dialog', { name: 'Delete my data' });
  check('Delete my data asks you to type DELETE first', await del.getByRole('button', { name: 'Delete everything' }).isDisabled());
  await del.getByLabel('Type DELETE to confirm').fill('delete'); await del.getByRole('button', { name: 'Delete everything' }).click();
  await dp.waitForURL('**/login?deleted=1', { timeout: 15000 });
  check('after deleting, you land on the start screen with a goodbye', (await dp.getByText('Your data is deleted').count()) === 1);
  await dp.goto(`${BASE}/me`); check('the old game is gone (signed out)', dp.url().includes('/login'));
  check('the player’s id is a real one (sanity)', /^[0-9a-f-]{36}$/.test(uid), uid);
  await ctx5.close();
});
await step('no-store', async () => { const r = await page.request.get(`${BASE}/home`); check('signed-in pages are Cache-Control no-store', /no-store/.test(r.headers()['cache-control'] || '')); });

const csp = problems.filter((p) => /Content Security Policy|Refused to/.test(p));
check('no CSP violations', csp.length === 0, csp.slice(0, 3).join(' | '));
const other = problems.filter((p) => !csp.includes(p) && !/rpc\/admin_(overview|events)/.test(p));   // the backend refusing a non-admin is expected
check('no page errors or failed requests', other.length === 0, other.slice(0, 5).join(' | '));
await browser.close();
const failed = results.filter((r) => r[0] === 'FAIL').length;
console.log(`\n${results.length - failed}/${results.length} passed`);
process.exit(failed ? 1 : 0);
