// End-to-end walk through every screen against e2e/mock-supabase.mjs.
//   1. node e2e/mock-supabase.mjs &
//   2. NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321 NEXT_PUBLIC_SUPABASE_ANON_KEY=anon-mock NEXT_PUBLIC_SITE_URL=http://localhost:3000 npx next build
//   3. ANTHROPIC_API_KEY=mock ANTHROPIC_BASE_URL=http://localhost:54321/anthropic npx next start -p 3000 &
//   4. node e2e/run.mjs [screenshot-dir]
import { createRequire } from 'node:module';
import zlib from 'node:zlib';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright'); // dev-only; resolved from NODE_PATH or a local install

const BASE = process.env.E2E_BASE || 'http://localhost:3000';
const SHOTS = process.argv[2] || null;
if (SHOTS) fs.mkdirSync(SHOTS, { recursive: true });

function png(w = 64, h = 64) {
  const crcT = Array.from({ length: 256 }, (_, n) => { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; return c >>> 0; });
  const crc = (b) => { let c = 0xffffffff; for (const x of b) c = crcT[(c ^ x) & 255] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; };
  const chunk = (t, d) => { const l = Buffer.alloc(4); l.writeUInt32BE(d.length); const td = Buffer.concat([Buffer.from(t), d]); const c = Buffer.alloc(4); c.writeUInt32BE(crc(td)); return Buffer.concat([l, td, c]); };
  const ihdr = Buffer.alloc(13); ihdr.writeUInt32BE(w, 0); ihdr.writeUInt32BE(h, 4); ihdr[8] = 8; ihdr[9] = 2;
  const raw = Buffer.alloc((w * 3 + 1) * h); for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) { const o = y * (w * 3 + 1) + 1 + x * 3; raw[o] = 230; raw[o + 1] = 160 + (x % 40); raw[o + 2] = 80; }
  return Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk('IHDR', ihdr), chunk('IDAT', zlib.deflateSync(raw)), chunk('IEND', Buffer.alloc(0))]);
}
const photo = { name: 'plate.png', mimeType: 'image/png', buffer: png() };

const results = [];
const check = (name, ok, detail = '') => { results.push([ok ? 'PASS' : 'FAIL', name, detail]); console.log(ok ? 'PASS' : 'FAIL', name, detail); };
const problems = [];

const browser = await chromium.launch({ args: ['--use-gl=swiftshader', '--enable-webgl', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, timezoneId: 'America/New_York' });
const page = await ctx.newPage();
page.setDefaultTimeout(12000);
page.on('console', (m) => { if (m.type() === 'error' && !/Failed to load resource/.test(m.text())) problems.push(`console: ${m.text()}`); });
page.on('pageerror', (e) => problems.push(`pageerror: ${e.message}`));
page.on('response', (r) => { if (r.status() >= 400 && !/api\/barcode/.test(r.url())) problems.push(`HTTP ${r.status()} ${r.request().method()} ${r.url()}`); });
const shot = async (n) => { if (SHOTS) await page.screenshot({ path: path.join(SHOTS, `${n}.png`), fullPage: true }); };
const step = async (name, fn) => { try { await fn(); } catch (e) { check(name, false, e.message.split('\n').filter((l) => /locator|Timeout|waiting/.test(l)).slice(0, 3).join(' | ')); await shot(`fail-${name.replace(/\W+/g, '-')}`); } };
const nav = (n) => page.getByRole('navigation').getByRole('link', { name: n, exact: true }).click();
const closePopups = async () => { await page.locator('.popup-scrim').first().waitFor({ timeout: 3000 }).catch(() => {}); for (let i = 0; i < 4; i++) { const x = page.locator('.popup-scrim [aria-label=Close]').first(); const leave = page.locator('.popup-scrim').getByRole('button', { name: 'Leave' }).first(); if (await x.count()) await x.click(); else if (await leave.count()) await leave.click(); else break; await page.waitForTimeout(400); } };

await step('signed-out redirect', async () => { await page.goto(`${BASE}/home`); check('signed-out /home redirects to /login', page.url().includes('/login')); });
await step('log in', async () => {
  check('no account: no email, no password, no Google', (await page.locator('input[type=password], input[type=email], #email, #password').count()) === 0 && (await page.getByText(/Google/).count()) === 0 && (await page.getByRole('button', { name: 'Start playing' }).count()) === 1);
  check('a plain-words disclaimer says what is recorded', /records what you do in the app/.test(await page.locator('.disclaimer').innerText()));
  check('Start stays off until you Accept or Decline', await page.getByRole('button', { name: 'Start playing' }).isDisabled());
  await page.getByRole('radio', { name: 'Decline' }).click();
  check('Decline says you can still play, nothing recorded', /still play everything, and nothing you do is recorded/.test(await page.locator('.disclaimer').innerText()));
  await page.getByRole('radio', { name: 'Accept' }).click();
  await shot('00-login');
  await page.getByRole('button', { name: 'Start playing' }).click(); await page.waitForURL('**/cook', { timeout: 15000 });
  check('Start playing makes a phone-only game and lands on Cook', (await (await fetch('http://localhost:54321/__e2e/anon-signups')).json()).n === 1);
  check('no second cookie popup: the Accept from the start screen was saved to the game', (await page.locator('.cc-scrim').count()) === 0);
  // No tour: you land straight in the app; Chef explains each thing the first time you tap it.
  check('no walkthrough: nothing covers the app on first open', (await page.locator('.coach, .tour-scrim').count()) === 0);
  await page.locator('.tip-card').waitFor({ timeout: 6000 });
  check('Chef says hello once, in one line, with no step numbers', /Welcome to Whisk/.test(await page.locator('.tip-card').innerText()) && !/\b\d+ of \d+\b/.test(await page.locator('.tip-card').innerText()));
  await page.locator('.hud-hello.on').waitFor({ timeout: 6000 }).catch(() => {});
  check('the greeting shows in the top bar', /Welcome to Whisk/.test(await page.locator('.hud-hello').innerText()));
  await shot('00b-welcome-tip');
  await page.locator('.nav a[href="/pantry"]').click(); await page.waitForURL('**/pantry');
  await page.locator('.tip-card', { hasText: 'Pantry' }).waitFor({ timeout: 4000 });
  check('tapping a new tab still opens it, and Chef explains it', page.url().includes('/pantry') && /real kitchen/.test(await page.locator('.tip-card').innerText()));
  const tipBox = await page.locator('.tip-card').boundingBox(); const add = await page.locator('[data-tour="add"]').boundingBox();
  check('the tip sits at the top, clear of the buttons', tipBox.y < 200 && tipBox.y + tipBox.height < add.y);
  await page.locator('#p-name').click();
  await page.locator('.tip-card').waitFor({ state: 'detached', timeout: 3000 });
  check('tapping anything else puts the tip away', true);
  await page.locator('.nav a[href="/cook"]').click(); await page.waitForURL('**/cook'); await page.locator('.tip-card', { hasText: 'Cook' }).waitFor({ timeout: 4000 }); await page.locator('.tip-ok').click();
  await page.locator('.nav a[href="/pantry"]').click(); await page.waitForURL('**/pantry'); await page.waitForTimeout(700);
  check('each tip shows only once', (await page.locator('.tip-card').count()) === 0);
  await page.fill('#p-name', 'Bananas'); await page.locator('[data-tour="add"]').click();
  await page.locator('.tip-card', { hasText: 'Add to pantry' }).waitFor({ timeout: 4000 });
  check('first Add explains XP; the item is still added', await page.locator('main').getByText('Bananas', { exact: true }).first().waitFor({ timeout: 6000 }).then(() => true, () => false));
  // name + the first kitchen thing (from the Me page)
  await page.locator('.nav a[href="/me"]').click(); await page.waitForURL('**/me');
  await page.locator('.tip-ok').click({ timeout: 2000 }).catch(() => {});
  await page.locator('.namebtn').click(); await page.locator('#nm').fill('Jai'); await page.locator('#nm').press('Enter');
  await page.waitForFunction(() => document.querySelector('.namebtn h1')?.textContent === 'Jai', null, { timeout: 6000 });
  check('name set from the Me page', true);
  check('no Whisk dance, no closet on Me', (await page.getByRole('button', { name: 'Dance' }).count()) === 0 && (await page.locator('.slotbar').count()) === 0);
  const coins0 = Number((await page.locator('header .pill').nth(1).innerText()).replace(/\D/g, ''));
  await page.locator('.shop-grid .tile').filter({ hasText: 'Knife block' }).click();
  await page.locator('[data-tour="buy"]').click();
  await page.waitForFunction((c0) => Number((document.querySelectorAll('header .pill')[1]?.textContent || '').replace(/\D/g, '')) !== c0, coins0, { timeout: 6000 }).catch(() => {});
  const coins1 = Number((await page.locator('header .pill').nth(1).innerText()).replace(/\D/g, ''));
  check('a knife block (800) can be bought with the starting coins', coins0 - coins1 === 800, `${coins0} → ${coins1}`);
  check('what you buy goes straight into your kitchen (a starter one if you had none)', await page.locator('#my-kitchen .kthing img[alt="Knife block"]').waitFor({ timeout: 8000 }).then(() => true, () => false));
  await page.locator('.tip-ok').click().catch(() => {});
  // the globe (on Compete): swipe left/right to spin; the dart only flies while it's spinning
  await page.locator('.nav a[href="/compete"]').click(); await page.waitForURL('**/compete');
  await page.locator('.globe-svg path.gl-c').nth(150).waitFor({ state: 'attached', timeout: 10000 });
  check('globe shows every country, unnamed and grey', (await page.locator('.globe-svg path.gl-c').count()) >= 190 && (await page.locator('.globe-svg text').count()) === 0);
  await page.locator('.globe-svg').scrollIntoViewIfNeeded(); await page.waitForTimeout(2600);
  check('can’t throw until it spins', await page.locator('.globe-throw').isDisabled());
  const gb = await page.locator('.globe-svg').boundingBox();
  await page.mouse.move(gb.x + 60, gb.y + gb.height * 0.42); await page.mouse.down();
  await page.mouse.move(gb.x + gb.width - 40, gb.y + gb.height * 0.42, { steps: 6 }); await page.mouse.up();
  await page.locator('.globe-throw.ready').waitFor({ timeout: 2000 });
  check('a swipe spins it and wakes up the dart', await page.locator('.globe-throw').isEnabled());
  await page.locator('.globe-throw').click();
  await page.locator('.globe-hit').waitFor({ timeout: 6000 });
  check('the dart lands on a country and names it (no exclamation mark)', !/!/.test(await page.locator('.globe-hit b').first().innerText()) && (await page.locator('.globe-hit b').first().innerText()).length > 2 && (await page.locator('.globe-hit').getByRole('button', { name: 'Cook it' }).count()) === 1);
  await shot('00c-me-globe');
  await nav('Home');
});
await step('home', async () => {
  await page.getByRole('heading', { name: 'Discover a Dish' }).waitFor();
  check('home shows Discover a Dish', true);
  // budget price tags + the difficulty knob
  check('price tags ($ to $$$$) and a small difficulty knob in one slim row', (await page.locator('.df-tag').count()) === 4 && (await page.locator('.df-knob').count()) === 1 && (await page.locator('.df').boundingBox()).height < 70);
  await page.locator('.rcard').first().waitFor();
  await page.locator('.df-tag', { hasText: 'Pocket change' }).click(); await page.waitForTimeout(300);
  const tags = await page.locator('.rcard .chip.price').allInnerTexts();
  check('Pocket change shows only dishes under $2 a serving', tags.length > 0 && tags.every((t) => t.startsWith('$ ·')), tags.slice(0, 3).join(' | '));
  await page.locator('.df-knobwrap').click(); await page.waitForTimeout(300);
  const heat = await page.locator('.rcard .chip.heat').allInnerTexts();
  check('…and the knob narrows it to Easy', heat.every((t) => t === 'Easy') && (await page.locator('.df-lvl.on').innerText()).includes('Easy'), heat.join(','));
  await shot('01a-home-filters');
  await page.locator('.df-tag', { hasText: 'Pocket change' }).click(); for (let k = 0; k < 3; k++) await page.locator('.df-knobwrap').click();
  check('home has no challenges or Fridge Raid', (await page.getByText('This week’s challenges').count()) === 0 && (await page.getByText('Fridge Raid').count()) === 0);
  await page.getByText('Ground beef is frozen').waitFor();
  check('home reminds you to defrost frozen ground beef', true);
  await page.locator('.src a').first().waitFor();
  check('almost-ready recipes link to their source site', /^https:\/\//.test(await page.locator('.src a').first().getAttribute('href')));
  check('home: just a "Full recipe" link (no "From"), no recipe count, no "items away" on the cards', (await page.locator('.src', { hasText: /^From/ }).count()) === 0 && (await page.locator('.src a', { hasText: 'Full recipe' }).count()) > 0 && !/\d+ recipes?$/.test(await page.locator('.page-title').first().innerText()) && (await page.locator('main .card .eyebrow', { hasText: /away/ }).count()) === 0);
  for (let i = 0; i < 8 && (await page.locator('.away-h').count()) < 2; i++) { const more = page.getByRole('button', { name: 'Show more' }); if (!(await more.count())) break; await more.click(); await page.waitForTimeout(150); }
  check('almost ready is grouped by items missing, closest first, no limit', (await page.locator('.away-h').count()) >= 2 && /1 item away/i.test(await page.locator('.away-h').first().innerText()) && /2 items away/i.test(await page.locator('.away-h').nth(1).innerText()));
  await page.evaluate(() => window.scrollTo(0, 0));
  check('pantry hint is the short version', (await page.getByText('Whisk reads').count()) === 0);
  // open one: tap a single missing ingredient under "What you have" to put it in the pantry
  check('postcards are all drawn by Whisk (no emoji pictures)', (await page.locator('main .rcard-art image').count()) === 0);
  check('every recipe card has a postcard of where the dish comes from (landmark + dish)', (await page.locator('main .rcard .rcard-art svg').count()) === (await page.locator('main .rcard').count()) && (await page.locator('main .rcard').count()) > 0);
  const chipCounts = await page.locator('main .rcard').evaluateAll((cs) => cs.map((c) => c.querySelectorAll('.chip.need').length));
  check('home shows at most 3 missing ingredients per card', chipCounts.every((n) => n <= 3), JSON.stringify(chipCounts.slice(0, 12)));
  const card0 = page.locator('main .rcard', { has: page.locator('.more-need') }).first();
  const shownN = await card0.locator('.chip.need').count();
  const moreN = Number(((await card0.locator('.more-need').innerText()).match(/\d+/) || [0])[0]);
  const cuisine0 = (await card0.locator('.eyebrow').innerText()).trim();
  await card0.getByRole('button', { name: 'Open recipe' }).click();
  const sheet = page.locator('[role=dialog].sheet');
  await sheet.locator('button.add-ing').first().waitFor();
  const needNames = (await sheet.locator('button.add-ing').allInnerTexts()).map((t) => t.replace(/^\+\s*/, '').trim());
  check('open it: every ingredient you still need is listed (the card’s 3 + the rest)', needNames.length === shownN + moreN, `${shownN}+${moreN} vs ${needNames.length}`);
  const ingOrder = (await sheet.locator('.ing-list li.need').allInnerTexts()).map((t) => t.toLowerCase());
  { let j = 0; for (const n of needNames) if (j < ingOrder.length && ingOrder[j].includes(n.toLowerCase())) j++;
    check('…in the recipe’s own order, marked in the ingredient list', ingOrder.length > 0 && j === ingOrder.length, `${needNames.join(', ')} | ${ingOrder.join(' / ')}`); }
  check('…seasonings, oil, butter and herbs included', needNames.some((n) => /salt|pepper|oil|butter|powder|seasoning|thyme|oregano|cumin|paprika|sauce|vinegar|sugar/i.test(n)), needNames.join(', '));
  const miss = sheet.locator('button.add-ing').first(); const missName = needNames[0];
  await miss.click();
  await page.locator('.toast', { hasText: 'is in your pantry' }).waitFor({ timeout: 6000 });
  check('tap one you already have: it goes in the pantry and off the list', (await sheet.locator('button.add-ing', { hasText: missName }).count()) === 0, missName);
  check('the recipe gets a soft cultural backdrop for its cuisine', (await sheet.getAttribute('class')).includes('cx') && !!(await sheet.getAttribute('data-motif')) && (await sheet.getAttribute('data-motif')) !== 'dots', `${cuisine0} → ${await sheet.getAttribute('data-motif')}`);
  await shot('01b-recipe-culture');
  await sheet.getByRole('button', { name: 'Close' }).click();
  await shot('01-home');
});
await step('pantry draft is remembered', async () => {
  await nav('Pantry');
  await page.fill('#p-name', 'Frozen pork chops'); await page.waitForTimeout(1600);
  await page.reload(); await page.waitForTimeout(1500); await closePopups();
  check('reopening starts on Cook', page.url().includes('/cook'), page.url());
  await nav('Pantry'); await page.locator('#p-name').waitFor();
  check('half-typed item survives a reload', (await page.inputValue('#p-name')) === 'Frozen pork chops');
  await page.click('text=Add to pantry');
  await page.getByText('frozen meat, remember to defrost').waitFor();
  check('frozen meat is detected from the name (auto category)', true);
  await page.getByRole('button', { name: /Frozen meat · tap to start thawing/ }).first().click();
  await page.getByText(/is thawing in the fridge/).waitFor();
  check('start thawing from the pantry', true);
  // Quick add: star a staple, then one tap restocks it
  const eggs = page.locator('main .card', { hasText: /^Eggs/ }).first();
  await eggs.getByRole('button', { name: 'Put Eggs in Quick add' }).click();
  await page.locator('.quick-chip', { hasText: 'Eggs' }).waitFor();
  check('★ puts an item in Quick add', true);
  await eggs.getByRole('button', { name: /^Eggs:/ }).click(); await page.waitForTimeout(300);   // stocked → low
  await page.locator('.quick-chip', { hasText: 'Eggs' }).click(); await page.waitForTimeout(500);
  check('one tap on a Quick add chip restocks it', (await page.locator('.quick-chip.have', { hasText: 'Eggs' }).count()) === 1);
  // Undo a delete
  const before = await page.locator('main .card button[aria-label^="Remove "]').count();
  const victim = (await page.locator('main .card button[aria-label^="Remove "]').first().getAttribute('aria-label')).replace('Remove ', '');
  await page.locator('main .card button[aria-label^="Remove "]').first().click();
  await page.locator('.toast.act').getByRole('button', { name: 'Undo' }).click(); await page.waitForTimeout(6000);
  await page.reload(); await page.waitForTimeout(1500); await closePopups(); await nav('Pantry'); await page.locator('#p-name').waitFor(); await page.waitForTimeout(800);
  check('Undo brings a deleted item back (and it stays)', (await page.locator('main .card button[aria-label^="Remove "]').count()) === before && (await page.locator(`main .card button[aria-label="Remove ${victim}"]`).count()) === 1, victim);
  await shot('02-pantry');
});
await step('cook', async () => {
  await nav('Cook');
  await page.click('text=What can I make?');
  await page.getByText(/recipes? you can make/).waitFor();
  const n = await page.locator('main button.card:has(.chip.have)').count();
  check('cook shows web recipes the pantry can make', n >= 5, `${n} recipes`);
  check('no "Find more online" searches', (await page.getByText('Find more online').count()) === 0 && (await page.getByText('Only real recipes').count()) === 0);
  check('saved recipes moved off Cook', (await page.getByText('Your saved recipes').count()) === 0);
  // Diet filter: every card left wears that tag; Any brings them all back
  const total = parseInt(await page.getByText(/recipes? you can make right now/).innerText(), 10);
  await page.getByRole('radio', { name: 'Vegetarian' }).click(); await page.waitForTimeout(300);
  const veg = await page.locator('main button.card:has(.chip.have)').count();
  const vegTotal = parseInt(await page.getByText(/recipes? you can make right now/).innerText(), 10);
  const vegTagged = await page.locator('main button.card:has(.chip.have):has(.chip.diet.veg), main button.card:has(.chip.have):has(.chip.diet.vegan)').count();
  check('Diet filter: Vegetarian keeps only vegetarian/vegan recipes', veg > 0 && vegTotal < total && veg === vegTagged, `${vegTotal} of ${total}`);
  await page.getByRole('radio', { name: 'Any' }).click(); await page.waitForTimeout(300);
  check('Diet filter: Any shows them all again', (await page.locator('main button.card:has(.chip.have)').count()) === n);
  await page.getByRole('button', { name: 'Fridge Raid', exact: true }).click();
  await page.getByText('Ingredients', { exact: true }).waitFor();
  check('Fridge Raid says "Ingredients" and "recipes you can make right now"', (await page.getByText('your hand').count()) === 0 && (await page.getByText(/you can make right now/).count()) >= 1);
  check('Fridge Raid deals 4 pantry items', (await page.locator('.grid2 .card').count()) === 4);
  await page.click('text=What can I make?');
  await page.getByRole('button', { name: /Poor Man's Burrito Bowls/ }).click();
  await page.getByText('Recipe from').waitFor();
  check('recipe sheet links to Budget Bytes', (await page.locator('[role=dialog] .src a').first().getAttribute('href')).includes('budgetbytes.com'));
  const dlg = page.locator('[role=dialog]');
  check('every ingredient is measured (full list from the recipe page)', (await dlg.locator('.ing-list li').count()) >= 6 && (await dlg.locator('.ing-q').filter({ hasText: /\d/ }).count()) >= 5);
  check('numbered beginner steps with measured amounts', (await dlg.locator('ol.steps li').count()) >= 6 && (await dlg.locator('ol.steps .amt').count()) >= 3);
  check('steps say which bowl or pan things go in', /bowl|skillet|pot|pan|baking dish/i.test(await dlg.locator('ol.steps').innerText()));
  check('cooking it is +100 XP and 500 coins', (await dlg.getByText('+100 XP · 500 coins when you cook it').count()) === 1);
  check('no row of outside links at the bottom of the recipe', (await dlg.locator('.links').count()) === 0 && (await dlg.locator('a', { hasText: /^(Google|YouTube|TikTok|Reddit)$/ }).count()) === 0);
  const amt0 = await dlg.locator('ol.steps .amt').first().innerText();
  const ing0 = await dlg.locator('.ing-q').filter({ hasText: /\d/ }).first().innerText();
  await dlg.locator('.servx-in input').fill('3');
  const amt3 = await dlg.locator('ol.steps .amt').first().innerText();
  const ing3 = await dlg.locator('.ing-q').filter({ hasText: /\d/ }).first().innerText();
  const qn = (t) => { const m = t.match(/^(\d+(?:\.\d+)?)?\s*([¼½¾⅓⅔⅛⅜⅝⅞])?/); const F = { '¼': .25, '½': .5, '¾': .75, '⅓': 1 / 3, '⅔': 2 / 3, '⅛': .125, '⅜': .375, '⅝': .625, '⅞': .875 }; return (parseFloat(m?.[1] || 0) || 0) + (F[m?.[2]] || 0); };
  check('type 3 next to the × and every amount triples', Math.abs(qn(amt3) - 3 * qn(amt0)) < .05 && Math.abs(qn(ing3) - 3 * qn(ing0)) < .05 && /x|×/.test(await dlg.locator('.servx-in').innerText()) && /= \d+ servings/.test(await dlg.locator('.servx').innerText()), `${amt0} → ${amt3}, ${ing0} → ${ing3}`);
  await shot('02b-recipe-3x');
  await dlg.locator('.servx-in input').fill('1');
  const tmr = page.locator('[role=dialog] button.timer').first();
  if (await tmr.count()) {
    await tmr.click(); await page.waitForTimeout(1300);
    check('one tap starts the step timer', /\d+:\d\d/.test(await tmr.innerText()) && (await tmr.getAttribute('class')).includes('running'));
    check('a running timer shows in the top bar', (await page.locator('header .pill').count()) === 3);
    await tmr.dblclick(); await page.waitForTimeout(300);
    check('double-tap stops and resets the timer', /min$/.test((await tmr.innerText()).trim()) && (await page.locator('header .pill').count()) === 2);
  } else check('recipe has a step timer', false);
  // Cook mode: big text, one step at a time, tap anywhere for the next step
  await dlg.getByRole('button', { name: 'Cook mode' }).click();
  const cm = page.locator('.cookmode');
  await cm.waitFor();
  check('Cook mode opens on "Get ready" with every ingredient', (await cm.locator('.cm-count').innerText()) === 'Get ready' && (await cm.locator('.cm-ready li').count()) >= 6);
  await cm.locator('.cm-page').click({ position: { x: 300, y: 200 } });
  check('tap anywhere → step 1, in big text', /^Step 1 of \d+$/.test(await cm.locator('.cm-count').innerText()) && parseFloat(await cm.locator('.cm-step p').evaluate((e) => getComputedStyle(e).fontSize)) >= 24);
  await cm.locator('.cm-page').click({ position: { x: 300, y: 200 } });
  await cm.locator('.cm-page').click({ position: { x: 20, y: 200 } });
  check('tap the left edge → back a step', /^Step 1 of/.test(await cm.locator('.cm-count').innerText()));
  await shot('02c-cook-mode');
  await cm.getByRole('button', { name: 'Leave cook mode' }).click();
  check('leaving Cook mode goes back to the recipe', (await page.locator('.cookmode').count()) === 0 && (await dlg.getByText('Recipe from').count()) === 1);
  await page.click('[role=dialog] >> text=Save · +5 XP');
  await page.getByText(/Saved to your cookbook/).waitFor();
  await page.click('[role=dialog] >> text=I cooked it');
  await page.locator('[aria-label="Log a meal"] input[type=file]').setInputFiles(photo);
  await page.click('text=Submit');
  await page.getByRole('heading', { name: 'Cooked it!' }).waitFor({ timeout: 15000 });
  check('submit photo → "Cooked it!" popup', true);
  check('cooking pays +100 XP and +500 coins', await page.locator('.toast', { hasText: /\+\d+ XP · \+500 coins/ }).count().then((n) => n >= 1).catch(() => false) || /500 coins/.test(await page.locator('.toast').allInnerTexts().then((t) => t.join(' '))), await page.locator('.toast').allInnerTexts().then((t) => t.join(' | ')));
  await page.click('[aria-label="Liked it"]'); await page.waitForTimeout(500);
  await page.locator('.usedup-row').first().waitFor({ timeout: 6000 });
  const usedName = (await page.locator('.usedup-row b').first().innerText()).trim();
  check('after cooking: "Out of … now?" for what the recipe used', /^Out of .+ now\?$/.test((await page.locator('.usedup-row span').first().innerText()).trim()), usedName);
  await page.locator('.usedup-row').first().getByRole('button', { name: 'Yes' }).click();
  await page.locator('.usedup-row', { hasText: 'is out' }).waitFor();
  check('Yes marks it out and puts it on the list', true);
  const shareSw = page.getByRole('switch', { name: 'Share this plate with friends' });
  check('plates start private (Share with friends is off)', (await shareSw.getAttribute('aria-checked')) === 'false');
  await shareSw.click(); await page.waitForTimeout(500);
  check('one tap shares this plate with friends', (await shareSw.getAttribute('aria-checked')) === 'true');
  await shot('03-cooked');
  await page.click('[role=dialog] >> text=Leave');
  await page.waitForTimeout(600); await closePopups();
  await nav('Cook');
  check('Cook: Saved recipes has its own box under search', (await page.locator('main .saved-box h2', { hasText: 'Saved recipes' }).count()) === 1 && (await page.locator('main .card', { has: page.locator('#o-dish') }).count()) === 1);
  await page.locator('.saved-box .saved-open').first().waitFor();
  check('Saved recipes: just the recipes (no All / Liked / Disliked buttons), each with an unsave button', (await page.locator('.saved-box button.chip').count()) === 0 && (await page.locator('.saved-box .saved-open', { hasText: /Burrito Bowls/ }).count()) >= 1 && (await page.locator('.saved-box .saved-x').count()) >= 1);
  await nav('Pantry'); await page.getByRole('tab', { name: 'Kitchen' }).waitFor();
  const tabsNow = (await page.getByRole('tab').allInnerTexts()).map((t) => t.replace(/\s*\(\d+\)/, '').trim()).join('|');
  check('Pantry tabs: Pantry, Shopping list, Kitchen (saved recipes moved to Cook)', tabsNow === 'Pantry|Shopping list|Kitchen', tabsNow);
});
await step('compete', async () => {
  await nav('Compete');
  await page.locator('.globe').waitFor();
  await page.locator('.flip .face').first().waitFor({ timeout: 15000 });
  const cards = await page.locator('.flip').count();
  check('3 challenges picked from your pantry', cards === 3, `${cards}`);
  await page.locator('.flip .face').first().click(); await page.waitForTimeout(700);
  check('tap flips the card to instructions', (await page.locator('.flip.on').count()) === 1);
  check('flipped challenge: numbered, measured steps + servings ×', (await page.locator('.flip.on ol.steps li').count()) >= 5 && (await page.locator('.flip.on ol.steps .amt').count()) >= 2 && (await page.locator('.flip.on .servx').count()) === 1 && (await page.locator('.flip.on .ing-list li').count()) >= 4);
  await page.locator('.flip.on .servx-in input').fill('2');
  check('tapping the servings box does not start the photo step', (await page.locator('[aria-label="Log a meal"]').count()) === 0);
  await shot('04-flip');
  await page.locator('.flip.on .flip-cta').click();
  await page.locator('[aria-label="Log a meal"] input[type=file]').setInputFiles(photo);
  await page.click('text=Submit');
  await page.getByRole('heading', { name: 'Cooked it!' }).waitFor({ timeout: 15000 });
  await page.click('[role=dialog] >> text=Leave'); await page.waitForTimeout(600); await closePopups();
  await page.getByText('Done · coins added').waitFor();
  check('completing a challenge pays coins', true);
  check('shop is no longer on Compete', (await page.getByRole('button', { name: 'Get coins' }).count()) === 0 && (await page.getByText('Picked from recipes').count()) === 0);
});
await step('me', async () => {
  await nav('Me');
  await page.locator('.pcard').waitFor();
  check('no pose buttons, no tier list, no "Your world" heading on Me', (await page.getByRole('button', { name: 'We’re so back!' }).count()) === 0 && (await page.locator('.tier-row').count()) === 0 && (await page.getByRole('heading', { name: 'Your world' }).count()) === 0);
  check('the daily quest moved to Me (the globe is on Compete now)', (await page.locator('[data-tip="quest"]').count()) === 1 && (await page.locator('.globe').count()) === 0);
  check('your level title shows under your name', (await page.locator('.me-tag').innerText()).length > 3);
  const pc = await page.locator('.pcard').innerText();
  check('profile: Level, Recipes, Ingredients, Countries, Streak (no Restaurant)', ['Level', 'Recipes', 'Ingredients', 'Countries', 'Streak'].every((k) => new RegExp(k, 'i').test(pc)) && !/Restaurant|Riverwalk Apartment/i.test(pc), pc);
  check('a progress bar to the next home, named only', /Ybor City Loft|Hyde Park Bungalow|Bayshore Condo/.test(pc) && !/Level \d+: move/.test(pc) && (await page.locator('.pcard-next .bar').count()) === 1);
  check('the kitchen stands in a cut-away room (floor slab + walls that hide on the near side), no box or wallpaper', (await page.locator('#my-kitchen .kw').count()) === 3 && (await page.locator('#my-kitchen .kwin').count()) === 1 && (await page.locator('#my-kitchen .k3-bg').count()) === 0 && (await page.locator('#my-kitchen .k3.placed').count()) === 1);
  check('the kitchen’s heading is where it is (or its name), with Edit on the same line', /Riverwalk Apartment|Ybor City Loft/.test(await page.locator('#my-kitchen .mk-title').innerText()) && Math.abs((await page.locator('#my-kitchen .mk-title').boundingBox()).y - (await page.locator('#my-kitchen .mk-bar a').boundingBox()).y) < 30);
  check('no pencil next to your name, no "Lv" text', (await page.locator('.namebtn svg').count()) === 0 && (await page.locator('.page-title').first().getByText(/^Lv /).count()) === 0);
  check('Kitchen shop opens on kitchen things with prices, no appliances', (await page.locator('.shop-grid .tile').count()) >= 20 && /\d/.test(await page.locator('.shop-grid .tile .tprice').first().innerText()) && (await page.locator('.shop [role=tab]', { hasText: 'Appliances' }).count()) === 0 && (await page.locator('.shop-grid .tile', { hasText: 'Gas range' }).count()) === 0);
  check('country things stay hidden until that country is done (no teaser text)', (await page.locator('.shop-grid .tile', { hasText: 'Molcajete' }).count()) === 0 && (await page.getByText(/Finish a country/).count()) === 0);
  await page.locator('.shop [role=tab]', { hasText: 'Finishes' }).click();
  check('finishes: terrazzo, lacquer, copper, gold marble', (await page.locator('.shop-grid .tile').count()) === 4);
  await page.locator('.shop [role=tab]', { hasText: 'Dogs' }).click();
  const dogTiles = await page.locator('.shop-grid .tile').count();
  const dogPrices = new Set(await page.locator('.shop-grid .tile .tprice').allInnerTexts());
  check('fridge magnets: 100+ dog breeds, all one price', dogTiles >= 100 && dogPrices.size === 1, `${dogTiles} · ${[...dogPrices]}`);
  await page.locator('.shop [role=tab]', { hasText: 'Cats' }).click();
  check('…every cat breed too', (await page.locator('.shop-grid .tile').count()) >= 40);
  await page.locator('.shop [role=tab]', { hasText: 'Cards & art' }).click();
  const paper = await page.locator('.shop-grid').innerText();
  check('cards & art: report cards, test scores, wedding invitations, Christmas cards, drawings', ['report card', 'test', 'wedding', 'christmas', 'drawing'].every((w) => paper.toLowerCase().includes(w)), paper.slice(0, 200));
  await page.locator('.shop [role=tab]', { hasText: 'Dogs' }).click();
  await page.locator('.shop-grid .tile', { hasText: 'Golden Retriever' }).click(); await page.locator('[data-tour="buy"]').click();
  check('a bought magnet sticks to the fridge in your kitchen', await page.locator('#my-kitchen img.kmag').first().waitFor({ state: 'attached', timeout: 8000 }).then(() => true, () => false));
  await page.locator('.shop [role=tab]', { hasText: 'Kitchen' }).click();
  await page.getByRole('button', { name: 'Get coins' }).waitFor();
  check('Get coins is on Me', true);
  await page.click('[aria-label^="Edit name"]'); await page.fill('#nm', 'Chef J ✨ #1'); await page.press('#nm', 'Enter');
  await page.getByRole('heading', { name: 'Chef J ✨ #1' }).waitFor();
  check('name can be any characters', true);
  check('last device is remembered in the background (not shown)', (await page.getByText('Last played on').count()) === 0);
  await shot('05-me');
});
await step('compete layout', async () => {
  await nav('Compete'); await page.getByText('Cuisine bingo').waitFor();
  const yB = (await page.getByRole('heading', { name: 'Cuisine bingo' }).boundingBox()).y, yQ = (await page.locator('.globe').boundingBox()).y;
  check('cuisine bingo is at the top of Compete, the globe where the daily quest was', yB < yQ, `${yB} < ${yQ}`);
  check('cooking Mexican shows on the globe (Bronze)', await page.locator('.globe-svg path.gl-c.bronze').first().waitFor({ state: 'attached', timeout: 8000 }).then(() => true, () => false));
  check('bingo has no text under the title any more (no "Get four in a row", no own timer)', (await page.locator('section[aria-labelledby=bingo-h] p').count()) === 0 && (await page.getByText('Get four in a row').count()) === 0 && (await page.locator('section[aria-labelledby=bingo-h]').getByText(/resets|\d+d\b/i).count()) === 0);
  const wantD = (() => { const n = new Date(); const d = (8 - n.getDay()) % 7 || 7; const mon = new Date(n.getFullYear(), n.getMonth(), n.getDate() + d); return Math.max(1, Math.ceil((mon - n) / 864e5)); })();
  check('one reset timer at the top, counting to Monday like the challenges', (await page.getByText(/^Resets in \d+d$/).count()) === 1 && (await page.getByText(`Resets in ${wantD}d`).count()) === 1);
  await nav('Me'); await page.locator('.pcard').waitFor();
});
await step('buy coins with Apple Pay', async () => {
  const before = Number((await page.locator('header .pill').nth(1).innerText()).replace(/\D/g, ''));
  await page.getByRole('button', { name: 'Get coins' }).first().click();
  await page.getByText('$2.00', { exact: true }).waitFor();
  check('Get coins shows the 4 packs, Apple Pay / Google Pay / card, no Bitcoin', (await page.locator('[aria-label="Get coins"] button.card').count()) === 4 && /Apple Pay/.test(await page.locator('[aria-label="Get coins"]').innerText()) && !/bitcoin/i.test(await page.locator('[aria-label="Get coins"]').innerText()));
  await page.getByText('$2.00', { exact: true }).click();
  await page.waitForURL('**/stripe-checkout/**', { timeout: 15000 });
  check('pack opens the Stripe checkout page (Apple Pay)', /Apple Pay/.test(await page.locator('h1').innerText()));
  const ss = (await (await fetch('http://localhost:54321/__e2e/stripe-sessions')).json()).at(-1);
  check('checkout is $2.00 USD for a Whisk order', ss.amount_total === 200 && ss.currency === 'usd' && /^[0-9a-f-]{36}$/.test(ss.metadata.order_id) && ss.success_url.endsWith('/me?paid=1'), JSON.stringify(ss));
  const hook = async (body, sig) => (await fetch(`${BASE}/api/coins/webhook`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Stripe-Signature': sig }, body })).status;
  const body = JSON.stringify({ id: 'evt_test', type: 'checkout.session.completed', data: { object: { id: ss.id, object: 'checkout.session' } } });
  const sign = (b, t = Math.floor(Date.now() / 1000)) => `t=${t},v1=` + crypto.createHmac('sha256', 'whsec_e2e').update(`${t}.${b}`).digest('hex');
  check('webhook with a bad signature is rejected', (await hook(body, 't=1,v1=00')) === 401);
  check('an old (replayed) signature is rejected', (await hook(body, sign(body, Math.floor(Date.now() / 1000) - 3600))) === 401);
  check('unpaid checkout credits nothing', (await hook(body, sign(body))) === 200);
  await fetch(`http://localhost:54321/__e2e/stripe-pay/${ss.id}`);
  check('paid checkout webhook accepted', (await hook(body, sign(body))) === 200);
  await hook(body, sign(body)); // Stripe retries
  await page.goto(`${BASE}/me?paid=1`); await page.waitForTimeout(1500); await closePopups();
  const after = Number((await page.locator('header .pill').nth(1).innerText()).replace(/\D/g, ''));
  check('1,000 coins credited exactly once', after === before + 1000, `${before} → ${after}`);
});
await step('me settings', async () => {
  await nav('Me'); await page.getByText('Settings').waitFor();
  check('autosave is not shown', (await page.getByText('Autosave').count()) === 0);
  check('day counter starts at Day 1', (await page.locator('.dayno').innerText()) === 'Day 1');
  await page.getByRole('button', { name: /Cookies & privacy/ }).click();
  check('cookie choices can be reopened from Settings', await page.getByRole('dialog', { name: 'Your choices' }).isVisible());
  check('Settings shows 4 purposes incl. usage data (on, from Accept), essential locked on', (await page.locator('.cc-switch').count()) === 4 && (await page.getByText('Help improve Whisk').count()) === 1 && (await page.locator('.cc-switch.locked[aria-checked=true]').count()) === 1 && (await page.locator('.cc-switch[aria-checked=true]').count()) === 4);
  check('your time zone is used for days', (await page.locator('.cc-text em').innerText()).includes('America/New York'));
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Bigger text' }).click(); await page.waitForTimeout(200);
  check('text size goes up', (await page.locator('main').evaluate((m) => getComputedStyle(m).zoom)) === '1.1');
  await page.getByRole('button', { name: 'Smaller text' }).click(); await page.waitForTimeout(200);
  check('text size goes back down', ['1', 'normal'].includes(await page.locator('main').evaluate((m) => getComputedStyle(m).zoom)));
  check('reset game is a tiny link', (await page.getByRole('button', { name: 'Reset game' }).evaluate((b) => parseFloat(getComputedStyle(b).fontSize))) <= 12);
  check('no takeout price setting on Me', (await page.locator('#takeout').count()) === 0 && (await page.getByText('Typical takeout').count()) === 0);
  await page.getByRole('button', { name: 'Reset game' }).click();
  check('reset: type RESET (no password, no Google)', (await page.locator('[aria-label="Reset game"] input[type=password]').count()) === 0 && await page.getByRole('button', { name: 'Reset my game' }).isDisabled());
  await page.fill('#rs-word', 'reset');
  check('typing RESET unlocks the button', await page.getByRole('button', { name: 'Reset my game' }).isEnabled());
  await page.locator('[aria-label="Reset game"]').getByRole('button', { name: 'Cancel' }).last().click();
});
await step('reload keeps everything', async () => {
  await page.goto(`${BASE}/me`); await page.waitForTimeout(1800); await closePopups();
  check('every open starts on Cook', page.url().includes('/cook'), page.url());
  check('no tour or popup on later opens (first time only)', (await page.locator('.coach').count()) === 0 && (await page.locator('.popup-scrim').count()) === 0);
  check('no "Welcome back" again within 24 hours', (await page.locator('.hud-hello.on').count()) === 0);
  await nav('Me');
  check('name persisted', await page.getByRole('heading', { name: 'Chef J ✨ #1' }).waitFor({ timeout: 8000 }).then(() => true, () => false));
});
await step('free dish search', async () => {
  await nav('Cook');
  if (await page.locator('.saved-x').count()) {
    const before = await page.locator('.saved-x').count();
    await page.locator('.saved-x').first().click(); await page.locator('.toast', { hasText: 'Removed' }).waitFor({ timeout: 5000 });
    await page.waitForFunction((n) => document.querySelectorAll('.saved-x').length === n - 1, before, { timeout: 6000 }).catch(() => {});
    check('a saved recipe can be unsaved', (await page.locator('.saved-x').count()) === before - 1);
  } else check('a saved recipe can be unsaved (none saved yet)', true);
  check('no country pop-up list on the search box', (await page.locator('#o-countries, datalist').count()) === 0 && (await page.locator('#o-dish').getAttribute('list')) === null);
  await page.fill('#o-dish', 'albanian food'); await page.getByRole('button', { name: 'Search dishes' }).click();
  await page.getByText('Byrek', { exact: true }).first().waitFor({ timeout: 15000 });
  check('a country (any way you write it) lists that country\'s dishes', /Dishes from Albania/i.test(await page.locator('section[aria-live] .eyebrow').first().innerText()) && (await page.locator('.dish-row:not(.skel)').count()) >= 8);
  await page.getByRole('button', { name: 'Byrek: show ingredients and video' }).click();
  const card = page.locator('.dflip.on');
  await card.locator('.ytbtn').waitFor({ timeout: 15000 });
  check('tapping a dish flips it to have / need', (await card.locator('.chip.have').count()) >= 1 && (await card.locator('.chip.need').count()) >= 1 && /you have \d+ of \d+/i.test(await card.innerText()));
  const yt = await card.locator('a.ytbtn').getAttribute('href');
  check('YouTube button: most-watched video that is really about the dish', yt === 'https://www.youtube.com/watch?v=BIGmatch001', yt);
  check('YouTube logo on the button', (await card.locator('.ytbtn svg path[fill="#FF0000"]').count()) === 1);
  await shot('07-dish-flip');
  await card.getByRole('button', { name: /Add \d+ missing to shopping list/ }).click(); await page.getByText(/Added \d+ to your shopping list/).waitFor();
  check('missing ingredients go to the shopping list', true);
  check('"I cooked it" on the card', (await card.getByRole('button', { name: 'I cooked it' }).count()) === 1);
  await card.getByRole('button', { name: 'Flip back' }).click(); await page.waitForTimeout(600);
  await page.getByRole('button', { name: 'Fli: show ingredients and video' }).click();
  await page.locator('.dflip.on .ytbtn').waitFor({ timeout: 15000 });
  check('no video about the dish on YouTube → logo greyed out', (await page.locator('.dflip.on .ytbtn.off').count()) === 1 && (await page.locator('.dflip.on a.ytbtn').count()) === 0);
  await shot('07b-dish-noyt');
  await page.locator('.dflip.on').getByRole('button', { name: 'Flip back' }).click(); await page.waitForTimeout(500);
  // the 5th Albanian dish finishes Albania: Gold, +3,000 coins and +300 XP
  await fetch('http://localhost:54321/__e2e/seed-meals?country=AL&n=4');
  const c0 = Number((await page.locator('header .pill').nth(1).innerText()).replace(/\D/g, ''));
  await page.getByRole('button', { name: 'Byrek: show ingredients and video' }).click();
  await page.locator('.dflip.on').getByRole('button', { name: 'I cooked it' }).click();
  await page.locator('[aria-label="Log a meal"] input[type=file]').setInputFiles(photo);
  check('dish counts toward its country', /Albania on your globe/.test(await page.locator('[aria-label="Log a meal"]').innerText()));
  await page.locator('[aria-label="Log a meal"]').getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('heading', { name: 'Cooked it!' }).waitFor({ timeout: 15000 });
  await page.getByRole('button', { name: 'Leave' }).click();
  await page.getByRole('heading', { name: 'Country complete!' }).waitFor({ timeout: 8000 });
  await shot('07c-country-done');
  const c1 = Number((await page.locator('header .pill').nth(1).innerText()).replace(/\D/g, ''));
  check('5th dish from a country: Gold popup with its art, +3,000 coins (plus 500 for cooking)', /Albania is Gold/.test(await page.locator('.popup').innerText()) && (await page.locator('.popup .country-badge').count()) === 1 && c1 - c0 === 3500, `${c0} → ${c1}`);
  await page.getByRole('button', { name: 'Nice!' }).click(); await page.waitForTimeout(600);
  if (await page.getByText('Level up!', { exact: false }).count()) { await page.locator('[aria-label=Close]').first().click(); await page.waitForTimeout(400); }
  // finished countries: Gold on the tier list, painted on the globe, their kitchen things in the shop
  await fetch('http://localhost:54321/__e2e/seed-meals?country=MX&n=5');
  await nav('Compete'); await page.locator('.globe').waitFor();
  await page.locator('.globe-svg .gl-gold').nth(1).waitFor({ state: 'attached', timeout: 8000 }).catch(() => {});
  check('a Gold country is painted on the globe (its colours and food, clipped to its shape)', (await page.locator('.globe-svg .gl-gold').count()) >= 2 && (await page.locator('.globe-svg .gl-gold clipPath').count()) >= 2);
  await page.locator('.globe').scrollIntoViewIfNeeded(); await shot('07e-globe-gold');
  await nav('Me'); await page.locator('.pcard').waitFor();
  check('country challenges show up for started countries', await page.locator('.cchal').first().waitFor({ timeout: 8000 }).then(() => true, () => false));
  await page.locator('.shop [role=tab]', { hasText: 'From your countries' }).click({ timeout: 8000 });
  await page.locator('.shop-grid .tile', { hasText: 'Molcajete' }).waitFor({ timeout: 8000 });
  check('finishing Mexico unlocks its kitchen things', (await page.locator('.shop-grid .tile', { hasText: 'Tortilla press' }).count()) === 1 && (await page.locator('.shop-grid .tile', { hasText: 'Moka pot' }).count()) === 0);
  await page.locator('.shop-grid .tile', { hasText: 'Molcajete' }).click(); await page.locator('[data-tour="buy"]').click();
  check('a country thing goes into the kitchen too', await page.locator('#my-kitchen .kthing img[alt="Molcajete"]').waitFor({ timeout: 8000 }).then(() => true, () => false));
  await closePopups(); if (await page.getByText('Level up!', { exact: false }).count()) { await page.locator('.popup [aria-label=Close]').first().click(); await page.waitForTimeout(400); }
  await page.locator('#my-kitchen').scrollIntoViewIfNeeded(); await shot('07d-me-kitchen');
  await nav('Cook');
  for (const [q, want] of [['pesto', 'Pesto'], ['chickpeas', 'Falafel'], ['sauce', 'Chimichurri'], ['pho', 'Pho']]) {
    await page.fill('#o-dish', q); await page.getByRole('button', { name: 'Search dishes' }).click();
    const ok = await page.getByText(want, { exact: true }).first().waitFor({ timeout: 8000 }).then(() => true, () => false);
    check(`search anything: "${q}" finds ${want}`, ok);
  }
  await page.fill('#o-dish', 'salsa macha'); await page.getByRole('button', { name: 'Search dishes' }).click();
  await page.getByText('Salsa macha', { exact: true }).first().waitFor({ timeout: 15000 });
  check('not in Whisk\'s list → free Wikipedia search, food articles only', (await page.locator('.dish-row:not(.skel)').count()) === 1 && (await page.getByText('Macha (film)').count()) === 0);
  await page.getByRole('button', { name: 'Salsa macha: show ingredients and video' }).click();
  await page.locator('.dflip.on .ytbtn').waitFor({ timeout: 15000 });
  const chips = await page.locator('.dflip.on .chip').allInnerTexts();
  check('its ingredients come from the Wikipedia infobox', chips.some((c) => /dried chiles/i.test(c)) && chips.some((c) => /garlic/i.test(c)) && chips.some((c) => /sesame seeds/i.test(c)), JSON.stringify(chips));
  const free = await (await fetch('http://localhost:54321/__e2e/free-calls')).json();
  check('no AI used for search (costs nothing)', !free.anthropic.includes('web_search') && free.wiki >= 1 && free.youtube.length >= 1, JSON.stringify(free));
  await page.evaluate(() => window.scrollTo(0, 0));
  check('just an "Add Channel" button: no heading, no explainer text, no built-in channels', (await page.locator('.channel').count()) === 0 && (await page.getByRole('button', { name: 'Add Channel' }).count()) === 1 && (await page.getByText(/Your YouTubers|They’ll be right here/).count()) === 0 && (await page.getByText(/You Suck at Cooking|Not Another Cooking Show/).count()) === 0);
  await page.getByRole('button', { name: 'Add Channel' }).click();
  const yIn = page.getByLabel('@handle');
  check('one box titled @handle, with the @ already typed', (await yIn.inputValue()) === '@' && (await page.locator('.yt-add input').count()) === 1);
  await yIn.fill('javascript:alert(1)'); await page.getByRole('button', { name: 'Add', exact: true }).click();
  check('a non-YouTube link is refused', (await page.getByRole('alert').filter({ hasText: 'doesn’t look like a YouTube channel' }).count()) === 1 && (await page.locator('.channel').count()) === 0);
  await yIn.fill('https://m.youtube.com/@MockKitchen/videos');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  check('added channel opens inside Whisk', (await page.locator('.channel a[href^="/cook/channel?u="]', { hasText: 'Mock Kitchen' }).count()) === 1);
  await page.getByRole('button', { name: 'Add Channel' }).click(); await yIn.fill('@mockkitchen'); await page.getByRole('button', { name: 'Add', exact: true }).click();
  check('the same channel can’t be added twice', (await page.getByText('Already on your list.').count()) === 1);
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.waitForTimeout(900); await page.reload(); await page.getByRole('button', { name: 'Add Channel' }).waitFor();
  check('your channels are saved with your game', (await page.locator('.channel', { hasText: 'Mock Kitchen' }).count()) === 1);
  // the channel page: cooking videos only, then cook along
  await page.route('https://www.youtube-nocookie.com/**', (r) => r.fulfill({ body: '<body style="background:#000"></body>', contentType: 'text/html' }));
  await page.locator('.channel a', { hasText: 'Mock Kitchen' }).click(); await page.waitForURL('**/cook/channel**');
  await page.locator('.vid-card:not(.skel)').first().waitFor({ timeout: 10000 });
  const titles = await page.locator('.vid-title').allInnerTexts();
  check('channel page lists its cooking videos and leaves out the Q&A', titles.includes('Crispy Honey Garlic Chicken') && titles.includes('Weeknight Carbonara') && !titles.some((t) => /Q&A/.test(t)), JSON.stringify(titles));
  check('the Cook tab stays lit on a channel page', (await page.locator('.nav a[href="/cook"][aria-current="page"]').count()) === 1);
  await page.locator('.vid-card', { hasText: 'Honey Garlic' }).click();
  const src = await page.locator('.vc-player iframe').getAttribute('src');
  check('video plays in Whisk from where the cooking starts (0:45) and stops before the taste test', /^https:\/\/www\.youtube-nocookie\.com\/embed\/RECIPEvid01\?/.test(src) && /start=45/.test(src) && /end=425/.test(src), src);
  check('steps one at a time from the description', /Step 1 of 3/.test(await page.locator('.vc-count').innerText()) && /Pat the chicken dry/.test(await page.locator('.vc-text').innerText()));
  await page.getByRole('button', { name: 'Next' }).click();
  check('big Next moves to the next step', /Step 2 of 3/.test(await page.locator('.vc-count').innerText()));
  await page.getByRole('button', { name: /Ingredients \(4\)/ }).click();
  check('ingredients from the description, grouped', /For the sauce/i.test(await page.locator('.vc-ing').innerText()) && /½ cup honey/.test(await page.locator('.vc-ing').innerText()));
  check('full written recipe links to the YouTuber’s site, not social media', (await page.locator('a', { hasText: 'Full written recipe' }).getAttribute('href')) === 'https://mockkitchen.example/recipes/honey-chicken');
  await shot('05b-cook-along');
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('.vid-card', { hasText: 'Carbonara' }).click();
  check('no written recipe: the steps are the video’s cooking chapters (intro and thanks left out)', /Step 1 of 3 · 1:12/.test(await page.locator('.vc-count').innerText()) && /Boiling the pasta/.test(await page.locator('.vc-text').innerText()));
  await page.getByRole('button', { name: 'Close' }).click();
  await page.goto(`${BASE}/cook`); await page.getByRole('button', { name: 'Add Channel' }).waitFor();
  await page.getByRole('button', { name: 'Remove Mock Kitchen' }).click();
  check('remove a channel', (await page.locator('.channel').count()) === 0);
});
await step('cook off with a friend', async () => {
  const pill = async (pg) => Number((await pg.locator('header .pill').last().innerText()).replace(/\D/g, ''));
  // your invite code (Get coins → Invite a friend)
  await nav('Me'); await page.waitForURL('**/me'); await page.getByRole('button', { name: /Get coins/ }).first().click();
  await page.locator('.invite-code b').waitFor();
  const myCode = (await page.locator('.invite-code b').innerText()).trim();
  check('Get coins has Invite a friend with your 6-letter code (1,000 each)', /^[A-Z2-9]{6}$/.test(myCode) && /1,000 each/.test(await page.locator('.invite').innerText()));
  await shot('06a-invite');
  await page.locator('[role=dialog][aria-label="Get coins"] button[aria-label="Close"]').click();
  // a friend starts Whisk from the invite link on their own phone
  const ctx2 = await browser.newContext({ viewport: { width: 390, height: 844 }, timezoneId: 'America/New_York' });
  const fr = await ctx2.newPage();
  await fr.goto(`${BASE}/login?ref=${myCode}`); await fr.getByRole('radio', { name: 'Accept' }).click(); await fr.getByRole('button', { name: 'Start playing' }).click();
  await fr.waitForURL('**/cook'); const invToast = await fr.locator('.toast', { hasText: /Invited by/ }).waitFor({ timeout: 10000 }).then(() => fr.locator('.toast').innerText(), () => '');
  check('the friend’s game picks up the invite from the link', /Invited by (?!a friend)/.test(invToast), invToast);
  // host makes a game
  const c0 = await pill(page);
  await nav('Compete'); await page.waitForURL('**/compete');
  check('Compete is tidy: one Friends card, no Cook Off controls on it', (await page.locator('main .co-card').count()) === 0 && (await page.locator('.fr-card').count()) === 1);
  await page.locator('.fr-card').click(); await page.waitForURL('**/compete/friends'); await page.locator('.co-card').waitFor();
  check('inside Friends: Cook Off starts as two buttons', (await page.getByRole('button', { name: 'New game' }).count()) === 1 && (await page.getByRole('button', { name: 'Join a game' }).count()) === 1 && (await page.locator('.co-times').count()) === 0);
  await page.getByRole('button', { name: 'New game' }).click();
  check('New game: pick the time, then make it', (await page.locator('.co-times [role=radio]').count()) === 4 && (await page.getByRole('button', { name: /Make a \d+-minute game/ }).count()) === 1);
  await page.locator('.co-times [role=radio]', { hasText: '30 min' }).click();
  await page.getByRole('button', { name: 'Make a 30-minute game' }).click(); await page.waitForURL('**/compete/cookoff?code=*');
  const code = new URL(page.url()).searchParams.get('code');
  await page.locator('.co-code b').waitFor();
  check('the lobby shows the code big, and you (host)', (await page.locator('.co-code b').innerText()) === code && /\(you\)/.test(await page.locator('.co-chip.me').innerText()) && (await page.locator('.co-chip.me svg').count()) === 1);
  // friend joins with the code
  await fr.getByRole('navigation').getByRole('link', { name: 'Compete', exact: true }).click(); await fr.waitForURL('**/compete');
  await fr.locator('.fr-card').click(); await fr.waitForURL('**/compete/friends'); await fr.getByRole('button', { name: 'Join a game' }).click();
  await fr.getByPlaceholder('Game code').fill(code.toLowerCase()); await fr.getByRole('button', { name: 'Join', exact: true }).click();
  await fr.waitForURL('**/compete/cookoff?code=*'); await fr.getByText('Waiting for the host to start…').waitFor();
  await page.locator('.co-chip', { hasText: /^Cook 2/ }).waitFor({ timeout: 6000 });
  check('a friend joins with the code; both screens list both cooks', (await page.locator('.co-chip').count()) === 2 && (await fr.locator('.co-chip').count()) === 2);
  await shot('06b-lobby');
  check('only the host has Start', (await fr.getByRole('button', { name: 'Start the Cook Off' }).count()) === 0);
  // a judge: someone new opens the "Invite judges" link, starts Whisk, lands in the game just to vote
  check('the lobby has "Invite judges to vote"', (await page.getByRole('button', { name: 'Invite judges to vote' }).count()) === 1);
  const ctx3 = await browser.newContext({ viewport: { width: 390, height: 844 }, timezoneId: 'America/New_York' });
  const jd = await ctx3.newPage();
  await jd.goto(`${BASE}/vote/${code}`); await jd.waitForURL('**/login?vote=*');
  check('a judge link sends someone new to the start screen with an invite note', /invited to judge a Cook Off/.test(await jd.locator('.judge-note').innerText()));
  await jd.getByRole('radio', { name: 'Accept' }).click(); await jd.getByRole('button', { name: 'Start playing' }).click();
  await jd.waitForURL('**/compete/cookoff?code=*&as=judge'); await jd.getByText('You’re a judge.', { exact: false }).waitFor({ timeout: 10000 });
  await page.locator('.co-chip.judge').waitFor({ timeout: 6000 });
  check('…and joins as a judge (no pantry needed); the host sees them under Judges', (await page.locator('.co-chip.judge').count()) === 1 && (await jd.getByRole('button', { name: 'Start the Cook Off' }).count()) === 0);
  await page.getByRole('button', { name: 'Start the Cook Off' }).click();
  await page.locator('.co-full .bw').waitFor({ timeout: 8000 });
  await fr.locator('.co-full .bw').waitFor({ timeout: 8000 });
  check('start: both phones go full screen and spin the wheel', (await page.locator('.nav').isVisible()) === true && (await page.locator('.co-full').evaluate((e) => getComputedStyle(e).position === 'fixed' && e.getBoundingClientRect().height >= innerHeight - 1)));
  await page.waitForTimeout(1500); await shot('06c-wheel');
  const blur = await page.locator('#bw-blur feGaussianBlur').getAttribute('stdDeviation');
  check('arcade drum: wooden planks with recipes roll between two arrows, motion-blurred up and down while fast', (await page.locator('.bw-plank').count()) === 24 && (await page.locator('.bw-arrow').count()) === 2 && /^0 (?!0(\.00)?$)/.test(blur), blur);
  await page.locator('.co-timer').waitFor({ timeout: 15000 }); await fr.locator('.co-timer').waitFor({ timeout: 15000 });
  const t1 = await page.locator('.co-timer').innerText(), t2 = await fr.locator('.co-timer').innerText();
  const secs = (t) => { const [m, s] = t.replace(/[^\d:]/g, '').split(':').map(Number); return m * 60 + s; };
  check('then your recipe with ingredients, steps and one shared clock', Math.abs(secs(t1) - secs(t2)) <= 2 && secs(t1) > 25 * 60 && secs(t1) <= 30 * 60 && (await page.locator('.co-cook .ing-list li').count()) > 2 && (await page.locator('.co-cook ol.steps li').count()) > 2, `${t1} / ${t2}`);
  check('a drawn postcard of that dish and where it’s from is behind it', (await page.locator('.co-cook .scene svg').count()) === 1 && (await page.locator('.co-cook .scene svg image').count()) === 0);
  await shot('06d-cook');
  for (const pg of [page, fr]) await pg.locator('.co-snap input[type=file]').setInputFiles('e2e/plate.jpg');
  await page.locator('.co-plates').waitFor({ timeout: 15000 }); await fr.locator('.co-plates').waitFor({ timeout: 15000 });
  await jd.locator('.co-plates').waitFor({ timeout: 15000 });
  check('both plates in → voting starts on every phone, judges included', /Vote for the best plate/.test(await page.locator('.co-big').innerText()) && (await page.locator('.co-plate img').count()) === 2 && /Judge: pick the best plate/.test(await jd.locator('.co-big').innerText()));
  check('you can’t vote for your own plate', await page.locator('.co-plate', { hasText: '(you)' }).isDisabled());
  await shot('06e-vote');
  check('voting is pick, then Submit', (await page.getByRole('button', { name: 'Tap a plate to pick it' }).isDisabled()));
  for (const pg of [page, fr]) { await pg.locator('.co-plate:not([disabled])').click(); await pg.getByRole('button', { name: 'Submit vote' }).click(); }
  await jd.locator('.co-plate', { hasText: /\(you\)/ }).count();
  const hostName = (await page.locator('.co-plate', { hasText: '(you)' }).locator('b').innerText()).replace(' (you)', '');
  await jd.locator('.co-plate', { hasText: hostName }).click(); await jd.getByRole('button', { name: 'Submit vote' }).click();
  await jd.waitForURL('**/cook', { timeout: 8000 });
  check('after the judge submits, Whisk takes them to the start of the app', jd.url().endsWith('/cook'));
  await page.getByText(/It’s a tie!|wins!/).waitFor({ timeout: 10000 });
  check('everyone voted → winner screen (the judge broke the tie)', /wins!/.test(await page.locator('.co-big').innerText()));
  check('your coins: +1,000 for the win', /\+1,000 coins/.test(await page.locator('.co-reward').innerText()));
  await shot('06f-winner');
  await page.getByRole('link', { name: 'Back to Compete' }).click(); await page.waitForURL('**/compete');
  await page.waitForTimeout(800);
  const c1 = await pill(page);
  check('coins: win (+1,000) + invite reward (+1,000)', c1 - c0 === 2000, `${c0} → ${c1}`);
  await ctx2.close(); await ctx3.close();
});
await step('activity backend', async () => {
  await page.waitForTimeout(4500); await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
  const ev = await (await fetch('http://localhost:54321/__e2e/events')).json();
  check('taps, picks and searches are recorded', ev.some((e) => e.kind === 'tap') && ev.some((e) => e.kind === 'search' && e.value === 'albanian food') && ev.some((e) => e.kind === 'view'), `${ev.length} events`);
  check('typed text in other fields is not recorded', !ev.some((e) => /Frozen pork chops|Chef J/.test(e.value || '')));
  await page.goto(`${BASE}/admin`); await page.waitForTimeout(1500);
  check('backend page is closed to non-admins', await page.getByText('This page is only for Whisk admins.').isVisible());
  await fetch('http://localhost:54321/__e2e/make-admin');
  await page.reload(); await page.getByRole('heading', { name: 'Backend' }).waitFor({ timeout: 8000 });
  check('admins see the backend dashboard', (await page.locator('.adm-tiles .adm-card').count()) === 5);
  check('dashboard lists top searches and the activity feed', (await page.getByRole('cell', { name: 'albanian food' }).count()) >= 1 && (await page.locator('.adm td').count()) > 10);
  await shot('08-backend');
});
await step('never show me, vacation, streak repair note', async () => {
  await page.goto(`${BASE}/cook`); await page.waitForTimeout(1200); await closePopups();
  await page.click('text=What can I make?'); await page.getByText(/recipes? you can make right now/).waitFor();
  const n0 = parseInt(await page.getByText(/recipes? you can make right now/).innerText(), 10);
  await nav('Me'); await page.getByRole('button', { name: /Never show me/ }).click();
  const ns = page.locator('[role=dialog][aria-label="Never show me"]');
  check('Never show me: one-tap allergies + any ingredient, and a check-the-label note', (await ns.locator('.never-pick .chip').count()) === 9 && (await ns.getByText(/always check the label/).count()) === 1);
  await ns.getByRole('button', { name: 'Eggs' }).click();
  await ns.locator('#never-w').fill('Cilantro'); await ns.getByRole('button', { name: 'Add ingredient' }).click();
  await ns.getByRole('button', { name: 'Save' }).click(); await page.waitForTimeout(600);
  check('saved: the row says how many are hidden', /2 hidden/.test(await page.getByRole('button', { name: /Never show me/ }).innerText()));
  await nav('Cook'); await page.click('text=What can I make?'); await page.getByText(/recipes? you can make right now/).waitFor();
  const n1 = parseInt(await page.getByText(/recipes? you can make right now/).innerText(), 10);
  await page.locator('main button.card:has(.chip.have)').first().click(); await page.getByText('Recipe from').waitFor();
  const ingText = (await page.locator('[role=dialog] .ing-list').innerText()).toLowerCase();
  check('recipes with eggs or cilantro are gone from Cook', n1 < n0 && !/\begg|cilantro/.test(ingText), `${n0} → ${n1}`);
  await page.locator('[role=dialog] [aria-label="Close"]').first().click();
  await nav('Me'); await page.getByRole('button', { name: /Never show me/ }).click();
  await ns.getByRole('button', { name: 'Eggs' }).click(); await ns.getByRole('button', { name: 'Show cilantro again' }).click(); await ns.getByRole('button', { name: 'Save' }).click(); await page.waitForTimeout(500);
  check('clearing it shows everything again', /Allergies, dislikes/.test(await page.getByRole('button', { name: /Never show me/ }).innerText()));
  await page.getByRole('switch', { name: 'Vacation mode' }).click(); await page.waitForTimeout(600);
  check('vacation mode on: the streak pill shows a plane', (await page.getByRole('switch', { name: 'Vacation mode' }).getAttribute('aria-checked')) === 'true' && /paused/.test(await page.locator('header .pill[data-tip=streak]').getAttribute('title')));
  await page.getByRole('switch', { name: 'Vacation mode' }).click(); await page.waitForTimeout(600);
  check('vacation mode off again', (await page.getByRole('switch', { name: 'Vacation mode' }).getAttribute('aria-checked')) === 'false');
  check('streak repair is explained', (await page.getByText(/Cook twice the next day and your streak comes back/).count()) === 1);
});
await step('share the shopping list', async () => {
  await nav('Pantry'); await page.getByRole('tab', { name: /Shopping list/ }).click();
  await page.locator('#s-new').fill('Basil'); await page.locator('#s-new').press('Enter'); await page.waitForTimeout(500);
  await page.getByRole('button', { name: /Share list/ }).click();
  const link = page.getByLabel('Share link'); await page.waitForFunction(() => /\/list\/[a-f0-9]{32}$/.test(document.querySelector('[aria-label="Share link"]')?.value || ''));
  const url = await link.inputValue();
  check('Share list makes a secret link', /\/list\/[a-f0-9]{32}$/.test(url));
  await page.getByRole('dialog', { name: 'Share your list' }).getByRole('button', { name: 'Close' }).click();
  const ctx4 = await browser.newContext({ viewport: { width: 390, height: 844 } }); const sh = await ctx4.newPage();
  const resp = await sh.goto(url);
  check('the link opens with no account, is never cached, and leaks no referrer', /no-store/.test(resp.headers()['cache-control'] || '') && resp.headers()['referrer-policy'] === 'no-referrer');
  await sh.locator('.sl-item', { hasText: 'Basil' }).waitFor();
  check('the shared page shows the list by aisle', (await sh.locator('.sl-item').count()) >= 1 && (await sh.locator('.eyebrow', { hasText: 'Produce' }).count()) === 1);
  await sh.locator('.sl-item', { hasText: 'Basil' }).click(); await sh.waitForTimeout(600);
  check('anyone with the link can tick an item', (await sh.locator('.sl-item.done', { hasText: 'Basil' }).count()) === 1);
  await sh.screenshot({ path: SHOTS ? path.join(SHOTS, '09-shared-list.png') : '/dev/null' }).catch(() => {});
  await page.reload(); await page.waitForTimeout(1200); await closePopups(); await nav('Pantry'); await page.getByRole('tab', { name: /Shopping list/ }).click();
  await page.locator('.card.ticked', { hasText: 'Basil' }).waitFor({ timeout: 6000 });
  check('…and the tick shows on the owner’s list', true);
  await page.getByRole('button', { name: /Share list/ }).click(); await page.getByRole('button', { name: 'Turn the link off' }).click(); await page.waitForTimeout(500);
  await sh.reload(); await sh.getByText('This link is off').waitFor({ timeout: 6000 });
  check('turning the link off stops it working', true);
  await ctx4.close();
});
await step('friends and the plate feed', async () => {
  const toFriends = async (pg) => { await pg.getByRole('navigation').getByRole('link', { name: 'Compete', exact: true }).click(); await pg.waitForURL('**/compete'); await pg.locator('.fr-card').click(); await pg.waitForURL('**/compete/friends'); };
  const reopen = async (pg) => { await pg.reload(); await pg.waitForURL('**/cook'); await pg.waitForTimeout(800); await pg.keyboard.press('Escape'); await toFriends(pg); };
  await toFriends(page);
  await page.locator('.fr-code').filter({ hasText: /^[A-Z2-9]{6}$/ }).waitFor();
  const myCode = await page.locator('.fr-code').innerText();
  check('Friends shows your 6-letter code', /^[A-HJ-NP-Z2-9]{6}$/.test(myCode), myCode);
  check('no Share button: tap the code to copy it; no text in the add box', (await page.getByRole('button', { name: /^Share$/ }).count()) === 0 && (await page.locator('button.fr-copy').count()) === 1 && !(await page.locator('#fr-code').getAttribute('placeholder')));
  check('"Add a friend to see what they cook." sits under Plates; Cook Off has the new line', (await page.getByText('Add a friend to see what they cook.').count()) === 1 && (await page.getByText('Yours stay private').count()) === 0 && (await page.getByText('The clock is ticking. The competition is heating up. And one winning dish.').count()) === 1);
  const ctx6 = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 }); const fp = await ctx6.newPage();
  await fp.goto(`${BASE}/login`); await fp.getByRole('radio', { name: 'Accept' }).click(); await fp.getByRole('button', { name: 'Start playing' }).click(); await fp.waitForURL('**/cook');
  await fp.waitForTimeout(1200); await fp.mouse.click(5, 400);
  await fp.getByRole('navigation').getByRole('link', { name: 'Compete', exact: true }).click(); await fp.waitForURL('**/compete');
  await fp.locator('.fr-card').click(); await fp.waitForURL('**/compete/friends');
  await fp.getByText('No plates yet').waitFor({ timeout: 8000 });
  check('a new player’s feed starts empty', true);
  await fp.locator('#fr-code').fill(myCode); await fp.getByRole('button', { name: 'Add', exact: true }).click();
  await fp.locator('.toast', { hasText: 'Request sent' }).waitFor();
  check('adding a code sends a friend request', true);
  await reopen(page); await page.locator('.fr-req', { hasText: 'wants to be friends' }).waitFor({ timeout: 8000 });
  check('the other player sees the request', true);
  await page.locator('.fr-req', { hasText: 'wants to be friends' }).getByRole('button', { name: 'Yes' }).click();
  await page.locator('.toast', { hasText: 'are friends' }).waitFor();
  await page.locator('article.post').first().waitFor({ timeout: 8000 });
  const mine = await page.locator('article.post').count();
  check('your own shared plate shows in your feed (only the shared one)', mine === 1 && (await page.locator('article.post .who b').first().innerText()) === 'You');
  await reopen(fp); await fp.locator('article.post').first().waitFor({ timeout: 8000 });
  await fp.waitForFunction(() => !!document.querySelector('article.post img.post-img')?.src, null, { timeout: 8000 });
  const imgOk = (await fp.request.get(await fp.locator('article.post img.post-img').getAttribute('src'))).ok();
  check('the friend can open the photo', imgOk);
  check('your friend sees it, photo and all (and nothing you didn’t share)', (await fp.locator('article.post').count()) === 1);
  await fp.locator('article.post .love').first().click(); await fp.waitForTimeout(600);
  check('love: the heart fills and counts 1', (await fp.locator('article.post .love.on').count()) === 1 && (await fp.locator('article.post .love').first().innerText()).trim() === '1');
  await fp.screenshot({ path: SHOTS ? path.join(SHOTS, '10-friends-feed.png') : '/dev/null' }).catch(() => {});
  await reopen(page); await page.locator('article.post .love').first().waitFor();
  check('the owner sees the love', (await page.locator('article.post .love').first().innerText()).trim() === '1');
  await fp.getByRole('button', { name: 'More' }).first().click(); await fp.getByRole('button', { name: 'Report this plate' }).click();
  await fp.getByRole('button', { name: 'It’s not food' }).click();
  await fp.locator('.toast', { hasText: 'won’t see that plate' }).waitFor();
  check('report: it disappears for the reporter right away', (await fp.locator('article.post').count()) === 0);
  await reopen(page); await page.locator('article.post').first().waitFor();
  check('one report doesn’t hide it for others', (await page.locator('article.post').count()) === 1);
  await ctx6.close();
});
await step('back up your game', async () => {
  await nav('Me'); await page.waitForURL('**/me');
  check('an unsaved game says so and offers a backup', (await page.getByText('Your game is saved on this phone').count()) === 1);
  await page.getByRole('button', { name: 'Back up your game' }).click();
  const bk = page.getByRole('dialog', { name: 'Back up your game' });
  await bk.getByRole('button', { name: 'Continue with Google' }).waitFor();
  check('only the switched-on ways show (Google + email here, no Apple)', (await bk.getByRole('button', { name: 'Continue with Apple' }).count()) === 0 && (await bk.locator('#bk-email').count()) === 1);
  await bk.locator('#bk-email').fill('chef@example.com'); await bk.getByRole('button', { name: 'Email me a link' }).click();
  await bk.getByText('Check your email').waitFor();
  const bks = await (await fetch('http://localhost:54321/__e2e/backups')).json();
  check('back up by email: the game gets that email (a confirm link is sent)', bks.backups.some((b) => b.email === 'chef@example.com'));
  await bk.getByRole('button', { name: 'OK' }).click();
  await fetch('http://localhost:54321/__e2e/play-days?n=3');
  await page.reload(); await page.waitForURL('**/cook'); await page.waitForTimeout(1000); await closePopups();
  await page.locator('.backup-nudge').waitFor({ timeout: 6000 });
  check('from day 3, Cook shows a small Back up card', true);
  await page.locator('.backup-nudge').getByRole('button', { name: 'Later' }).click(); await page.waitForTimeout(300);
  check('Later hides it', (await page.locator('.backup-nudge').count()) === 0);
});
await step('get my game back', async () => {
  const ctx7 = await browser.newContext({ viewport: { width: 390, height: 844 } }); const rp = await ctx7.newPage();
  await rp.goto(`${BASE}/login`);
  await rp.getByRole('button', { name: /Get it back/ }).click();
  const gb = rp.getByRole('dialog', { name: 'Get my game back' });
  await gb.locator('#bk-email').fill('chef@example.com'); await gb.getByRole('button', { name: 'Email me a link' }).click();
  await gb.getByText('Check your email').waitFor();
  check('on a new phone: get a backed-up game back by email (no new game made)', (await (await fetch('http://localhost:54321/__e2e/backups')).json()).otps.includes('chef@example.com'));
  await ctx7.close();
});
await step('notifications', async () => {
  await nav('Me'); await page.waitForURL('**/me');
  check('Me has Notifications (off until you turn it on), with only-useful wording', (await page.getByRole('switch', { name: 'Notifications' }).getAttribute('aria-checked')) === 'false' && (await page.getByText(/Only useful ones/).count()) === 1);
  const bad = await page.request.post(`${BASE}/api/push/due`, { headers: { Authorization: 'Bearer wrong' } });
  check('the hourly sender refuses without the secret', bad.status() === 401);
  const ok = await page.request.post(`${BASE}/api/push/due`, { headers: { Authorization: 'Bearer e2e-push-secret-0123456789abcdef' } });
  check('…and runs with it', ok.status() === 200 && (await ok.json()).ok === true);
  const co = await page.request.post(`${BASE}/api/push/cookoff`, { data: { code: 'ABCDEF' } });
  check('the Cook Off push only works for your own new game (quietly does nothing otherwise)', co.status() === 200 && (await co.json()).sent === 0);
});
await step('kitchen layout', async () => {
  await fetch('http://localhost:54321/__e2e/clear-kitchens');   // the shop made one earlier; this walk starts from none
  await page.reload(); await page.waitForTimeout(1500); await closePopups();
  await nav('Pantry'); await page.getByRole('tab', { name: /^Pantry \(/ }).click();
  await page.locator('button.chip', { hasText: /^All$/ }).click();
  await page.locator('a.kf-empty').click(); await page.waitForURL('**/pantry/kitchen/design');
  await page.locator('.kbox').first().waitFor();
  check('Layout kitchen opens the designer with a starter kitchen to play with', (await page.locator('.kbox').count()) === 9);
  await page.locator('.grid2 button', { hasText: 'Add' }).click();
  await page.locator('.kd-search input').fill('c');
  check('search guesses what you mean after one letter', (await page.locator('.kd-ghost').innerText()).includes('abinet with 3 sliding drawers'));
  await page.locator('.kd-search input').fill('deep freeze');
  check('…and understands everyday words (“deep freeze” → chest freezer)', /Chest freezer/.test(await page.locator('.kd-res').first().innerText()));
  await page.locator('.kd-res').first().click();
  check('adding a piece drops it on the floor, picked up', (await page.locator('.kbox').count()) === 10 && (await page.locator('.kbox.sel').count()) === 1);
  check('a picked piece shows plain dots to stretch it (left, right, taller, and deeper from the sides), no arrows', (await page.locator('.kbox.sel .kknob:not(.side)').count()) === 3 && (await page.locator('.kbox.sel .kknob.side').count()) === 2 && (await page.locator('.kbox.sel .kknob svg').count()) === 0);
  const topOf = () => page.locator('.kbox.sel').evaluate((el) => `${el.style.top}|${el.style.transform}`);
  const before = await topOf();
  await page.getByRole('button', { name: /Bring it toward you|Push it back/ }).click();
  check('one small button moves it toward you (or back)', (await topOf()) !== before);
  const sb = await page.locator('.kbox.sel').boundingBox();
  const hit = await page.evaluate(([x, y]) => !!document.elementFromPoint(x, y)?.closest('.kbox.sel'), [sb.x + sb.width / 2, sb.y + sb.height / 2]);
  if (hit) {
    const z0 = await topOf();
    await page.mouse.move(sb.x + sb.width / 2, sb.y + sb.height / 2); await page.mouse.down(); await page.mouse.move(sb.x + sb.width / 2, sb.y + sb.height / 2 - 90, { steps: 8 }); await page.mouse.up();
    check('drag a piece up and it lifts up', (await topOf()).split('|')[1] !== z0.split('|')[1], await topOf());
    const sb2 = await page.locator('.kbox.sel').boundingBox();
    await page.mouse.move(sb2.x + sb2.width / 2, sb2.y + sb2.height / 2); await page.mouse.down(); await page.mouse.move(sb2.x + sb2.width / 2, sb2.y + sb2.height / 2 + 200, { steps: 8 }); await page.mouse.up();
    check('…and drag it down to set it back on the floor', /translateZ\(0px\)/.test(await topOf()), await topOf());
  }
  const camT = () => page.locator('.kd-stage .k3-cam').evaluate((el) => el.style.transform);
  const c0 = await camT();
  const st = await page.locator('.kd-stage .k3').boundingBox();
  await page.mouse.move(st.x + st.width / 2, st.y + st.height / 2); await page.mouse.wheel(0, -500); await page.waitForTimeout(200);
  const sc = (t) => Number(t.match(/scale\(([\d.]+)\)/)[1]);
  check('scroll (or pinch) zooms in', sc(await camT()) > sc(c0) * 1.3, `${c0} → ${await camT()}`);
  await page.getByRole('button', { name: 'Zoom out' }).click();
  check('…and the − button zooms out', sc(await camT()) < sc(await camT()) + 1);
  const rz = (t) => Number(t.match(/rotateZ\((-?[\d.]+)deg\)/)[1]);
  const r0 = rz(await camT());
  await page.mouse.move(st.x + 30, st.y + 60); await page.mouse.down(); await page.mouse.move(st.x + 150, st.y + 60, { steps: 6 }); await page.mouse.up();
  check('swipe right → the kitchen turns right with your finger', rz(await camT()) < r0, `${r0} → ${rz(await camT())}`);
  await page.locator('.kd-tools').getByRole('button', { name: 'Paint' }).click();
  const tex = await page.locator('.kd-tex').allInnerTexts();
  check('a freezer can’t be marble: steel, matte, gloss (and Copper from the shop, locked until bought)', tex.join('|') === 'Brushed steel|Matte|Gloss|Copper' && (await page.locator('.kd-tex.locked', { hasText: 'Copper' }).count()) === 1, tex.join('|'));
  await page.locator('.kd-tex', { hasText: 'Gloss' }).click(); await page.locator('.kd-sw[aria-label=Red]').click();
  await page.locator('.kd-sheet').getByRole('button', { name: 'Done' }).click();
  await page.locator('.kd-actions').getByRole('button', { name: 'Save' }).click(); await page.locator('.kd-actions').getByRole('button', { name: 'Saved' }).waitFor();
  check('the first kitchen you save goes on display', (await page.getByRole('button', { name: 'On display in your Pantry' }).count()) === 1);
  await page.locator('.kd-actions').getByRole('button', { name: 'New' }).click(); await page.locator('.kd-new', { hasText: 'Dream kitchen' }).click();
  check('Dream kitchen doesn’t jump straight into the search', (await page.locator('.kd-add').count()) === 0);
  await page.locator('.grid2 button', { hasText: 'Add' }).click();
  await page.locator('.kd-res', { hasText: 'Retro fridge' }).click();
  await page.locator('.kd-actions').getByRole('button', { name: 'Save' }).click(); await page.locator('.kd-actions').getByRole('button', { name: 'Saved' }).waitFor();
  check('a new kitchen saves without changing the one on display', (await page.getByRole('button', { name: 'Put on display in your Pantry' }).count()) === 1);
  await page.locator('.kd-name').click();
  check('My kitchens lists both; one is showing', (await page.locator('.kd-mine').count()) === 2 && (await page.locator('.kd-mine .chip.have').count()) === 1);
  await page.locator('.kd-mine', { hasText: 'My kitchen' }).locator('.kd-mine-main').click();
  await page.locator('.title-link', { hasText: 'Pantry' }).click(); await page.waitForURL(/\/pantry$/);
  await page.locator('.kfloat .kbox').first().waitFor();
  check('Pantry: your kitchen floats between the categories and the list', (await page.locator('.kfloat .kbox').count()) === 10);
  const todo = Number((await page.locator('.kf-go').innerText()).match(/\d+/)[0]);
  await page.locator('.kf-go').click(); await page.waitForURL('**/pantry/kitchen');
  await page.locator('.pa-box').first().waitFor();
  check('Put it away: every unplaced food is a box in the tray', (await page.locator('.pa-box').count()) === todo, `${todo}`);
  const meat = page.locator('.pa-box', { has: page.locator('.pa-emoji', { hasText: '🍗' }) }).first();
  const hadMeat = (await meat.count()) > 0;
  const pick = hadMeat ? meat : page.locator('.pa-box').first();
  const pickName = (await pick.locator('.pa-name').innerText()).trim();
  await pick.click(); await page.waitForTimeout(800);
  check('tap a food box → every door and drawer opens with lit spots', (await page.locator('[data-spot]').count()) > 20);
  const visibleSpot = (skip = 0) => page.evaluate((skip) => { let n = 0; for (const el of document.querySelectorAll('[data-spot]')) { const r = el.getBoundingClientRect(); if (r.width < 8 || r.height < 6) continue; const hit = document.elementFromPoint(r.left + r.width / 2, r.top + r.height / 2); if (hit === el && r.top > 80) { if (n++ === skip) return { x: r.left + r.width / 2, y: r.top + r.height / 2, k: el.dataset.spot }; } } return null; }, skip);
  const v1 = await visibleSpot(0); await page.mouse.click(v1.x, v1.y);
  await page.locator('.pa-pop').first().waitFor();
  check('drop it on a spot → +3 XP and one fewer to put away', /\+3 XP/.test(await page.locator('.pa-pop').first().innerText()) && (await page.locator('.pa-box').count()) === todo - 1);
  // drag one in too (hold and move)
  await page.evaluate(() => { document.querySelector('.putaway .k3').scrollIntoView({ block: 'start' }); document.querySelector('.pa-tray').scrollLeft = 0; }); await page.waitForTimeout(400);
  const b2 = await page.locator('.pa-box').first().boundingBox();
  await page.mouse.move(b2.x + 40, b2.y + 40); await page.mouse.down(); await page.mouse.move(b2.x + 40, b2.y - 80, { steps: 5 });
  await page.locator('.pa-ghost').waitFor(); await page.waitForTimeout(700);
  const t = await visibleSpot(3);
  await page.mouse.move(t.x, t.y, { steps: 6 }); await page.mouse.up();
  await page.waitForTimeout(600);
  check('…or hold a box and drag it into the kitchen', (await page.locator('.pa-box').count()) === todo - 2);
  await page.locator('.title-link', { hasText: 'Pantry' }).click(); await page.waitForURL(/\/pantry$/);
  if (hadMeat) {
    await page.locator('button.chip', { hasText: /^Proteins$/ }).click(); await page.waitForTimeout(500);
    check('pick Proteins → the spots holding them open and light up, with the food’s sticker', (await page.locator('.kfloat .ks.lit').count()) >= 1 && (await page.locator(`.kfloat .kstks img[title="${pickName}"]`).count()) >= 1, pickName);
    await page.locator('button.chip', { hasText: /^All$/ }).click();
  } else check('(no proteins in this pantry to light up)', true);
  await page.getByRole('tab', { name: 'Kitchen' }).click();
  await page.locator('main .kdoor[role=button]').first().click();
  await page.waitForTimeout(700); const v3 = await visibleSpot(0); check('Kitchen tab: an open door shows tappable spots', !!v3); if (v3) await page.mouse.click(v3.x, v3.y);
  check('Kitchen tab: open a door, tap a spot, see what’s there', /Fridge|Pantry|Cabinet/.test(await page.locator('main .card b').last().innerText()));
  check('fridge doors have shelves on the inside you can put food on', (await page.locator('main .ks.bin').count()) >= 1);
  const kcam = () => page.locator('main .k3-cam').evaluate((el) => el.style.transform);
  const kb = await page.locator('main .k3').boundingBox();
  await page.mouse.move(kb.x + kb.width / 2, kb.y + kb.height / 2);
  await page.getByRole('button', { name: 'Back' }).click(); await page.waitForTimeout(900);
  await page.locator('main .k3').scrollIntoViewIfNeeded(); const kb2 = await page.locator('main .k3').boundingBox(); await page.mouse.move(kb2.x + kb2.width / 2, kb2.y + kb2.height / 2);
  const t0 = await kcam(); await page.mouse.wheel(150, 0); await page.waitForTimeout(900);
  const t1 = await kcam(), scl = (t) => t.match(/scale\(([\d.]+)\)/)[1], trl = (t) => t.match(/translate\([^)]*\)/)[0], rxl = (t) => t.match(/rotateX\(([-\d.]+)deg\)/)[1];
  check('scrolling sideways turns the kitchen smoothly', t1 !== t0, `${t0} → ${t1}`);
  check('…but never zooms, slides or tilts (locked to the best angle)', scl(t1) === scl(t0) && trl(t1) === trl(t0) && rxl(t1) === rxl(t0), `${t0} → ${t1}`);
  const kbefore = await kcam(); await page.mouse.move(kb2.x + kb2.width / 2, kb2.y + kb2.height / 2); await page.mouse.down(); await page.mouse.move(kb2.x + kb2.width / 2 + 90, kb2.y + kb2.height / 2 + 60, { steps: 8 }); await page.mouse.up(); await page.waitForTimeout(1200);
  check('dragging turns it left/right only', (await kcam()) !== kbefore && rxl(await kcam()) === rxl(kbefore) && scl(await kcam()) === scl(kbefore));
  // a walk-in pantry closet you can put anywhere off the kitchen: shelves on 3 walls and the floor; tap it to fly to it
  await page.locator('main a.btn', { hasText: 'Design' }).click(); await page.waitForURL('**/pantry/kitchen/design');
  await page.getByRole('button', { name: 'Pantry closet' }).click();
  check('Pantry closet sits off the kitchen with shelves on 3 walls + the floor', (await page.locator('.kd-stage .kcloset').count()) === 1 && (await page.locator('.kd-stage .kcloset .kc-wall').count()) === 3);
  await page.getByRole('button', { name: 'Done with this piece' }).click();
  await page.getByRole('button', { name: 'Spice cabinet' }).click();
  await page.getByRole('button', { name: 'Done with this piece' }).click();
  await page.locator('.kd-actions').getByRole('button', { name: 'Save' }).click(); await page.locator('.kd-actions').getByRole('button', { name: 'Saved' }).waitFor();
  await page.locator('.title-link', { hasText: 'Pantry' }).click(); await page.waitForURL(/\/pantry$/);
  await page.getByRole('tab', { name: 'Kitchen' }).click(); await page.locator('main .kcloset').waitFor();
  check('the closet’s shelves and floor are spots you can put food on', (await page.locator('main .kcloset [data-spot]').count()) === 31);
  check('Kitchen tab: arrows and tabs slide between the kitchen and your storage', (await page.locator('main .kstage-tabs [role=tab]').count()) === 3 && (await page.locator('main .kstage-arrow').count()) === 2);
  const zc = () => page.locator('main .k3-cam').evaluate((el) => Number(el.style.transform.match(/scale\(([\d.]+)\)/)[1]));
  const z0 = await zc(); await page.locator('main .kcloset').dispatchEvent('click'); await page.waitForTimeout(300);
  check('tap the closet → the view flies in to it', (await zc()) > z0 * 1.3, `${z0} → ${await zc()}`);
  await shot('31-pantry-closet');
  await page.locator('main .kstage-tabs [role=tab]', { hasText: 'Spice cabinet' }).click(); await page.waitForTimeout(700);
  check('…tap Spice cabinet: it comes front and centre', (await page.locator('main .kstage-tabs [role=tab][aria-selected=true]').innerText()) === 'Spice cabinet' && (await zc()) > z0 * 1.3);
  await page.getByRole('tab', { name: /^Pantry \(/ }).click();
  await shot('30-kitchen-pantry');
});
await step('delete my data', async () => {
  const ctx5 = await browser.newContext({ viewport: { width: 390, height: 844 } }); const dp = await ctx5.newPage();
  await dp.goto(`${BASE}/login`); await dp.getByRole('radio', { name: 'Accept' }).click(); await dp.getByRole('button', { name: 'Start playing' }).click(); await dp.waitForURL('**/cook');
  await dp.waitForTimeout(1500); await dp.mouse.click(5, 400);
  await dp.getByRole('navigation').getByRole('link', { name: 'Me', exact: true }).click(); await dp.waitForURL('**/me');
  const uid = await dp.locator('.mono').first().innerText();
  await dp.getByRole('button', { name: 'Delete my data' }).click();
  const del = dp.getByRole('dialog', { name: 'Delete my data' });
  check('Delete my data asks you to type DELETE first', await del.getByRole('button', { name: 'Delete everything' }).isDisabled());
  await del.getByLabel('Type DELETE to confirm').fill('delete'); await del.getByRole('button', { name: 'Delete everything' }).click();
  await dp.waitForURL('**/login?deleted=1', { timeout: 15000 });
  check('after deleting, you land on the start screen with a goodbye', (await dp.getByText('Your data is deleted').count()) === 1);
  await dp.goto(`${BASE}/me`); check('the old game is gone (signed out)', dp.url().includes('/login'));
  check('the player’s id is a real one (sanity)', /^[0-9a-f-]{36}$/.test(uid), uid);
  await ctx5.close();
});
await step('tabs open instantly from memory', async () => {
  await page.goto(`${BASE}/cook`); await page.waitForTimeout(2500); await closePopups();   // the app fills every tab's memory in the background
  for (const t of ['Home', 'Pantry', 'Compete', 'Cook']) { await nav(t); await page.waitForTimeout(700); }
  await ctx.setOffline(true);
  const t0 = Date.now(); await nav('Pantry'); await page.locator('main [aria-label^="Remove "]').first().waitFor({ timeout: 3000 });
  const tp = Date.now() - t0;
  await nav('Compete'); await page.locator('main .bingo').waitFor({ timeout: 3000 });
  check('with the network off, Pantry and Compete still open with everything on them', tp < 1500, `${tp} ms`);
  await ctx.setOffline(false);
});
await step('no-store', async () => { const r = await page.request.get(`${BASE}/home`); check('signed-in pages are Cache-Control no-store', /no-store/.test(r.headers()['cache-control'] || '')); });

const csp = problems.filter((p) => /Content Security Policy|Refused to/.test(p));
check('no CSP violations', csp.length === 0, csp.slice(0, 3).join(' | '));
const other = problems.filter((p) => !csp.includes(p) && !/rpc\/admin_(overview|events)/.test(p));   // the backend refusing a non-admin is expected
check('no page errors or failed requests', other.length === 0, other.slice(0, 5).join(' | '));
await browser.close();
const failed = results.filter((r) => r[0] === 'FAIL').length;
console.log(`\n${results.length - failed}/${results.length} passed`);
process.exit(failed ? 1 : 0);
