-- Whisk setup 18: fridge magnets, free appliances, night mode by default.
--  • The Kitchen shop stops selling appliances (stoves, ovens, dishwasher, smart fridge): they're free in Layout kitchen.
--  • New: fridge magnets. Every dog and cat breed we drew, other pets (all 500 coins), plus cities, postcards, art,
--    kids' drawings, test scores, report cards, wedding invitations, Christmas cards and a few odd ones.
--    Bought magnets show up on the fridge doors in your kitchen.
--  • Night mode is the default look until a player turns it off on Me.
-- Safe to run more than once.

alter table public.kitchen_items drop constraint if exists kitchen_items_kind_check;
alter table public.kitchen_items add constraint kitchen_items_kind_check check (kind in ('gear', 'appliance', 'decor', 'finish', 'magnet'));

update public.kitchen_items set active = false where kind = 'appliance';

insert into public.kitchen_items (id, name, kind, price, country, sort) values
  ('md_affenpinscher', 'Affenpinscher', 'magnet', 500, null, 200),
  ('md_afghan_hound', 'Afghan Hound', 'magnet', 500, null, 201),
  ('md_airedale_terrier', 'Airedale Terrier', 'magnet', 500, null, 202),
  ('md_akita', 'Akita', 'magnet', 500, null, 203),
  ('md_alaskan_malamute', 'Alaskan Malamute', 'magnet', 500, null, 204),
  ('md_american_bulldog', 'American Bulldog', 'magnet', 500, null, 205),
  ('md_american_eskimo_dog', 'American Eskimo Dog', 'magnet', 500, null, 206),
  ('md_american_foxhound', 'American Foxhound', 'magnet', 500, null, 207),
  ('md_american_staffordshire_terrier', 'American Staffordshire Terrier', 'magnet', 500, null, 208),
  ('md_australian_cattle_dog', 'Australian Cattle Dog', 'magnet', 500, null, 209),
  ('md_australian_shepherd', 'Australian Shepherd', 'magnet', 500, null, 210),
  ('md_basenji', 'Basenji', 'magnet', 500, null, 211),
  ('md_basset_hound', 'Basset Hound', 'magnet', 500, null, 212),
  ('md_beagle', 'Beagle', 'magnet', 500, null, 213),
  ('md_bearded_collie', 'Bearded Collie', 'magnet', 500, null, 214),
  ('md_bedlington_terrier', 'Bedlington Terrier', 'magnet', 500, null, 215),
  ('md_belgian_malinois', 'Belgian Malinois', 'magnet', 500, null, 216),
  ('md_bernese_mountain_dog', 'Bernese Mountain Dog', 'magnet', 500, null, 217),
  ('md_bichon_frise', 'Bichon Frise', 'magnet', 500, null, 218),
  ('md_black_and_tan_coonhound', 'Black and Tan Coonhound', 'magnet', 500, null, 219),
  ('md_bloodhound', 'Bloodhound', 'magnet', 500, null, 220),
  ('md_border_collie', 'Border Collie', 'magnet', 500, null, 221),
  ('md_border_terrier', 'Border Terrier', 'magnet', 500, null, 222),
  ('md_borzoi', 'Borzoi', 'magnet', 500, null, 223),
  ('md_boston_terrier', 'Boston Terrier', 'magnet', 500, null, 224),
  ('md_bouvier_des_flandres', 'Bouvier des Flandres', 'magnet', 500, null, 225),
  ('md_boxer', 'Boxer', 'magnet', 500, null, 226),
  ('md_boykin_spaniel', 'Boykin Spaniel', 'magnet', 500, null, 227),
  ('md_briard', 'Briard', 'magnet', 500, null, 228),
  ('md_brittany', 'Brittany', 'magnet', 500, null, 229),
  ('md_brussels_griffon', 'Brussels Griffon', 'magnet', 500, null, 230),
  ('md_bull_terrier', 'Bull Terrier', 'magnet', 500, null, 231),
  ('md_bulldog', 'Bulldog', 'magnet', 500, null, 232),
  ('md_bullmastiff', 'Bullmastiff', 'magnet', 500, null, 233),
  ('md_cairn_terrier', 'Cairn Terrier', 'magnet', 500, null, 234),
  ('md_cane_corso', 'Cane Corso', 'magnet', 500, null, 235),
  ('md_cardigan_welsh_corgi', 'Cardigan Welsh Corgi', 'magnet', 500, null, 236),
  ('md_cavalier_king_charles_spaniel', 'Cavalier King Charles Spaniel', 'magnet', 500, null, 237),
  ('md_chesapeake_bay_retriever', 'Chesapeake Bay Retriever', 'magnet', 500, null, 238),
  ('md_chihuahua', 'Chihuahua', 'magnet', 500, null, 239),
  ('md_chinese_crested', 'Chinese Crested', 'magnet', 500, null, 240),
  ('md_chinese_shar_pei', 'Chinese Shar-Pei', 'magnet', 500, null, 241),
  ('md_chow_chow', 'Chow Chow', 'magnet', 500, null, 242),
  ('md_cocker_spaniel', 'Cocker Spaniel', 'magnet', 500, null, 243),
  ('md_collie', 'Collie', 'magnet', 500, null, 244),
  ('md_dachshund', 'Dachshund', 'magnet', 500, null, 245),
  ('md_dalmatian', 'Dalmatian', 'magnet', 500, null, 246),
  ('md_doberman_pinscher', 'Doberman Pinscher', 'magnet', 500, null, 247),
  ('md_dogue_de_bordeaux', 'Dogue de Bordeaux', 'magnet', 500, null, 248),
  ('md_english_setter', 'English Setter', 'magnet', 500, null, 249),
  ('md_english_springer_spaniel', 'English Springer Spaniel', 'magnet', 500, null, 250),
  ('md_field_spaniel', 'Field Spaniel', 'magnet', 500, null, 251),
  ('md_finnish_spitz', 'Finnish Spitz', 'magnet', 500, null, 252),
  ('md_flat_coated_retriever', 'Flat-Coated Retriever', 'magnet', 500, null, 253),
  ('md_french_bulldog', 'French Bulldog', 'magnet', 500, null, 254),
  ('md_german_pinscher', 'German Pinscher', 'magnet', 500, null, 255),
  ('md_german_shepherd_dog', 'German Shepherd Dog', 'magnet', 500, null, 256),
  ('md_german_shorthaired_pointer', 'German Shorthaired Pointer', 'magnet', 500, null, 257),
  ('md_german_wirehaired_pointer', 'German Wirehaired Pointer', 'magnet', 500, null, 258),
  ('md_giant_schnauzer', 'Giant Schnauzer', 'magnet', 500, null, 259),
  ('md_golden_retriever', 'Golden Retriever', 'magnet', 500, null, 260),
  ('md_gordon_setter', 'Gordon Setter', 'magnet', 500, null, 261),
  ('md_great_dane', 'Great Dane', 'magnet', 500, null, 262),
  ('md_great_pyrenees', 'Great Pyrenees', 'magnet', 500, null, 263),
  ('md_greater_swiss_mountain_dog', 'Greater Swiss Mountain Dog', 'magnet', 500, null, 264),
  ('md_greyhound', 'Greyhound', 'magnet', 500, null, 265),
  ('md_havanese', 'Havanese', 'magnet', 500, null, 266),
  ('md_irish_setter', 'Irish Setter', 'magnet', 500, null, 267),
  ('md_irish_terrier', 'Irish Terrier', 'magnet', 500, null, 268),
  ('md_irish_water_spaniel', 'Irish Water Spaniel', 'magnet', 500, null, 269),
  ('md_irish_wolfhound', 'Irish Wolfhound', 'magnet', 500, null, 270),
  ('md_italian_greyhound', 'Italian Greyhound', 'magnet', 500, null, 271),
  ('md_jack_russell_terrier', 'Jack Russell Terrier', 'magnet', 500, null, 272),
  ('md_japanese_chin', 'Japanese Chin', 'magnet', 500, null, 273),
  ('md_keeshond', 'Keeshond', 'magnet', 500, null, 274),
  ('md_kerry_blue_terrier', 'Kerry Blue Terrier', 'magnet', 500, null, 275),
  ('md_komondor', 'Komondor', 'magnet', 500, null, 276),
  ('md_kuvasz', 'Kuvasz', 'magnet', 500, null, 277),
  ('md_labrador_retriever', 'Labrador Retriever', 'magnet', 500, null, 278),
  ('md_labrador_retriever_black', 'Labrador Retriever (Black)', 'magnet', 500, null, 279),
  ('md_labrador_retriever_chocolate', 'Labrador Retriever (Chocolate)', 'magnet', 500, null, 280),
  ('md_lagotto_romagnolo', 'Lagotto Romagnolo', 'magnet', 500, null, 281),
  ('md_lakeland_terrier', 'Lakeland Terrier', 'magnet', 500, null, 282),
  ('md_leonberger', 'Leonberger', 'magnet', 500, null, 283),
  ('md_lhasa_apso', 'Lhasa Apso', 'magnet', 500, null, 284),
  ('md_maltese', 'Maltese', 'magnet', 500, null, 285),
  ('md_manchester_terrier', 'Manchester Terrier', 'magnet', 500, null, 286),
  ('md_mastiff', 'Mastiff', 'magnet', 500, null, 287),
  ('md_miniature_american_shepherd', 'Miniature American Shepherd', 'magnet', 500, null, 288),
  ('md_miniature_pinscher', 'Miniature Pinscher', 'magnet', 500, null, 289),
  ('md_miniature_schnauzer', 'Miniature Schnauzer', 'magnet', 500, null, 290),
  ('md_newfoundland', 'Newfoundland', 'magnet', 500, null, 291),
  ('md_norfolk_terrier', 'Norfolk Terrier', 'magnet', 500, null, 292),
  ('md_norwegian_elkhound', 'Norwegian Elkhound', 'magnet', 500, null, 293),
  ('md_norwich_terrier', 'Norwich Terrier', 'magnet', 500, null, 294),
  ('md_old_english_sheepdog', 'Old English Sheepdog', 'magnet', 500, null, 295),
  ('md_papillon', 'Papillon', 'magnet', 500, null, 296),
  ('md_pekingese', 'Pekingese', 'magnet', 500, null, 297),
  ('md_pembroke_welsh_corgi', 'Pembroke Welsh Corgi', 'magnet', 500, null, 298),
  ('md_pharaoh_hound', 'Pharaoh Hound', 'magnet', 500, null, 299),
  ('md_plott_hound', 'Plott Hound', 'magnet', 500, null, 300),
  ('md_pointer', 'Pointer', 'magnet', 500, null, 301),
  ('md_pomeranian', 'Pomeranian', 'magnet', 500, null, 302),
  ('md_poodle_standard', 'Poodle (Standard)', 'magnet', 500, null, 303),
  ('md_poodle_toy', 'Poodle (Toy)', 'magnet', 500, null, 304),
  ('md_portuguese_water_dog', 'Portuguese Water Dog', 'magnet', 500, null, 305),
  ('md_pug', 'Pug', 'magnet', 500, null, 306),
  ('md_puli', 'Puli', 'magnet', 500, null, 307),
  ('md_rat_terrier', 'Rat Terrier', 'magnet', 500, null, 308),
  ('md_redbone_coonhound', 'Redbone Coonhound', 'magnet', 500, null, 309),
  ('md_rhodesian_ridgeback', 'Rhodesian Ridgeback', 'magnet', 500, null, 310),
  ('md_rottweiler', 'Rottweiler', 'magnet', 500, null, 311),
  ('md_saint_bernard', 'Saint Bernard', 'magnet', 500, null, 312),
  ('md_saluki', 'Saluki', 'magnet', 500, null, 313),
  ('md_samoyed', 'Samoyed', 'magnet', 500, null, 314),
  ('md_schipperke', 'Schipperke', 'magnet', 500, null, 315),
  ('md_scottish_deerhound', 'Scottish Deerhound', 'magnet', 500, null, 316),
  ('md_scottish_terrier', 'Scottish Terrier', 'magnet', 500, null, 317),
  ('md_shetland_sheepdog', 'Shetland Sheepdog', 'magnet', 500, null, 318),
  ('md_shiba_inu', 'Shiba Inu', 'magnet', 500, null, 319),
  ('md_shih_tzu', 'Shih Tzu', 'magnet', 500, null, 320),
  ('md_siberian_husky', 'Siberian Husky', 'magnet', 500, null, 321),
  ('md_silky_terrier', 'Silky Terrier', 'magnet', 500, null, 322),
  ('md_skye_terrier', 'Skye Terrier', 'magnet', 500, null, 323),
  ('md_smooth_fox_terrier', 'Smooth Fox Terrier', 'magnet', 500, null, 324),
  ('md_soft_coated_wheaten_terrier', 'Soft Coated Wheaten Terrier', 'magnet', 500, null, 325),
  ('md_staffordshire_bull_terrier', 'Staffordshire Bull Terrier', 'magnet', 500, null, 326),
  ('md_standard_schnauzer', 'Standard Schnauzer', 'magnet', 500, null, 327),
  ('md_tibetan_mastiff', 'Tibetan Mastiff', 'magnet', 500, null, 328),
  ('md_tibetan_terrier', 'Tibetan Terrier', 'magnet', 500, null, 329),
  ('md_toy_fox_terrier', 'Toy Fox Terrier', 'magnet', 500, null, 330),
  ('md_vizsla', 'Vizsla', 'magnet', 500, null, 331),
  ('md_weimaraner', 'Weimaraner', 'magnet', 500, null, 332),
  ('md_welsh_springer_spaniel', 'Welsh Springer Spaniel', 'magnet', 500, null, 333),
  ('md_west_highland_white_terrier', 'West Highland White Terrier', 'magnet', 500, null, 334),
  ('md_whippet', 'Whippet', 'magnet', 500, null, 335),
  ('md_wire_fox_terrier', 'Wire Fox Terrier', 'magnet', 500, null, 336),
  ('md_xoloitzcuintli', 'Xoloitzcuintli', 'magnet', 500, null, 337),
  ('md_yorkshire_terrier', 'Yorkshire Terrier', 'magnet', 500, null, 338),
  ('md_cockapoo', 'Cockapoo', 'magnet', 500, null, 339),
  ('md_goldendoodle', 'Goldendoodle', 'magnet', 500, null, 340),
  ('md_labradoodle', 'Labradoodle', 'magnet', 500, null, 341),
  ('md_mutt', 'Mutt', 'magnet', 500, null, 342),
  ('mc_abyssinian', 'Abyssinian', 'magnet', 500, null, 343),
  ('mc_american_bobtail', 'American Bobtail', 'magnet', 500, null, 344),
  ('mc_american_curl', 'American Curl', 'magnet', 500, null, 345),
  ('mc_american_shorthair', 'American Shorthair', 'magnet', 500, null, 346),
  ('mc_american_wirehair', 'American Wirehair', 'magnet', 500, null, 347),
  ('mc_balinese', 'Balinese', 'magnet', 500, null, 348),
  ('mc_bengal', 'Bengal', 'magnet', 500, null, 349),
  ('mc_birman', 'Birman', 'magnet', 500, null, 350),
  ('mc_bombay', 'Bombay', 'magnet', 500, null, 351),
  ('mc_british_shorthair', 'British Shorthair', 'magnet', 500, null, 352),
  ('mc_burmese', 'Burmese', 'magnet', 500, null, 353),
  ('mc_burmilla', 'Burmilla', 'magnet', 500, null, 354),
  ('mc_chartreux', 'Chartreux', 'magnet', 500, null, 355),
  ('mc_colorpoint_shorthair', 'Colorpoint Shorthair', 'magnet', 500, null, 356),
  ('mc_cornish_rex', 'Cornish Rex', 'magnet', 500, null, 357),
  ('mc_devon_rex', 'Devon Rex', 'magnet', 500, null, 358),
  ('mc_egyptian_mau', 'Egyptian Mau', 'magnet', 500, null, 359),
  ('mc_european_burmese', 'European Burmese', 'magnet', 500, null, 360),
  ('mc_exotic_shorthair', 'Exotic Shorthair', 'magnet', 500, null, 361),
  ('mc_havana_brown', 'Havana Brown', 'magnet', 500, null, 362),
  ('mc_japanese_bobtail', 'Japanese Bobtail', 'magnet', 500, null, 363),
  ('mc_khao_manee', 'Khao Manee', 'magnet', 500, null, 364),
  ('mc_korat', 'Korat', 'magnet', 500, null, 365),
  ('mc_laperm', 'LaPerm', 'magnet', 500, null, 366),
  ('mc_lykoi', 'Lykoi', 'magnet', 500, null, 367),
  ('mc_maine_coon', 'Maine Coon', 'magnet', 500, null, 368),
  ('mc_manx', 'Manx', 'magnet', 500, null, 369),
  ('mc_norwegian_forest_cat', 'Norwegian Forest Cat', 'magnet', 500, null, 370),
  ('mc_ocicat', 'Ocicat', 'magnet', 500, null, 371),
  ('mc_oriental', 'Oriental', 'magnet', 500, null, 372),
  ('mc_persian', 'Persian', 'magnet', 500, null, 373),
  ('mc_ragamuffin', 'Ragamuffin', 'magnet', 500, null, 374),
  ('mc_ragdoll', 'Ragdoll', 'magnet', 500, null, 375),
  ('mc_russian_blue', 'Russian Blue', 'magnet', 500, null, 376),
  ('mc_scottish_fold', 'Scottish Fold', 'magnet', 500, null, 377),
  ('mc_selkirk_rex', 'Selkirk Rex', 'magnet', 500, null, 378),
  ('mc_siamese', 'Siamese', 'magnet', 500, null, 379),
  ('mc_siberian', 'Siberian', 'magnet', 500, null, 380),
  ('mc_singapura', 'Singapura', 'magnet', 500, null, 381),
  ('mc_somali', 'Somali', 'magnet', 500, null, 382),
  ('mc_sphynx', 'Sphynx', 'magnet', 500, null, 383),
  ('mc_tonkinese', 'Tonkinese', 'magnet', 500, null, 384),
  ('mc_toybob', 'Toybob', 'magnet', 500, null, 385),
  ('mc_turkish_angora', 'Turkish Angora', 'magnet', 500, null, 386),
  ('mc_turkish_van', 'Turkish Van', 'magnet', 500, null, 387),
  ('mc_tabby_cat', 'Tabby Cat', 'magnet', 500, null, 388),
  ('mc_calico_cat', 'Calico Cat', 'magnet', 500, null, 389),
  ('mc_tuxedo_cat', 'Tuxedo Cat', 'magnet', 500, null, 390),
  ('mp_goldfish', 'Goldfish', 'magnet', 500, null, 391),
  ('mp_clownfish', 'Clownfish', 'magnet', 500, null, 392),
  ('mp_betta', 'Betta fish', 'magnet', 500, null, 393),
  ('mp_puffer', 'Pufferfish', 'magnet', 500, null, 394),
  ('mp_seaturtle', 'Sea turtle', 'magnet', 500, null, 395),
  ('mp_boxturtle', 'Box turtle', 'magnet', 500, null, 396),
  ('mp_tortoise', 'Tortoise', 'magnet', 500, null, 397),
  ('mp_hamster', 'Golden hamster', 'magnet', 500, null, 398),
  ('mp_dwarfhamster', 'Dwarf hamster', 'magnet', 500, null, 399),
  ('mp_teddyhamster', 'Teddy bear hamster', 'magnet', 500, null, 400),
  ('mp_lop', 'Lop bunny', 'magnet', 500, null, 401),
  ('mp_lionhead', 'Lionhead bunny', 'magnet', 500, null, 402),
  ('mp_dutch', 'Dutch bunny', 'magnet', 500, null, 403),
  ('mm_city_tampa', 'Tampa skyline', 'magnet', 1000, null, 404),
  ('mm_city_nyc', 'New York City', 'magnet', 1000, null, 405),
  ('mm_city_paris', 'Paris', 'magnet', 1000, null, 406),
  ('mm_city_tokyo', 'Tokyo', 'magnet', 1000, null, 407),
  ('mm_post_tampa', 'Greetings from Tampa', 'magnet', 800, null, 408),
  ('mm_post_rome', 'Greetings from Rome', 'magnet', 800, null, 409),
  ('mm_post_mexico', 'Saludos from Mexico', 'magnet', 800, null, 410),
  ('mm_post_japan', 'Hello from Japan', 'magnet', 800, null, 411),
  ('mm_art_starry', 'Starry Night magnet', 'magnet', 1500, null, 412),
  ('mm_art_wave', 'Great Wave magnet', 'magnet', 1500, null, 413),
  ('mm_art_mona', 'Mona Lisa magnet', 'magnet', 1500, null, 414),
  ('mm_art_pearl', 'Pearl Earring magnet', 'magnet', 1500, null, 415),
  ('mm_draw_house', 'Kid''s drawing: our house', 'magnet', 300, null, 416),
  ('mm_draw_family', 'Kid''s drawing: my family', 'magnet', 300, null, 417),
  ('mm_draw_rainbow', 'Kid''s drawing: rainbow', 'magnet', 300, null, 418),
  ('mm_draw_dino', 'Kid''s drawing: dinosaur', 'magnet', 300, null, 419),
  ('mm_test_aplus', 'A+ math test', 'magnet', 400, null, 420),
  ('mm_test_100', '100% spelling test', 'magnet', 400, null, 421),
  ('mm_test_star', 'Gold star science quiz', 'magnet', 400, null, 422),
  ('mm_rc_straighta', 'Straight A report card', 'magnet', 600, null, 423),
  ('mm_rc_honor', 'Honor roll certificate', 'magnet', 600, null, 424),
  ('mm_rc_attend', 'Perfect attendance award', 'magnet', 600, null, 425),
  ('mm_wed_classic', 'Wedding invitation (classic)', 'magnet', 700, null, 426),
  ('mm_wed_floral', 'Wedding invitation (floral)', 'magnet', 700, null, 427),
  ('mm_wed_beach', 'Wedding invitation (beach)', 'magnet', 700, null, 428),
  ('mm_xmas_tree', 'Christmas card (tree)', 'magnet', 500, null, 429),
  ('mm_xmas_snowman', 'Christmas card (snowman)', 'magnet', 500, null, 430),
  ('mm_xmas_reindeer', 'Christmas card (reindeer)', 'magnet', 500, null, 431),
  ('mm_cool_disco', 'Disco ball', 'magnet', 2500, null, 432),
  ('mm_cool_goldbar', 'Gold bar', 'magnet', 5000, null, 433),
  ('mm_cool_planet', 'Glow-in-the-dark planet', 'magnet', 2000, null, 434),
  ('mm_cool_lavalamp', 'Lava lamp', 'magnet', 1800, null, 435),
  ('mm_cool_pizza', 'Pizza slice', 'magnet', 600, null, 436),
  ('mm_cool_orange', 'Florida orange', 'magnet', 400, null, 437),
  ('mm_cool_vinyl', 'Vinyl record', 'magnet', 1200, null, 438)
on conflict (id) do update set name = excluded.name, kind = excluded.kind, price = excluded.price, country = excluded.country, sort = excluded.sort, active = true;

-- Your kitchen can only hold shop things you own (gear and decorations as "x:<id>" pieces, shop finishes).
-- Appliances that aren't sold any more are free for everyone.
create or replace function public._kitchen_layouts_guard() returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if tg_op = 'INSERT' and (select count(*) from kitchen_layouts where user_id = new.user_id) >= 12 then
    raise exception 'You can keep 12 kitchens. Delete one to make another.';
  end if;
  if exists (
    select 1 from jsonb_array_elements(new.pieces) p
    where (case
      when (p ->> 'mid') like 'x:%' then substr(p ->> 'mid', 3)
      when (p ->> 'mid') in (select id from kitchen_items where kind = 'appliance' and active) then p ->> 'mid'
      else null end) is not null
      and not exists (select 1 from kitchen_owned o where o.user_id = new.user_id and o.item_id = (case when (p ->> 'mid') like 'x:%' then substr(p ->> 'mid', 3) else p ->> 'mid' end))
  ) or exists (
    select 1 from jsonb_array_elements(new.pieces) p, lateral (values (p -> 'fin' ->> 'tex'), (p -> 'tfin' ->> 'tex')) t(tex)
    where t.tex in ('terrazzo', 'lacquer', 'copper', 'goldmarble')
      and not exists (select 1 from kitchen_owned o where o.user_id = new.user_id and o.item_id = 'fin_' || t.tex)
  ) then
    raise exception 'That kitchen uses something you don''t own yet.';
  end if;
  new.updated_at := now();
  return new;
end $$;

-- night mode by default (the app hasn't launched, so everyone starts on night once; players can switch it on Me,
-- and running this file again won't undo their choice)
do $$ begin
  if coalesce((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'theme_pref'), '') not like '%night%' then
    update public.profiles set theme_pref = 'night' where theme_pref = 'day';
    alter table public.profiles alter column theme_pref set default 'night';
  end if;
end $$;
