// How Whisk works, one card per feature. The first time a player taps something marked data-tip="<id>", its card shows
// once (they can tap "Got it" or just carry on). Every card is also listed under Me › How Whisk works.
// Plain and to the point: what it is, how to use it, what you get. Up to 5 sentences, ideally 3. Shared with Whisk Play.
export const TIPS = {
  welcome: ['Welcome to Whisk', 'Whisk turns the food in your kitchen into meals, and cooking them into points. Tap anything new and a short card explains it, once. You can read all of them any time under Me › How Whisk works.'],
  'tab-home': ['Home', 'Recipes you’re only a grocery or two away from making. Tap one to see everything you’d need, and add the missing items to your shopping list in one tap. Pull down for a fresh set.'],
  'tab-pantry': ['Pantry', 'Everything that’s in your real kitchen. Type it or scan a receipt or barcode to add it, and Whisk tracks what expires soon. The Kitchen tab shows where each item lives in your 3D kitchen.'],
  'tab-cook': ['Cook', 'Recipes you can make right now with what you have, plus a search for any dish from any country. Cook one, snap a photo of your plate and earn 100 XP and 500 coins (up to 3 meals a day).'],
  'tab-compete': ['Compete', 'Weekly challenges, cuisine bingo, the globe and Cook Off with friends. Each one pays XP or coins, and they reset every week.'],
  'tab-me': ['Me', 'Your level, your stats, your kitchen and the Kitchen shop. Tap your name to change it, and find settings at the bottom.'],
  add: ['Add to pantry', 'Type an item, an amount and an expiry date, then add it. Each item earns 5 XP. Frozen food gets a reminder to start thawing.'],
  receipt: ['Scan a receipt', 'Take a photo of a grocery receipt and every item on it goes into your pantry at once.'],
  barcode: ['Scan a barcode', 'Point the camera at a product’s barcode to add it to your pantry without typing.'],
  make: ['What can I make?', 'Shows real recipes that your pantry can make right now, with food that expires soon listed first. Filter by time, cuisine or diet.'],
  fridge: ['Fridge Raid', 'Whisk picks four things from your pantry and finds recipes that use as many of them as possible. Good for using up what’s about to go bad.'],
  search: ['Search any dish', 'Search a dish, an ingredient or a country (try “Albania”). Tap a result to see its ingredients, what you’re missing and a video. Cooking a country’s dishes fills it in on your globe.'],
  channels: ['Your channels', 'Add the cooking YouTubers you like by their @handle. Tap one to watch their recipe videos inside Whisk.'],
  cookoff: ['Cook Off', 'Start a game and share the code, or join a friend’s. Everyone gets a recipe and the same timer, then everyone votes on the best plate. The winner gets 1,000 coins.'],
  friends: ['Friends', 'Add friends with their 6-letter code (tap your own code to copy it). You’ll see the plates they choose to share, and they’ll see yours. Your plates stay private unless you share them.'],
  bingo: ['Cuisine bingo', 'Each square is a cuisine. Cook dishes to mark squares, and get four in a row (across, down or diagonal) before Monday for 200 XP.'],
  quest: ['Daily quest', 'One small task each day, such as adding three items. Finish it and claim 30 XP. A new one arrives tomorrow.'],
  challenges: ['Weekly challenges', 'Three recipes picked for your pantry, from small to big. Cook one with a photo before the week ends to earn its coins.'],
  coins: ['Coins', 'You earn coins by cooking, finishing challenges and completing countries. Spend them in the Kitchen shop on Me.'],
  streak: ['Streak', 'The number of days in a row you’ve cooked. One streak freeze a week covers a missed day. If you miss one anyway, cooking twice the next day brings it back.'],
  stage: ['The globe', 'Swipe to spin it. While it’s spinning, tap Throw a dart and cook something from the country it lands on. One dish from a country makes it Bronze, three make it Silver, and five make it Gold, which paints it in its colors and pays 3,000 coins.'],
  album: ['Countries', 'Every dish you cook counts toward its country: 1 for Bronze, 3 for Silver, 5 for Gold. Gold countries unlock new kitchen items in the shop and harder challenges.'],
  closet: ['Kitchen shop', 'Spend coins on kitchen gear, decorations, finishes and fridge magnets. Whatever you buy goes straight into your kitchen, and magnets stick to your fridge.'],
  mykitchen: ['Your kitchen', 'This is the kitchen you built, in the home you’ve earned. Tap its name to rename it and Edit to change it. Each new level range moves you to a bigger place in Tampa.'],
  kitchen: ['Kitchen tab', 'Your 3D kitchen with your food in it. Tap a door or drawer to open it, then tap a shelf to see what’s there. Drag to turn it, pinch to zoom, and use the arrows to visit your pantry closet or spice cabinet.'],
  putaway: ['Put it away', 'Drag each food box onto a shelf, drawer or fridge door, or tap the box and then tap a spot. Each one earns 3 XP, and quick drops in a row build a combo.'],
  design: ['Layout kitchen', 'Build your kitchen piece by piece. Tap a piece to pick it, then drag it to move it or pull a yellow dot to resize it; dragging anywhere else turns the view. Save keeps it, and Display makes it the kitchen you see in your pantry.'],
  storage: ['Pantry closet & spice cabinet', 'Extra storage you can place anywhere away from the kitchen. The closet has shelves on three walls plus floor space. Tap it to zoom in and put food on a specific shelf.'],
  cchallenges: ['Country challenges', 'A recipe from a country you’ve started, worth 250 XP. Once a country is Gold you get two harder ones worth 400 XP.'],
  profile: ['Your stats', 'Your level, recipes cooked, items in your pantry, countries cooked from and your streak. The bar shows how close you are to moving to your next home.'],
  recipe: ['A recipe', 'Every amount is measured. Change the × to cook for more people, and tap I cooked it when you’re done to earn the rewards.']
};
