// Generates supabase/migrations/0002_whisk_seed.sql from the app's catalogs,
// so the database items always match the 3D models in lib/whisk3d/engine.js.
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { pathToFileURL } from 'node:url';

const root = process.cwd();
const three = pathToFileURL(path.join(root, 'node_modules/three/build/three.module.js')).href;
const src = fs.readFileSync(path.join(root, 'lib/whisk3d/engine.js'), 'utf8').replace("from 'three'", `from '${three}'`);
const tmp = path.join(os.tmpdir(), `whisk-engine-${Date.now()}.mjs`);
fs.writeFileSync(tmp, src);
const { SLOTS } = await import(pathToFileURL(tmp).href);
const mealsSrc = fs.readFileSync(path.join(root, 'lib/catalog/meals.js'), 'utf8');
const tmp2 = path.join(os.tmpdir(), `whisk-meals-${Date.now()}.mjs`);
fs.writeFileSync(tmp2, mealsSrc);
const { CHALLENGE_MEALS } = await import(pathToFileURL(tmp2).href);

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const items = SLOTS.flatMap((c) => c.list.map((it) => `(${q(it.id)}, ${q(c.key)}, ${q(it.name)}, ${q(it.rarity)}, ${it.price}, ${it.sort})`));
const meals = CHALLENGE_MEALS.map(([n, cu, m, t, p, s, pr]) => `(${q(n)}, ${q(cu)}, ${m}, ${t}, ${p}, ${s}, ${pr})`);
const sql = `-- Generated by scripts/gen-seed.mjs — do not edit by hand.
-- ${items.length} shop items, ${meals.length} challenge meals.
insert into public.items (id, slot, name, rarity, price, sort) values
${items.join(',\n')}
on conflict (id) do update set slot = excluded.slot, name = excluded.name, rarity = excluded.rarity, price = excluded.price, sort = excluded.sort, active = true;

insert into public.challenge_meals (name, cuisine, minutes, technique, prep, steps, precision_level) values
${meals.join(',\n')}
on conflict (name) do update set cuisine = excluded.cuisine, minutes = excluded.minutes, technique = excluded.technique, prep = excluded.prep, steps = excluded.steps, precision_level = excluded.precision_level;
`;
fs.writeFileSync(path.join(root, 'supabase/migrations/0002_whisk_seed.sql'), sql);
fs.unlinkSync(tmp); fs.unlinkSync(tmp2);
console.log(`wrote ${items.length} items, ${meals.length} meals`);
