-- 0012: free dish list in the database, log any dish from it, and 5,000 coins for every passport stamp.
-- Safe to run more than once.

-- ---------- Whisk's dish list (1,787 dishes, all 193 countries). Read only by the server functions below. ----------
create table if not exists public.dishes (
  country text not null check (country ~ '^[A-Z]{2}$'),
  name text not null check (char_length(name) between 1 and 80),
  type text not null,
  cuisine text not null check (char_length(cuisine) <= 40)
);
create unique index if not exists dishes_country_name on public.dishes (country, lower(name));
alter table public.dishes enable row level security;
revoke all on public.dishes from public, anon, authenticated;
insert into public.dishes (country, name, type, cuisine) values
('AD','Escudella i Carn d''Olla','soup','Andorra'),
('AD','Trinxat','main','Andorra'),
('AD','Canelons','main','Andorra'),
('AD','Coca','bread','Andorra'),
('AD','Crema Catalana','dessert','Andorra'),
('AE','Machboos','main','United Arab Emirates · Middle Eastern'),
('AE','Harees','main','United Arab Emirates · Middle Eastern'),
('AE','Luqaimat','dessert','United Arab Emirates · Middle Eastern'),
('AE','Shawarma','street food','United Arab Emirates · Middle Eastern'),
('AE','Balaleet','breakfast','United Arab Emirates · Middle Eastern'),
('AE','Chebab','breakfast','United Arab Emirates · Middle Eastern'),
('AE','Thareed','main','United Arab Emirates · Middle Eastern'),
('AE','Madrooba','main','United Arab Emirates · Middle Eastern'),
('AF','Kabuli Pulao','main','Afghanistan'),
('AF','Mantu','main','Afghanistan'),
('AF','Ashak','main','Afghanistan'),
('AF','Bolani','street food','Afghanistan'),
('AF','Chapli Kebab','main','Afghanistan'),
('AF','Qorma Sabzi','main','Afghanistan'),
('AF','Aushak Soup (Aush)','soup','Afghanistan'),
('AF','Borani Banjan','side','Afghanistan'),
('AF','Naan-e Afghani','bread','Afghanistan'),
('AF','Firni','dessert','Afghanistan'),
('AF','Sheer Yakh','dessert','Afghanistan'),
('AF','Doogh','drink','Afghanistan'),
('AG','Fungee and Pepperpot','main','Antigua and Barbuda · Caribbean'),
('AG','Ducana','side','Antigua and Barbuda · Caribbean'),
('AG','Saltfish','main','Antigua and Barbuda · Caribbean'),
('AG','Seasoned Rice','side','Antigua and Barbuda · Caribbean'),
('AG','Johnny Cakes','bread','Antigua and Barbuda · Caribbean'),
('AL','Byrek','street food','Albania'),
('AL','Tavë Kosi','main','Albania'),
('AL','Fërgesë','main','Albania'),
('AL','Qofte','main','Albania'),
('AL','Fli','main','Albania'),
('AL','Speca të Mbushura','main','Albania'),
('AL','Jani me Fasule','soup','Albania'),
('AL','Pispili','bread','Albania'),
('AL','Trileçe','dessert','Albania'),
('AL','Ballokume','dessert','Albania'),
('AL','Kadaif','dessert','Albania'),
('AM','Khorovats','main','Armenia'),
('AM','Dolma','main','Armenia'),
('AM','Harissa','main','Armenia'),
('AM','Lavash','bread','Armenia'),
('AM','Khash','soup','Armenia'),
('AM','Spas','soup','Armenia'),
('AM','Ghapama','main','Armenia'),
('AM','Lahmajoun','street food','Armenia'),
('AM','Ishkhan','main','Armenia'),
('AM','Gata','dessert','Armenia'),
('AM','Tolma (Cabbage)','main','Armenia'),
('AO','Muamba de Galinha','main','Angola'),
('AO','Calulu','main','Angola'),
('AO','Mufete','main','Angola'),
('AO','Kizaca','side','Angola'),
('AO','Feijão de Óleo de Palma','main','Angola'),
('AO','Cocada Amarela','dessert','Angola'),
('AR','Asado','main','Argentina'),
('AR','Chimichurri','sauce','Argentina'),
('AR','Empanadas','street food','Argentina'),
('AR','Milanesa','main','Argentina'),
('AR','Locro','soup','Argentina'),
('AR','Choripán','street food','Argentina'),
('AR','Provoleta','side','Argentina'),
('AR','Humita','main','Argentina'),
('AR','Medialunas','breakfast','Argentina'),
('AR','Alfajores','dessert','Argentina'),
('AR','Dulce de Leche','sauce','Argentina'),
('AT','Wiener Schnitzel','main','Austria'),
('AT','Tafelspitz','main','Austria'),
('AT','Goulash','main','Austria'),
('AT','Käsespätzle','main','Austria'),
('AT','Frittatensuppe','soup','Austria'),
('AT','Knödel','side','Austria'),
('AT','Kaiserschmarrn','dessert','Austria'),
('AT','Apfelstrudel','dessert','Austria'),
('AT','Sachertorte','dessert','Austria'),
('AT','Marillenknödel','dessert','Austria'),
('AT','Brettljause','snack','Austria'),
('AU','Meat Pie','street food','Australia'),
('AU','Sausage Roll','snack','Australia'),
('AU','Pavlova','dessert','Australia'),
('AU','Lamingtons','dessert','Australia'),
('AU','Anzac Biscuits','dessert','Australia'),
('AU','Vegemite Toast','breakfast','Australia'),
('AU','Damper','bread','Australia'),
('AU','Chicken Parmigiana','main','Australia'),
('AU','Fairy Bread','snack','Australia'),
('AU','Barramundi','main','Australia'),
('AU','Lemon Myrtle Prawns','main','Australia'),
('AU','Flat White','drink','Australia'),
('AZ','Plov','main','Azerbaijan'),
('AZ','Dolma','main','Azerbaijan'),
('AZ','Dushbara','soup','Azerbaijan'),
('AZ','Piti','soup','Azerbaijan'),
('AZ','Lula Kebab','main','Azerbaijan'),
('AZ','Qutab','street food','Azerbaijan'),
('AZ','Dovga','soup','Azerbaijan'),
('AZ','Saj Ichi','main','Azerbaijan'),
('AZ','Pakhlava','dessert','Azerbaijan'),
('AZ','Shekerbura','dessert','Azerbaijan'),
('BA','Ćevapi','main','Bosnia and Herzegovina'),
('BA','Burek','street food','Bosnia and Herzegovina'),
('BA','Begova Čorba','soup','Bosnia and Herzegovina'),
('BA','Bosanski Lonac','main','Bosnia and Herzegovina'),
('BA','Japrak','main','Bosnia and Herzegovina'),
('BA','Klepe','main','Bosnia and Herzegovina'),
('BA','Sogan Dolma','main','Bosnia and Herzegovina'),
('BA','Somun','bread','Bosnia and Herzegovina'),
('BA','Tufahija','dessert','Bosnia and Herzegovina'),
('BA','Hurmašice','dessert','Bosnia and Herzegovina'),
('BA','Ajvar','sauce','Bosnia and Herzegovina'),
('BB','Cou-Cou and Flying Fish','main','Barbados · Caribbean'),
('BB','Bajan Fish Cakes','street food','Barbados · Caribbean'),
('BB','Pudding and Souse','main','Barbados · Caribbean'),
('BB','Macaroni Pie','side','Barbados · Caribbean'),
('BB','Fish Cutter','street food','Barbados · Caribbean'),
('BB','Bajan Pepper Sauce','sauce','Barbados · Caribbean'),
('BB','Conkies','dessert','Barbados · Caribbean'),
('BB','Rum Punch','drink','Barbados · Caribbean'),
('BD','Kacchi Biryani','main','Bangladesh'),
('BD','Shorshe Ilish','main','Bangladesh'),
('BD','Bhuna Khichuri','main','Bangladesh'),
('BD','Beef Kala Bhuna','main','Bangladesh'),
('BD','Fuchka','street food','Bangladesh'),
('BD','Dal','soup','Bangladesh'),
('BD','Aloo Bhorta','side','Bangladesh'),
('BD','Chingri Malai Curry','main','Bangladesh'),
('BD','Pitha','dessert','Bangladesh'),
('BD','Roshogolla','dessert','Bangladesh'),
('BD','Mishti Doi','dessert','Bangladesh'),
('BD','Borhani','drink','Bangladesh'),
('BE','Moules-Frites','main','Belgium'),
('BE','Carbonade Flamande','main','Belgium'),
('BE','Belgian Fries','street food','Belgium'),
('BE','Waterzooi','soup','Belgium'),
('BE','Stoemp','side','Belgium'),
('BE','Chicons au Gratin','main','Belgium'),
('BE','Boulets à la Liégeoise','main','Belgium'),
('BE','Liège Waffles','dessert','Belgium'),
('BE','Brussels Waffles','dessert','Belgium'),
('BE','Speculoos','dessert','Belgium'),
('BE','Andalouse Sauce','sauce','Belgium'),
('BF','Riz Gras','main','Burkina Faso'),
('BF','Tô','main','Burkina Faso'),
('BF','Poulet Bicyclette','main','Burkina Faso'),
('BF','Sauce Arachide','sauce','Burkina Faso'),
('BF','Sauce Gombo','sauce','Burkina Faso'),
('BF','Babenda','main','Burkina Faso'),
('BF','Zoom-Koom','drink','Burkina Faso'),
('BG','Shopska Salad','salad','Bulgaria'),
('BG','Banitsa','breakfast','Bulgaria'),
('BG','Tarator','soup','Bulgaria'),
('BG','Kebapche','street food','Bulgaria'),
('BG','Kyufte','main','Bulgaria'),
('BG','Lyutenitsa','sauce','Bulgaria'),
('BG','Musaka','main','Bulgaria'),
('BG','Sarmi','main','Bulgaria'),
('BG','Kavarma','main','Bulgaria'),
('BG','Shkembe Chorba','soup','Bulgaria'),
('BG','Mekitsa','breakfast','Bulgaria'),
('BG','Kozunak','dessert','Bulgaria'),
('BH','Machboos','main','Bahrain · Middle Eastern'),
('BH','Muhammar','side','Bahrain · Middle Eastern'),
('BH','Harees','main','Bahrain · Middle Eastern'),
('BH','Balaleet','breakfast','Bahrain · Middle Eastern'),
('BH','Samboosa','street food','Bahrain · Middle Eastern'),
('BH','Halwa Bahraini','dessert','Bahrain · Middle Eastern'),
('BH','Gabout','main','Bahrain · Middle Eastern'),
('BI','Ibiharage','main','Burundi'),
('BI','Mukeke','main','Burundi'),
('BI','Ndagala','main','Burundi'),
('BI','Isombe','main','Burundi'),
('BI','Ubugali','side','Burundi'),
('BI','Boko Boko','main','Burundi'),
('BI','Goat Brochettes','street food','Burundi'),
('BJ','Amiwo','main','Benin'),
('BJ','Sauce Gombo','sauce','Benin'),
('BJ','Moyo','sauce','Benin'),
('BJ','Kuli-Kuli','snack','Benin'),
('BJ','Atassi','main','Benin'),
('BJ','Peanut Soup','soup','Benin'),
('BN','Ambuyat','main','Brunei'),
('BN','Nasi Katok','main','Brunei'),
('BN','Beef Rendang','main','Brunei'),
('BN','Nasi Lemak','main','Brunei'),
('BN','Kelupis','side','Brunei'),
('BN','Satay','street food','Brunei'),
('BN','Sambal Belacan','sauce','Brunei'),
('BN','Kuih Mor','dessert','Brunei'),
('BO','Salteñas','street food','Bolivia'),
('BO','Pique a lo Macho','main','Bolivia'),
('BO','Silpancho','main','Bolivia'),
('BO','Sopa de Maní','soup','Bolivia'),
('BO','Majadito','main','Bolivia'),
('BO','Sajta de Pollo','main','Bolivia'),
('BO','Anticuchos','street food','Bolivia'),
('BO','Llajua','sauce','Bolivia'),
('BO','Cuñapé','bread','Bolivia'),
('BO','Api','drink','Bolivia'),
('BR','Feijoada','main','Brazil · Brazilian'),
('BR','Pão de Queijo','bread','Brazil · Brazilian'),
('BR','Coxinha','street food','Brazil · Brazilian'),
('BR','Moqueca','main','Brazil · Brazilian'),
('BR','Picanha','main','Brazil · Brazilian'),
('BR','Acarajé','street food','Brazil · Brazilian'),
('BR','Farofa','side','Brazil · Brazilian'),
('BR','Vinagrete','sauce','Brazil · Brazilian'),
('BR','Pastel','street food','Brazil · Brazilian'),
('BR','Brigadeiro','dessert','Brazil · Brazilian'),
('BR','Açaí Bowl','breakfast','Brazil · Brazilian'),
('BR','Caipirinha','drink','Brazil · Brazilian'),
('BS','Conch Fritters','street food','Bahamas · Caribbean'),
('BS','Cracked Conch','main','Bahamas · Caribbean'),
('BS','Conch Salad','salad','Bahamas · Caribbean'),
('BS','Peas n'' Rice','side','Bahamas · Caribbean'),
('BS','Johnnycake','bread','Bahamas · Caribbean'),
('BS','Stew Fish','main','Bahamas · Caribbean'),
('BS','Guava Duff','dessert','Bahamas · Caribbean'),
('BT','Ema Datshi','main','Bhutan'),
('BT','Kewa Datshi','main','Bhutan'),
('BT','Shamu Datshi','main','Bhutan'),
('BT','Phaksha Paa','main','Bhutan'),
('BT','Momo','street food','Bhutan'),
('BT','Jasha Maru','main','Bhutan'),
('BT','Suja','drink','Bhutan'),
('BW','Seswaa','main','Botswana'),
('BW','Morogo','side','Botswana'),
('BW','Magwinya','street food','Botswana'),
('BW','Bogobe jwa Lerotse','side','Botswana'),
('BW','Dikgobe','main','Botswana'),
('BW','Chakalaka','sauce','Botswana'),
('BY','Draniki','main','Belarus'),
('BY','Machanka','main','Belarus'),
('BY','Kalduny','main','Belarus'),
('BY','Babka','main','Belarus'),
('BY','Kholodnik','soup','Belarus'),
('BY','Borscht','soup','Belarus'),
('BY','Kletski','soup','Belarus'),
('BY','Syrniki','breakfast','Belarus'),
('BZ','Rice and Beans','main','Belize'),
('BZ','Stew Chicken','main','Belize'),
('BZ','Fry Jacks','breakfast','Belize'),
('BZ','Hudut','main','Belize'),
('BZ','Garnaches','street food','Belize'),
('BZ','Panades','street food','Belize'),
('BZ','Salbutes','street food','Belize'),
('BZ','Boil Up','main','Belize'),
('BZ','Powder Bun','dessert','Belize'),
('CA','Poutine','main','Canada'),
('CA','Butter Tarts','dessert','Canada'),
('CA','Nanaimo Bars','dessert','Canada'),
('CA','Tourtière','main','Canada'),
('CA','Peameal Bacon Sandwich','street food','Canada'),
('CA','Montreal-Style Bagels','bread','Canada'),
('CA','Montreal Smoked Meat','main','Canada'),
('CA','BeaverTails','dessert','Canada'),
('CA','Pea Soup','soup','Canada'),
('CA','Bannock','bread','Canada'),
('CA','Pouding Chômeur','dessert','Canada'),
('CA','Caesar','drink','Canada'),
('CD','Poulet Moambé','main','DR Congo'),
('CD','Pondu','main','DR Congo'),
('CD','Fufu','side','DR Congo'),
('CD','Liboké','main','DR Congo'),
('CD','Chikwangue','side','DR Congo'),
('CD','Makayabu','main','DR Congo'),
('CD','Ntaba','street food','DR Congo'),
('CD','Makemba','side','DR Congo'),
('CD','Mikate','snack','DR Congo'),
('CD','Lituma','side','DR Congo'),
('CF','Gozo','side','Central African Republic'),
('CF','Kanda','main','Central African Republic'),
('CF','Ngunza','main','Central African Republic'),
('CF','Maboké','main','Central African Republic'),
('CF','Peanut Chicken Stew','main','Central African Republic'),
('CF','Makara','snack','Central African Republic'),
('CG','Saka Saka','main','Congo'),
('CG','Poulet Moambé','main','Congo'),
('CG','Liboké de Poisson','main','Congo'),
('CG','Chikwangue','side','Congo'),
('CG','Fufu','side','Congo'),
('CG','Fried Plantains','side','Congo'),
('CG','Mikate','snack','Congo'),
('CH','Cheese Fondue','main','Switzerland'),
('CH','Raclette','main','Switzerland'),
('CH','Rösti','side','Switzerland'),
('CH','Zürcher Geschnetzeltes','main','Switzerland'),
('CH','Älplermagronen','main','Switzerland'),
('CH','Capuns','main','Switzerland'),
('CH','Bircher Muesli','breakfast','Switzerland'),
('CH','Zopf','bread','Switzerland'),
('CH','Basler Läckerli','dessert','Switzerland'),
('CH','Nusstorte','dessert','Switzerland'),
('CI','Attiéké','side','Côte d''Ivoire'),
('CI','Alloco','street food','Côte d''Ivoire'),
('CI','Garba','street food','Côte d''Ivoire'),
('CI','Kedjenou','main','Côte d''Ivoire'),
('CI','Foutou','side','Côte d''Ivoire'),
('CI','Sauce Graine','sauce','Côte d''Ivoire'),
('CI','Sauce Arachide','sauce','Côte d''Ivoire'),
('CI','Placali','side','Côte d''Ivoire'),
('CI','Poisson Braisé','main','Côte d''Ivoire'),
('CI','Gnamakoudji','drink','Côte d''Ivoire'),
('CL','Empanadas de Pino','street food','Chile'),
('CL','Pastel de Choclo','main','Chile'),
('CL','Cazuela','soup','Chile'),
('CL','Completo','street food','Chile'),
('CL','Sopaipillas','snack','Chile'),
('CL','Curanto','main','Chile'),
('CL','Charquicán','main','Chile'),
('CL','Porotos Granados','main','Chile'),
('CL','Humitas','main','Chile'),
('CL','Pebre','sauce','Chile'),
('CL','Chorrillana','main','Chile'),
('CL','Mote con Huesillo','drink','Chile'),
('CM','Ndolé','main','Cameroon'),
('CM','Eru','main','Cameroon'),
('CM','Achu Soup','soup','Cameroon'),
('CM','Koki','main','Cameroon'),
('CM','Poulet DG','main','Cameroon'),
('CM','Mbongo Tchobi','main','Cameroon'),
('CM','Kondre','main','Cameroon'),
('CM','Puff-Puff','snack','Cameroon'),
('CM','Soya','street food','Cameroon'),
('CM','Sanga','main','Cameroon'),
('CN','Kung Pao Chicken','main','China · Chinese'),
('CN','Mapo Tofu','main','China · Chinese'),
('CN','Peking Duck','main','China · Chinese'),
('CN','Xiaolongbao','snack','China · Chinese'),
('CN','Jiaozi','main','China · Chinese'),
('CN','Char Siu','main','China · Chinese'),
('CN','Sweet and Sour Pork','main','China · Chinese'),
('CN','Hot Pot','main','China · Chinese'),
('CN','Dan Dan Noodles','main','China · Chinese'),
('CN','Chow Mein','main','China · Chinese'),
('CN','Hot and Sour Soup','soup','China · Chinese'),
('CN','Egg Fried Rice','main','China · Chinese'),
('CN','Scallion Pancakes','street food','China · Chinese'),
('CN','Baozi','breakfast','China · Chinese'),
('CN','Congee','breakfast','China · Chinese'),
('CN','Mooncakes','dessert','China · Chinese'),
('CO','Bandeja Paisa','main','Colombia'),
('CO','Ajiaco','soup','Colombia'),
('CO','Arepas','bread','Colombia'),
('CO','Sancocho','soup','Colombia'),
('CO','Empanadas','street food','Colombia'),
('CO','Patacones','side','Colombia'),
('CO','Lechona','main','Colombia'),
('CO','Changua','breakfast','Colombia'),
('CO','Buñuelos','snack','Colombia'),
('CO','Pandebono','bread','Colombia'),
('CO','Arroz con Coco','side','Colombia'),
('CO','Ají','sauce','Colombia'),
('CR','Gallo Pinto','breakfast','Costa Rica'),
('CR','Casado','main','Costa Rica'),
('CR','Olla de Carne','soup','Costa Rica'),
('CR','Arroz con Pollo','main','Costa Rica'),
('CR','Chifrijo','snack','Costa Rica'),
('CR','Sopa Negra','soup','Costa Rica'),
('CR','Tamales','main','Costa Rica'),
('CR','Patacones','side','Costa Rica'),
('CR','Ceviche','snack','Costa Rica'),
('CR','Salsa Lizano','sauce','Costa Rica'),
('CR','Tres Leches','dessert','Costa Rica'),
('CU','Ropa Vieja','main','Cuba · Caribbean'),
('CU','Cuban Sandwich','street food','Cuba · Caribbean'),
('CU','Moros y Cristianos','side','Cuba · Caribbean'),
('CU','Picadillo','main','Cuba · Caribbean'),
('CU','Lechón Asado','main','Cuba · Caribbean'),
('CU','Yuca con Mojo','side','Cuba · Caribbean'),
('CU','Tostones','side','Cuba · Caribbean'),
('CU','Vaca Frita','main','Cuba · Caribbean'),
('CU','Black Bean Soup','soup','Cuba · Caribbean'),
('CU','Croquetas','snack','Cuba · Caribbean'),
('CU','Pastelitos de Guayaba','dessert','Cuba · Caribbean'),
('CU','Flan','dessert','Cuba · Caribbean'),
('CU','Mojito','drink','Cuba · Caribbean'),
('CV','Cachupa','main','Cabo Verde'),
('CV','Caldo de Peixe','soup','Cabo Verde'),
('CV','Pastel com Diabo Dentro','snack','Cabo Verde'),
('CV','Xerém','main','Cabo Verde'),
('CV','Djagacida','main','Cabo Verde'),
('CV','Pudim de Queijo','dessert','Cabo Verde'),
('CY','Halloumi','snack','Cyprus · Mediterranean'),
('CY','Souvla','main','Cyprus · Mediterranean'),
('CY','Sheftalia','street food','Cyprus · Mediterranean'),
('CY','Kleftiko','main','Cyprus · Mediterranean'),
('CY','Koupepia','main','Cyprus · Mediterranean'),
('CY','Afelia','main','Cyprus · Mediterranean'),
('CY','Makaronia tou Fournou','main','Cyprus · Mediterranean'),
('CY','Flaouna','bread','Cyprus · Mediterranean'),
('CY','Tahini Dip','sauce','Cyprus · Mediterranean'),
('CY','Loukoumades','dessert','Cyprus · Mediterranean'),
('CZ','Svíčková','main','Czechia'),
('CZ','Vepřo Knedlo Zelo','main','Czechia'),
('CZ','Knedlíky','side','Czechia'),
('CZ','Guláš','main','Czechia'),
('CZ','Smažený Sýr','main','Czechia'),
('CZ','Bramboráky','snack','Czechia'),
('CZ','Kulajda','soup','Czechia'),
('CZ','Česnečka','soup','Czechia'),
('CZ','Ovocné Knedlíky','dessert','Czechia'),
('CZ','Koláče','dessert','Czechia'),
('CZ','Trdelník','street food','Czechia'),
('CZ','Utopenci','snack','Czechia'),
('DE','Bratwurst','street food','Germany'),
('DE','Wiener Schnitzel','main','Germany'),
('DE','Currywurst','street food','Germany'),
('DE','Sauerbraten','main','Germany'),
('DE','Rouladen','main','Germany'),
('DE','Schweinshaxe','main','Germany'),
('DE','Käsespätzle','main','Germany'),
('DE','Kartoffelsalat','salad','Germany'),
('DE','Kartoffelpuffer','side','Germany'),
('DE','Sauerkraut','side','Germany'),
('DE','Brezel','bread','Germany'),
('DE','Black Forest Cake','dessert','Germany'),
('DE','Apfelstrudel','dessert','Germany'),
('DJ','Skoudehkaris','main','Djibouti'),
('DJ','Lahoh','bread','Djibouti'),
('DJ','Fah-Fah','soup','Djibouti'),
('DJ','Sambusa','snack','Djibouti'),
('DJ','Halwa','dessert','Djibouti'),
('DJ','Fried Fish with Red Sauce','main','Djibouti'),
('DK','Smørrebrød','main','Denmark'),
('DK','Frikadeller','main','Denmark'),
('DK','Stegt Flæsk','main','Denmark'),
('DK','Flæskesteg','main','Denmark'),
('DK','Rugbrød','bread','Denmark'),
('DK','Æbleskiver','dessert','Denmark'),
('DK','Wienerbrød','breakfast','Denmark'),
('DK','Kanelsnegl','breakfast','Denmark'),
('DK','Risalamande','dessert','Denmark'),
('DK','Leverpostej','snack','Denmark'),
('DK','Rød Pølse','street food','Denmark'),
('DK','Rødgrød med Fløde','dessert','Denmark'),
('DM','Callaloo Soup','soup','Dominica · Caribbean'),
('DM','Bakes','bread','Dominica · Caribbean'),
('DM','Titiri Accra','snack','Dominica · Caribbean'),
('DM','Saltfish and Green Figs','main','Dominica · Caribbean'),
('DM','Bouyon','soup','Dominica · Caribbean'),
('DM','Crab Backs','main','Dominica · Caribbean'),
('DO','Mangú','breakfast','Dominican Republic · Caribbean'),
('DO','La Bandera','main','Dominican Republic · Caribbean'),
('DO','Sancocho','soup','Dominican Republic · Caribbean'),
('DO','Locrio','main','Dominican Republic · Caribbean'),
('DO','Moro de Guandules','side','Dominican Republic · Caribbean'),
('DO','Chicharrón','snack','Dominican Republic · Caribbean'),
('DO','Tostones','side','Dominican Republic · Caribbean'),
('DO','Chimi','street food','Dominican Republic · Caribbean'),
('DO','Pastelón','main','Dominican Republic · Caribbean'),
('DO','Habichuelas con Dulce','dessert','Dominican Republic · Caribbean'),
('DO','Bizcocho Dominicano','dessert','Dominican Republic · Caribbean'),
('DO','Morir Soñando','drink','Dominican Republic · Caribbean'),
('DZ','Couscous','main','Algeria'),
('DZ','Chakhchoukha','main','Algeria'),
('DZ','Chorba Frik','soup','Algeria'),
('DZ','Harira','soup','Algeria'),
('DZ','Rechta','main','Algeria'),
('DZ','Karantika','street food','Algeria'),
('DZ','Chakchouka','main','Algeria'),
('DZ','Mhadjeb','street food','Algeria'),
('DZ','Kesra','bread','Algeria'),
('DZ','Makroud','dessert','Algeria'),
('DZ','Dziriet','dessert','Algeria'),
('EC','Encebollado','soup','Ecuador'),
('EC','Ceviche de Camarón','main','Ecuador'),
('EC','Llapingachos','main','Ecuador'),
('EC','Locro de Papa','soup','Ecuador'),
('EC','Fanesca','soup','Ecuador'),
('EC','Hornado','main','Ecuador'),
('EC','Bolón de Verde','breakfast','Ecuador'),
('EC','Seco de Pollo','main','Ecuador'),
('EC','Encocado de Pescado','main','Ecuador'),
('EC','Humitas','snack','Ecuador'),
('EC','Empanadas de Viento','street food','Ecuador'),
('EC','Colada Morada','drink','Ecuador'),
('EE','Verivorst','main','Estonia'),
('EE','Mulgikapsad','main','Estonia'),
('EE','Mulgipuder','side','Estonia'),
('EE','Rosolje','salad','Estonia'),
('EE','Kiluvõileib','snack','Estonia'),
('EE','Sült','side','Estonia'),
('EE','Kama','dessert','Estonia'),
('EE','Must Leib','bread','Estonia'),
('EE','Kohuke','dessert','Estonia'),
('EG','Koshari','main','Egypt'),
('EG','Ful Medames','breakfast','Egypt'),
('EG','Ta''ameya','street food','Egypt'),
('EG','Molokhia','soup','Egypt'),
('EG','Mahshi','main','Egypt'),
('EG','Fattah','main','Egypt'),
('EG','Hawawshi','street food','Egypt'),
('EG','Kofta','main','Egypt'),
('EG','Feteer Meshaltet','bread','Egypt'),
('EG','Om Ali','dessert','Egypt'),
('EG','Basbousa','dessert','Egypt'),
('EG','Tahini Sauce','sauce','Egypt'),
('ER','Zigni','main','Eritrea'),
('ER','Injera','bread','Eritrea'),
('ER','Shiro','main','Eritrea'),
('ER','Tsebhi Dorho','main','Eritrea'),
('ER','Ful','breakfast','Eritrea'),
('ER','Kitcha Fit-Fit','breakfast','Eritrea'),
('ER','Hilbet','side','Eritrea'),
('ES','Paella','main','Spain · Spanish Mediterranean'),
('ES','Tortilla Española','main','Spain · Spanish Mediterranean'),
('ES','Gazpacho','soup','Spain · Spanish Mediterranean'),
('ES','Salmorejo','soup','Spain · Spanish Mediterranean'),
('ES','Patatas Bravas','snack','Spain · Spanish Mediterranean'),
('ES','Gambas al Ajillo','snack','Spain · Spanish Mediterranean'),
('ES','Croquetas','snack','Spain · Spanish Mediterranean'),
('ES','Pulpo a la Gallega','main','Spain · Spanish Mediterranean'),
('ES','Fabada Asturiana','soup','Spain · Spanish Mediterranean'),
('ES','Churros','dessert','Spain · Spanish Mediterranean'),
('ES','Crema Catalana','dessert','Spain · Spanish Mediterranean'),
('ES','Romesco','sauce','Spain · Spanish Mediterranean'),
('ES','Aioli','sauce','Spain · Spanish Mediterranean'),
('ET','Doro Wat','main','Ethiopia · Ethiopian'),
('ET','Injera','bread','Ethiopia · Ethiopian'),
('ET','Kitfo','main','Ethiopia · Ethiopian'),
('ET','Shiro','main','Ethiopia · Ethiopian'),
('ET','Tibs','main','Ethiopia · Ethiopian'),
('ET','Misir Wat','main','Ethiopia · Ethiopian'),
('ET','Gomen','side','Ethiopia · Ethiopian'),
('ET','Atkilt Wat','side','Ethiopia · Ethiopian'),
('ET','Firfir','breakfast','Ethiopia · Ethiopian'),
('ET','Genfo','breakfast','Ethiopia · Ethiopian'),
('ET','Berbere','sauce','Ethiopia · Ethiopian'),
('ET','Niter Kibbeh','sauce','Ethiopia · Ethiopian'),
('FI','Karjalanpiirakka','bread','Finland'),
('FI','Lohikeitto','soup','Finland'),
('FI','Poronkäristys','main','Finland'),
('FI','Lihapullat','main','Finland'),
('FI','Hernekeitto','soup','Finland'),
('FI','Kalakukko','bread','Finland'),
('FI','Leipäjuusto','dessert','Finland'),
('FI','Ruisleipä','bread','Finland'),
('FI','Korvapuusti','dessert','Finland'),
('FI','Mustikkapiirakka','dessert','Finland'),
('FI','Mämmi','dessert','Finland'),
('FJ','Kokoda','main','Fiji'),
('FJ','Lovo','main','Fiji'),
('FJ','Palusami','side','Fiji'),
('FJ','Rourou','side','Fiji'),
('FJ','Fiji Chicken Curry','main','Fiji'),
('FJ','Roti','bread','Fiji'),
('FJ','Cassava Cake','dessert','Fiji'),
('FJ','Kava','drink','Fiji'),
('FM','Breadfruit in Coconut Milk','side','Micronesia'),
('FM','Coconut Crab','main','Micronesia'),
('FM','Raw Fish Salad','main','Micronesia'),
('FM','Taro with Coconut Cream','side','Micronesia'),
('FM','Grilled Reef Fish','main','Micronesia'),
('FR','Coq au Vin','main','France · French'),
('FR','Boeuf Bourguignon','main','France · French'),
('FR','Ratatouille','main','France · French'),
('FR','French Onion Soup','soup','France · French'),
('FR','Cassoulet','main','France · French'),
('FR','Bouillabaisse','soup','France · French'),
('FR','Quiche Lorraine','main','France · French'),
('FR','Croque Monsieur','snack','France · French'),
('FR','Croissant','bread','France · French'),
('FR','Baguette','bread','France · French'),
('FR','Crêpes','dessert','France · French'),
('FR','Crème Brûlée','dessert','France · French'),
('FR','Béarnaise Sauce','sauce','France · French'),
('FR','Hollandaise Sauce','sauce','France · French'),
('GA','Poulet Nyembwe','main','Gabon'),
('GA','Bâton de Manioc','side','Gabon'),
('GA','Feuilles de Manioc','side','Gabon'),
('GA','Sauce Odika','sauce','Gabon'),
('GA','Fried Plantains','side','Gabon'),
('GA','Beignets','street food','Gabon'),
('GB','Fish and Chips','main','United Kingdom · British'),
('GB','Full English Breakfast','breakfast','United Kingdom · British'),
('GB','Sunday Roast','main','United Kingdom · British'),
('GB','Shepherd''s Pie','main','United Kingdom · British'),
('GB','Bangers and Mash','main','United Kingdom · British'),
('GB','Yorkshire Pudding','side','United Kingdom · British'),
('GB','Cornish Pasty','street food','United Kingdom · British'),
('GB','Scones','bread','United Kingdom · British'),
('GB','Sticky Toffee Pudding','dessert','United Kingdom · British'),
('GB','Beef Wellington','main','United Kingdom · British'),
('GB','Gravy','sauce','United Kingdom · British'),
('GB','Mint Sauce','sauce','United Kingdom · British'),
('GD','Oil Down','main','Grenada · Caribbean'),
('GD','Callaloo Soup','soup','Grenada · Caribbean'),
('GD','Lambie Curry','main','Grenada · Caribbean'),
('GD','Bakes and Saltfish','breakfast','Grenada · Caribbean'),
('GD','Fish Broth','soup','Grenada · Caribbean'),
('GD','Roti','main','Grenada · Caribbean'),
('GD','Nutmeg Ice Cream','dessert','Grenada · Caribbean'),
('GE','Khachapuri','bread','Georgia'),
('GE','Khinkali','main','Georgia'),
('GE','Lobio','main','Georgia'),
('GE','Pkhali','side','Georgia'),
('GE','Badrijani Nigvzit','side','Georgia'),
('GE','Chakapuli','main','Georgia'),
('GE','Satsivi','main','Georgia'),
('GE','Chkmeruli','main','Georgia'),
('GE','Mtsvadi','main','Georgia'),
('GE','Kharcho','soup','Georgia'),
('GE','Tkemali','sauce','Georgia'),
('GE','Churchkhela','dessert','Georgia'),
('GH','Jollof Rice','main','Ghana'),
('GH','Waakye','main','Ghana'),
('GH','Fufu with Light Soup','main','Ghana'),
('GH','Banku and Tilapia','main','Ghana'),
('GH','Kenkey','main','Ghana'),
('GH','Red Red','main','Ghana'),
('GH','Kelewele','street food','Ghana'),
('GH','Groundnut Soup','soup','Ghana'),
('GH','Palava Sauce','main','Ghana'),
('GH','Shito','sauce','Ghana'),
('GH','Bofrot','dessert','Ghana'),
('GM','Domoda','main','Gambia'),
('GM','Benachin','main','Gambia'),
('GM','Chicken Yassa','main','Gambia'),
('GM','Superkanja','main','Gambia'),
('GM','Plasas','main','Gambia'),
('GM','Akara','street food','Gambia'),
('GM','Wonjo','drink','Gambia'),
('GN','Sauce Arachide','main','Guinea'),
('GN','Poulet Yassa','main','Guinea'),
('GN','Riz Gras','main','Guinea'),
('GN','Sauce Feuille','main','Guinea'),
('GN','Fouti','main','Guinea'),
('GN','Fonio','side','Guinea'),
('GN','Bissap','drink','Guinea'),
('GQ','Pepper Soup','soup','Equatorial Guinea'),
('GQ','Succotash','main','Equatorial Guinea'),
('GQ','Fufu','side','Equatorial Guinea'),
('GQ','Chicken in Peanut Sauce','main','Equatorial Guinea'),
('GQ','Fried Plantains','side','Equatorial Guinea'),
('GR','Moussaka','main','Greece · Greek Mediterranean'),
('GR','Souvlaki','street food','Greece · Greek Mediterranean'),
('GR','Gyros','street food','Greece · Greek Mediterranean'),
('GR','Spanakopita','main','Greece · Greek Mediterranean'),
('GR','Greek Salad','salad','Greece · Greek Mediterranean'),
('GR','Pastitsio','main','Greece · Greek Mediterranean'),
('GR','Dolmades','side','Greece · Greek Mediterranean'),
('GR','Gemista','main','Greece · Greek Mediterranean'),
('GR','Avgolemono','soup','Greece · Greek Mediterranean'),
('GR','Fasolada','soup','Greece · Greek Mediterranean'),
('GR','Tzatziki','sauce','Greece · Greek Mediterranean'),
('GR','Baklava','dessert','Greece · Greek Mediterranean'),
('GR','Loukoumades','dessert','Greece · Greek Mediterranean'),
('GT','Pepián','main','Guatemala'),
('GT','Kak''ik','soup','Guatemala'),
('GT','Jocón','main','Guatemala'),
('GT','Hilachas','main','Guatemala'),
('GT','Chiles Rellenos','main','Guatemala'),
('GT','Tamales Colorados','main','Guatemala'),
('GT','Chuchitos','snack','Guatemala'),
('GT','Shucos','street food','Guatemala'),
('GT','Fiambre','salad','Guatemala'),
('GT','Rellenitos','dessert','Guatemala'),
('GW','Caldo de Chabéu','main','Guinea-Bissau'),
('GW','Frango à Cafriela','main','Guinea-Bissau'),
('GW','Caldo de Mancarra','main','Guinea-Bissau'),
('GW','Jollof Rice','main','Guinea-Bissau'),
('GW','Grilled Oysters','street food','Guinea-Bissau'),
('GY','Pepperpot','main','Guyana'),
('GY','Cook-Up Rice','main','Guyana'),
('GY','Metemgee','main','Guyana'),
('GY','Chicken Curry and Roti','main','Guyana'),
('GY','Dhal Puri','bread','Guyana'),
('GY','Garlic Pork','main','Guyana'),
('GY','Chow Mein','main','Guyana'),
('GY','Cheese Rolls','snack','Guyana'),
('GY','Pine Tarts','dessert','Guyana'),
('GY','Black Cake','dessert','Guyana'),
('HN','Baleadas','street food','Honduras'),
('HN','Plato Típico','main','Honduras'),
('HN','Sopa de Caracol','soup','Honduras'),
('HN','Tapado','soup','Honduras'),
('HN','Pollo Chuco','street food','Honduras'),
('HN','Yuca con Chicharrón','main','Honduras'),
('HN','Pastelitos de Carne','street food','Honduras'),
('HN','Catrachitas','snack','Honduras'),
('HN','Tres Leches','dessert','Honduras'),
('HR','Peka','main','Croatia · Mediterranean'),
('HR','Pašticada','main','Croatia · Mediterranean'),
('HR','Crni Rižot','main','Croatia · Mediterranean'),
('HR','Štrukli','main','Croatia · Mediterranean'),
('HR','Sarma','main','Croatia · Mediterranean'),
('HR','Brudet','main','Croatia · Mediterranean'),
('HR','Soparnik','main','Croatia · Mediterranean'),
('HR','Fritule','dessert','Croatia · Mediterranean'),
('HR','Rožata','dessert','Croatia · Mediterranean'),
('HR','Fuži with Truffles','main','Croatia · Mediterranean'),
('HR','Ajvar','sauce','Croatia · Mediterranean'),
('HT','Griot','main','Haiti · Caribbean'),
('HT','Soup Joumou','soup','Haiti · Caribbean'),
('HT','Diri ak Djon Djon','main','Haiti · Caribbean'),
('HT','Diri Kole ak Pwa','main','Haiti · Caribbean'),
('HT','Pikliz','sauce','Haiti · Caribbean'),
('HT','Bannann Peze','side','Haiti · Caribbean'),
('HT','Legim','main','Haiti · Caribbean'),
('HT','Akra','street food','Haiti · Caribbean'),
('HT','Tasso','main','Haiti · Caribbean'),
('HT','Pen Patat','dessert','Haiti · Caribbean'),
('HU','Goulash','soup','Hungary'),
('HU','Chicken Paprikash','main','Hungary'),
('HU','Pörkölt','main','Hungary'),
('HU','Halászlé','soup','Hungary'),
('HU','Töltött Káposzta','main','Hungary'),
('HU','Lecsó','main','Hungary'),
('HU','Lángos','street food','Hungary'),
('HU','Rakott Krumpli','main','Hungary'),
('HU','Túrós Csusza','main','Hungary'),
('HU','Dobos Torte','dessert','Hungary'),
('HU','Kürtőskalács','dessert','Hungary'),
('HU','Somlói Galuska','dessert','Hungary'),
('ID','Nasi Goreng','main','Indonesia'),
('ID','Beef Rendang','main','Indonesia'),
('ID','Satay','street food','Indonesia'),
('ID','Gado-Gado','salad','Indonesia'),
('ID','Soto Ayam','soup','Indonesia'),
('ID','Bakso','soup','Indonesia'),
('ID','Mie Goreng','main','Indonesia'),
('ID','Sambal','sauce','Indonesia'),
('ID','Martabak Manis','dessert','Indonesia'),
('ID','Tempeh Goreng','side','Indonesia'),
('ID','Es Cendol','drink','Indonesia'),
('IE','Irish Stew','main','Ireland'),
('IE','Soda Bread','bread','Ireland'),
('IE','Colcannon','side','Ireland'),
('IE','Boxty','side','Ireland'),
('IE','Dublin Coddle','main','Ireland'),
('IE','Full Irish Breakfast','breakfast','Ireland'),
('IE','Champ','side','Ireland'),
('IE','Seafood Chowder','soup','Ireland'),
('IE','Barmbrack','bread','Ireland'),
('IE','Irish Coffee','drink','Ireland'),
('IL','Shakshuka','breakfast','Israel · Middle Eastern Mediterranean'),
('IL','Falafel','street food','Israel · Middle Eastern Mediterranean'),
('IL','Hummus','side','Israel · Middle Eastern Mediterranean'),
('IL','Sabich','street food','Israel · Middle Eastern Mediterranean'),
('IL','Israeli Salad','salad','Israel · Middle Eastern Mediterranean'),
('IL','Jachnun','breakfast','Israel · Middle Eastern Mediterranean'),
('IL','Malawach','bread','Israel · Middle Eastern Mediterranean'),
('IL','Shawarma','street food','Israel · Middle Eastern Mediterranean'),
('IL','Bourekas','snack','Israel · Middle Eastern Mediterranean'),
('IL','Rugelach','dessert','Israel · Middle Eastern Mediterranean'),
('IN','Butter Chicken','main','India · Indian'),
('IN','Chicken Biryani','main','India · Indian'),
('IN','Chana Masala','main','India · Indian'),
('IN','Palak Paneer','main','India · Indian'),
('IN','Dal Tadka','main','India · Indian'),
('IN','Chicken Tikka Masala','main','India · Indian'),
('IN','Masala Dosa','breakfast','India · Indian'),
('IN','Samosa','street food','India · Indian'),
('IN','Naan','bread','India · Indian'),
('IN','Pani Puri','street food','India · Indian'),
('IN','Gulab Jamun','dessert','India · Indian'),
('IN','Mango Lassi','drink','India · Indian'),
('IQ','Masgouf','main','Iraq · Middle Eastern'),
('IQ','Dolma','main','Iraq · Middle Eastern'),
('IQ','Kubba','main','Iraq · Middle Eastern'),
('IQ','Quzi','main','Iraq · Middle Eastern'),
('IQ','Tashreeb','main','Iraq · Middle Eastern'),
('IQ','Tepsi Baytinjan','main','Iraq · Middle Eastern'),
('IQ','Bagila Bil Dihin','breakfast','Iraq · Middle Eastern'),
('IQ','Samoon','bread','Iraq · Middle Eastern'),
('IQ','Kleicha','dessert','Iraq · Middle Eastern'),
('IR','Ghormeh Sabzi','main','Iran · Middle Eastern'),
('IR','Fesenjan','main','Iran · Middle Eastern'),
('IR','Chelo Kabab','main','Iran · Middle Eastern'),
('IR','Joojeh Kabab','main','Iran · Middle Eastern'),
('IR','Tahdig','side','Iran · Middle Eastern'),
('IR','Ash Reshteh','soup','Iran · Middle Eastern'),
('IR','Kashke Bademjan','side','Iran · Middle Eastern'),
('IR','Zereshk Polo','main','Iran · Middle Eastern'),
('IR','Mirza Ghasemi','side','Iran · Middle Eastern'),
('IR','Sholeh Zard','dessert','Iran · Middle Eastern'),
('IR','Faloodeh','dessert','Iran · Middle Eastern'),
('IS','Plokkfiskur','main','Iceland'),
('IS','Kjötsúpa','soup','Iceland'),
('IS','Hangikjöt','main','Iceland'),
('IS','Skyr','dessert','Iceland'),
('IS','Rúgbrauð','bread','Iceland'),
('IS','Pylsur','street food','Iceland'),
('IS','Kleinur','dessert','Iceland'),
('IS','Flatkaka','bread','Iceland'),
('IS','Harðfiskur','snack','Iceland'),
('IS','Pönnukökur','dessert','Iceland'),
('IT','Spaghetti Carbonara','main','Italy · Italian Mediterranean'),
('IT','Margherita Pizza','main','Italy · Italian Mediterranean'),
('IT','Lasagna','main','Italy · Italian Mediterranean'),
('IT','Risotto alla Milanese','main','Italy · Italian Mediterranean'),
('IT','Fettuccine Alfredo','main','Italy · Italian Mediterranean'),
('IT','Osso Buco','main','Italy · Italian Mediterranean'),
('IT','Minestrone','soup','Italy · Italian Mediterranean'),
('IT','Bruschetta','snack','Italy · Italian Mediterranean'),
('IT','Tiramisu','dessert','Italy · Italian Mediterranean'),
('IT','Pesto','sauce','Italy · Italian Mediterranean'),
('IT','Marinara Sauce','sauce','Italy · Italian Mediterranean'),
('IT','Focaccia','bread','Italy · Italian Mediterranean'),
('JM','Jerk Chicken','main','Jamaica · Caribbean'),
('JM','Ackee and Saltfish','breakfast','Jamaica · Caribbean'),
('JM','Curry Goat','main','Jamaica · Caribbean'),
('JM','Oxtail Stew','main','Jamaica · Caribbean'),
('JM','Rice and Peas','side','Jamaica · Caribbean'),
('JM','Jamaican Beef Patty','street food','Jamaica · Caribbean'),
('JM','Escovitch Fish','main','Jamaica · Caribbean'),
('JM','Festival','side','Jamaica · Caribbean'),
('JM','Bammy','bread','Jamaica · Caribbean'),
('JM','Jerk Sauce','sauce','Jamaica · Caribbean'),
('JM','Gizzada','dessert','Jamaica · Caribbean'),
('JM','Sorrel','drink','Jamaica · Caribbean'),
('JO','Mansaf','main','Jordan · Middle Eastern'),
('JO','Maqluba','main','Jordan · Middle Eastern'),
('JO','Musakhan','main','Jordan · Middle Eastern'),
('JO','Zarb','main','Jordan · Middle Eastern'),
('JO','Falafel','street food','Jordan · Middle Eastern'),
('JO','Hummus','side','Jordan · Middle Eastern'),
('JO','Galayet Bandora','main','Jordan · Middle Eastern'),
('JO','Shorbat Adas','soup','Jordan · Middle Eastern'),
('JO','Knafeh','dessert','Jordan · Middle Eastern'),
('JP','Ramen','soup','Japan · Japanese'),
('JP','Sushi','main','Japan · Japanese'),
('JP','Tempura','main','Japan · Japanese'),
('JP','Miso Soup','soup','Japan · Japanese'),
('JP','Tonkatsu','main','Japan · Japanese'),
('JP','Japanese Curry','main','Japan · Japanese'),
('JP','Okonomiyaki','street food','Japan · Japanese'),
('JP','Takoyaki','street food','Japan · Japanese'),
('JP','Udon','soup','Japan · Japanese'),
('JP','Gyoza','snack','Japan · Japanese'),
('JP','Chicken Teriyaki','main','Japan · Japanese'),
('JP','Onigiri','snack','Japan · Japanese'),
('KE','Ugali','side','Kenya'),
('KE','Nyama Choma','main','Kenya'),
('KE','Sukuma Wiki','side','Kenya'),
('KE','Githeri','main','Kenya'),
('KE','Mukimo','side','Kenya'),
('KE','Pilau','main','Kenya'),
('KE','Chapati','bread','Kenya'),
('KE','Mandazi','snack','Kenya'),
('KE','Kachumbari','salad','Kenya'),
('KE','Irio','side','Kenya'),
('KG','Beshbarmak','main','Kyrgyzstan'),
('KG','Plov','main','Kyrgyzstan'),
('KG','Lagman','main','Kyrgyzstan'),
('KG','Manty','main','Kyrgyzstan'),
('KG','Kuurdak','main','Kyrgyzstan'),
('KG','Ashlyan-Fu','soup','Kyrgyzstan'),
('KG','Samsa','street food','Kyrgyzstan'),
('KG','Boorsok','bread','Kyrgyzstan'),
('KG','Chuchuk','main','Kyrgyzstan'),
('KH','Fish Amok','main','Cambodia'),
('KH','Lok Lak','main','Cambodia'),
('KH','Kuy Teav','soup','Cambodia'),
('KH','Num Banh Chok','breakfast','Cambodia'),
('KH','Bai Sach Chrouk','breakfast','Cambodia'),
('KH','Samlor Korko','soup','Cambodia'),
('KH','Samlor Machu','soup','Cambodia'),
('KH','Kampot Pepper Crab','main','Cambodia'),
('KH','Prahok Ktis','sauce','Cambodia'),
('KH','Nom Krok','snack','Cambodia'),
('KH','Num Ansom','dessert','Cambodia'),
('KI','Ika Mata','main','Kiribati'),
('KI','Palusami','side','Kiribati'),
('KI','Babai','side','Kiribati'),
('KI','Breadfruit Chips','snack','Kiribati'),
('KI','Coconut Crab','main','Kiribati'),
('KI','Te Bua Toro','dessert','Kiribati'),
('KM','Langouste à la Vanille','main','Comoros'),
('KM','Mataba','main','Comoros'),
('KM','Pilao','main','Comoros'),
('KM','Ntrovi','main','Comoros'),
('KM','Mkatra Foutra','bread','Comoros'),
('KM','Ladu','dessert','Comoros'),
('KN','Stewed Saltfish','main','Saint Kitts and Nevis · Caribbean'),
('KN','Spicy Plantains','side','Saint Kitts and Nevis · Caribbean'),
('KN','Coconut Dumplings','side','Saint Kitts and Nevis · Caribbean'),
('KN','Goat Water','soup','Saint Kitts and Nevis · Caribbean'),
('KN','Breadfruit','side','Saint Kitts and Nevis · Caribbean'),
('KN','Conkies','dessert','Saint Kitts and Nevis · Caribbean'),
('KN','Johnny Cakes','bread','Saint Kitts and Nevis · Caribbean'),
('KP','Pyongyang Naengmyeon','main','North Korea'),
('KP','Kimchi','side','North Korea'),
('KP','Injogogi Bap','street food','North Korea'),
('KP','Onban','main','North Korea'),
('KP','Bindae-tteok','street food','North Korea'),
('KP','Hamhung Naengmyeon','main','North Korea'),
('KP','Dubu Bap','street food','North Korea'),
('KP','Mandu','snack','North Korea'),
('KR','Kimchi','side','South Korea · Korean'),
('KR','Bibimbap','main','South Korea · Korean'),
('KR','Bulgogi','main','South Korea · Korean'),
('KR','Kimchi Jjigae','soup','South Korea · Korean'),
('KR','Tteokbokki','street food','South Korea · Korean'),
('KR','Japchae','side','South Korea · Korean'),
('KR','Samgyeopsal','main','South Korea · Korean'),
('KR','Korean Fried Chicken','main','South Korea · Korean'),
('KR','Sundubu Jjigae','soup','South Korea · Korean'),
('KR','Haemul Pajeon','snack','South Korea · Korean'),
('KR','Ssamjang','sauce','South Korea · Korean'),
('KR','Hotteok','dessert','South Korea · Korean'),
('KW','Machboos','main','Kuwait · Middle Eastern'),
('KW','Mutabbaq Samak','main','Kuwait · Middle Eastern'),
('KW','Harees','main','Kuwait · Middle Eastern'),
('KW','Jireesh','main','Kuwait · Middle Eastern'),
('KW','Balaleet','breakfast','Kuwait · Middle Eastern'),
('KW','Gers Ogaily','dessert','Kuwait · Middle Eastern'),
('KW','Luqaimat','dessert','Kuwait · Middle Eastern'),
('KZ','Beshbarmak','main','Kazakhstan'),
('KZ','Baursak','bread','Kazakhstan'),
('KZ','Kazy','main','Kazakhstan'),
('KZ','Kuyrdak','main','Kazakhstan'),
('KZ','Plov','main','Kazakhstan'),
('KZ','Manti','main','Kazakhstan'),
('KZ','Lagman','main','Kazakhstan'),
('KZ','Sorpa','soup','Kazakhstan'),
('KZ','Shelpek','bread','Kazakhstan'),
('LA','Larb','salad','Laos'),
('LA','Tam Mak Hoong','salad','Laos'),
('LA','Khao Niao','side','Laos'),
('LA','Or Lam','soup','Laos'),
('LA','Khao Piak Sen','soup','Laos'),
('LA','Mok Pa','main','Laos'),
('LA','Sai Oua','main','Laos'),
('LA','Jaew Bong','sauce','Laos'),
('LA','Khao Jee','street food','Laos'),
('LB','Tabbouleh','salad','Lebanon · Middle Eastern Mediterranean'),
('LB','Fattoush','salad','Lebanon · Middle Eastern Mediterranean'),
('LB','Kibbeh','main','Lebanon · Middle Eastern Mediterranean'),
('LB','Hummus','side','Lebanon · Middle Eastern Mediterranean'),
('LB','Baba Ganoush','side','Lebanon · Middle Eastern Mediterranean'),
('LB','Manakish','bread','Lebanon · Middle Eastern Mediterranean'),
('LB','Shish Tawook','main','Lebanon · Middle Eastern Mediterranean'),
('LB','Toum','sauce','Lebanon · Middle Eastern Mediterranean'),
('LB','Mujaddara','main','Lebanon · Middle Eastern Mediterranean'),
('LB','Baklava','dessert','Lebanon · Middle Eastern Mediterranean'),
('LC','Green Fig and Saltfish','main','Saint Lucia · Caribbean'),
('LC','Bouyon','soup','Saint Lucia · Caribbean'),
('LC','Accra','snack','Saint Lucia · Caribbean'),
('LC','Bakes','bread','Saint Lucia · Caribbean'),
('LC','Callaloo Soup','soup','Saint Lucia · Caribbean'),
('LC','Cocoa Tea','drink','Saint Lucia · Caribbean'),
('LC','Banana Bread','dessert','Saint Lucia · Caribbean'),
('LI','Käsknöpfle','main','Liechtenstein'),
('LI','Ribel','breakfast','Liechtenstein'),
('LI','Hafalaab','main','Liechtenstein'),
('LI','Rösti','side','Liechtenstein'),
('LI','Törkarebl','dessert','Liechtenstein'),
('LK','Rice and Curry','main','Sri Lanka'),
('LK','Kottu Roti','street food','Sri Lanka'),
('LK','Hoppers','breakfast','Sri Lanka'),
('LK','String Hoppers','breakfast','Sri Lanka'),
('LK','Parippu','side','Sri Lanka'),
('LK','Fish Ambul Thiyal','main','Sri Lanka'),
('LK','Lamprais','main','Sri Lanka'),
('LK','Pol Sambol','sauce','Sri Lanka'),
('LK','Coconut Roti','bread','Sri Lanka'),
('LK','Watalappan','dessert','Sri Lanka'),
('LK','Kiribath','breakfast','Sri Lanka'),
('LR','Palm Butter Soup','soup','Liberia'),
('LR','Jollof Rice','main','Liberia'),
('LR','Potato Greens','main','Liberia'),
('LR','Cassava Leaf Stew','main','Liberia'),
('LR','Fufu','side','Liberia'),
('LR','Pepper Soup','soup','Liberia'),
('LR','Rice Bread','bread','Liberia'),
('LR','Kala','snack','Liberia'),
('LS','Papa','side','Lesotho'),
('LS','Moroho','side','Lesotho'),
('LS','Likhobe','main','Lesotho'),
('LS','Motoho','breakfast','Lesotho'),
('LS','Chakalaka','sauce','Lesotho'),
('LT','Cepelinai','main','Lithuania'),
('LT','Šaltibarščiai','soup','Lithuania'),
('LT','Kugelis','main','Lithuania'),
('LT','Kibinai','snack','Lithuania'),
('LT','Vėdarai','main','Lithuania'),
('LT','Koldūnai','main','Lithuania'),
('LT','Kepta Duona','snack','Lithuania'),
('LT','Šakotis','dessert','Lithuania'),
('LT','Skruzdėlynas','dessert','Lithuania'),
('LU','Judd mat Gaardebounen','main','Luxembourg'),
('LU','Bouneschlupp','soup','Luxembourg'),
('LU','Gromperekichelcher','street food','Luxembourg'),
('LU','Rieslingspaschtéit','main','Luxembourg'),
('LU','Kniddelen','main','Luxembourg'),
('LU','Quetschentaart','dessert','Luxembourg'),
('LU','Feierstengszalot','salad','Luxembourg'),
('LV','Grey Peas with Bacon','main','Latvia'),
('LV','Pīrāgi','snack','Latvia'),
('LV','Rupjmaize','bread','Latvia'),
('LV','Aukstā Zupa','soup','Latvia'),
('LV','Sklandrausis','dessert','Latvia'),
('LV','Jāņu Siers','snack','Latvia'),
('LV','Maizes Zupa','dessert','Latvia'),
('LY','Bazeen','main','Libya'),
('LY','Sharba Libiya','soup','Libya'),
('LY','Couscous','main','Libya'),
('LY','Usban','main','Libya'),
('LY','Mbakbaka','main','Libya'),
('LY','Asida','dessert','Libya'),
('LY','Makroudh','dessert','Libya'),
('MA','Chicken Tagine with Preserved Lemon','main','Morocco · Mediterranean'),
('MA','Couscous','main','Morocco · Mediterranean'),
('MA','Harira','soup','Morocco · Mediterranean'),
('MA','Pastilla','main','Morocco · Mediterranean'),
('MA','Kefta Tagine','main','Morocco · Mediterranean'),
('MA','Lamb Tagine with Prunes','main','Morocco · Mediterranean'),
('MA','Zaalouk','salad','Morocco · Mediterranean'),
('MA','Chermoula','sauce','Morocco · Mediterranean'),
('MA','Msemen','bread','Morocco · Mediterranean'),
('MA','Khobz','bread','Morocco · Mediterranean'),
('MA','Chebakia','dessert','Morocco · Mediterranean'),
('MA','Moroccan Mint Tea','drink','Morocco · Mediterranean'),
('MC','Barbagiuan','snack','Monaco'),
('MC','Socca','street food','Monaco'),
('MC','Stocafi','main','Monaco'),
('MC','Pissaladière','bread','Monaco'),
('MC','Fougasse Monégasque','dessert','Monaco'),
('MC','Pan Bagnat','main','Monaco'),
('MD','Mămăligă','side','Moldova'),
('MD','Sarmale','main','Moldova'),
('MD','Plăcinte','bread','Moldova'),
('MD','Zeamă','soup','Moldova'),
('MD','Mititei','main','Moldova'),
('MD','Răcituri','main','Moldova'),
('MD','Colțunași','main','Moldova'),
('MD','Ardei Umpluți','main','Moldova'),
('MD','Pască','dessert','Moldova'),
('ME','Kačamak','side','Montenegro'),
('ME','Crni Rižoto','main','Montenegro'),
('ME','Ćevapi','main','Montenegro'),
('ME','Japrak','main','Montenegro'),
('ME','Buzara','main','Montenegro'),
('ME','Priganice','breakfast','Montenegro'),
('ME','Burek','bread','Montenegro'),
('MG','Romazava','main','Madagascar'),
('MG','Ravitoto','main','Madagascar'),
('MG','Henakisoa sy Ravitoto','main','Madagascar'),
('MG','Akoho sy Voanio','main','Madagascar'),
('MG','Lasary','sauce','Madagascar'),
('MG','Sakay','sauce','Madagascar'),
('MG','Mofo Gasy','breakfast','Madagascar'),
('MG','Koba','dessert','Madagascar'),
('MG','Mofo Anana','street food','Madagascar'),
('MG','Lasopy','soup','Madagascar'),
('MH','Bwiro','side','Marshall Islands'),
('MH','Chukuchuk','side','Marshall Islands'),
('MH','Jajimi','main','Marshall Islands'),
('MH','Breadfruit Chips','snack','Marshall Islands'),
('MH','Mokwan','dessert','Marshall Islands'),
('MK','Tavče Gravče','main','North Macedonia'),
('MK','Ajvar','sauce','North Macedonia'),
('MK','Šopska Salata','salad','North Macedonia'),
('MK','Burek','street food','North Macedonia'),
('MK','Pastrmajlija','bread','North Macedonia'),
('MK','Polneti Piperki','main','North Macedonia'),
('MK','Selsko Meso','main','North Macedonia'),
('MK','Turli Tava','main','North Macedonia'),
('MK','Kebapi','main','North Macedonia'),
('MK','Baklava','dessert','North Macedonia'),
('ML','Tigadegena','main','Mali'),
('ML','Riz Gras','main','Mali'),
('ML','Tô','side','Mali'),
('ML','Fakoye','main','Mali'),
('ML','Poulet Yassa','main','Mali'),
('ML','Capitaine Sauce','main','Mali'),
('ML','Maafe','main','Mali'),
('ML','Fufu','side','Mali'),
('ML','Dégué','dessert','Mali'),
('ML','Bissap','drink','Mali'),
('MM','Mohinga','soup','Myanmar'),
('MM','Lahpet Thoke','salad','Myanmar'),
('MM','Shan Noodles','main','Myanmar'),
('MM','Ohn No Khao Swè','soup','Myanmar'),
('MM','Burmese Chicken Curry','main','Myanmar'),
('MM','Nan Gyi Thoke','main','Myanmar'),
('MM','Samosa Thoke','salad','Myanmar'),
('MM','Mont Lin Ma Yar','street food','Myanmar'),
('MM','Shwe Yin Aye','dessert','Myanmar'),
('MN','Buuz','main','Mongolia'),
('MN','Khuushuur','street food','Mongolia'),
('MN','Khorkhog','main','Mongolia'),
('MN','Tsuivan','main','Mongolia'),
('MN','Boodog','main','Mongolia'),
('MN','Guriltai Shul','soup','Mongolia'),
('MN','Bansh','main','Mongolia'),
('MN','Boortsog','snack','Mongolia'),
('MN','Suutei Tsai','drink','Mongolia'),
('MR','Thieboudienne','main','Mauritania'),
('MR','Méchoui','main','Mauritania'),
('MR','Couscous','main','Mauritania'),
('MR','Maru We Lham','main','Mauritania'),
('MR','Lakh','breakfast','Mauritania'),
('MR','Maghrebi Mint Tea','drink','Mauritania'),
('MT','Stuffat tal-Fenek','main','Malta · Mediterranean'),
('MT','Pastizzi','street food','Malta · Mediterranean'),
('MT','Ftira','bread','Malta · Mediterranean'),
('MT','Ħobż biż-Żejt','snack','Malta · Mediterranean'),
('MT','Lampuki Pie','main','Malta · Mediterranean'),
('MT','Timpana','main','Malta · Mediterranean'),
('MT','Aljotta','soup','Malta · Mediterranean'),
('MT','Bigilla','sauce','Malta · Mediterranean'),
('MT','Imqaret','dessert','Malta · Mediterranean'),
('MT','Kannoli','dessert','Malta · Mediterranean'),
('MU','Dholl Puri','street food','Mauritius'),
('MU','Rougaille','main','Mauritius'),
('MU','Mine Frit','street food','Mauritius'),
('MU','Gateaux Piments','snack','Mauritius'),
('MU','Vindaye Poisson','main','Mauritius'),
('MU','Bol Renversé','main','Mauritius'),
('MU','Farata','bread','Mauritius'),
('MU','Mauritian Chicken Curry','main','Mauritius'),
('MU','Alouda','drink','Mauritius'),
('MU','Gato Patat','dessert','Mauritius'),
('MV','Mas Huni','breakfast','Maldives'),
('MV','Garudhiya','soup','Maldives'),
('MV','Mas Riha','main','Maldives'),
('MV','Roshi','bread','Maldives'),
('MV','Gulha','snack','Maldives'),
('MV','Bis Keemiya','snack','Maldives'),
('MV','Fihunu Mas','main','Maldives'),
('MV','Bondibai','dessert','Maldives'),
('MW','Nsima','side','Malawi'),
('MW','Chambo','main','Malawi'),
('MW','Ndiwo','side','Malawi'),
('MW','Usipa','main','Malawi'),
('MW','Mandasi','snack','Malawi'),
('MW','Futali','side','Malawi'),
('MW','Chikondamoyo','dessert','Malawi'),
('MX','Tacos al Pastor','street food','Mexico · Mexican'),
('MX','Mole Poblano','sauce','Mexico · Mexican'),
('MX','Guacamole','sauce','Mexico · Mexican'),
('MX','Salsa Verde','sauce','Mexico · Mexican'),
('MX','Pozole','soup','Mexico · Mexican'),
('MX','Chiles Rellenos','main','Mexico · Mexican'),
('MX','Enchiladas','main','Mexico · Mexican'),
('MX','Tamales','main','Mexico · Mexican'),
('MX','Cochinita Pibil','main','Mexico · Mexican'),
('MX','Chilaquiles','breakfast','Mexico · Mexican'),
('MX','Elote','street food','Mexico · Mexican'),
('MX','Churros','dessert','Mexico · Mexican'),
('MY','Nasi Lemak','main','Malaysia'),
('MY','Beef Rendang','main','Malaysia'),
('MY','Char Kway Teow','street food','Malaysia'),
('MY','Laksa','soup','Malaysia'),
('MY','Satay','street food','Malaysia'),
('MY','Roti Canai','bread','Malaysia'),
('MY','Hainanese Chicken Rice','main','Malaysia'),
('MY','Mee Goreng Mamak','street food','Malaysia'),
('MY','Nasi Kerabu','main','Malaysia'),
('MY','Sambal','sauce','Malaysia'),
('MY','Cendol','dessert','Malaysia'),
('MY','Teh Tarik','drink','Malaysia'),
('MZ','Frango à Piri-Piri','main','Mozambique'),
('MZ','Piri-Piri Sauce','sauce','Mozambique'),
('MZ','Matapa','main','Mozambique'),
('MZ','Camarão Grelhado','main','Mozambique'),
('MZ','Xima','side','Mozambique'),
('MZ','Caril de Caranguejo','main','Mozambique'),
('MZ','Mucapata','side','Mozambique'),
('MZ','Pão','bread','Mozambique'),
('MZ','Bolo Polana','dessert','Mozambique'),
('NA','Kapana','street food','Namibia'),
('NA','Potjiekos','main','Namibia'),
('NA','Oshifima','side','Namibia'),
('NA','Braai','main','Namibia'),
('NA','Boerewors','main','Namibia'),
('NA','Biltong','snack','Namibia'),
('NA','Vetkoek','bread','Namibia'),
('NA','Mopane Worms','snack','Namibia'),
('NE','Djerma Stew','main','Niger'),
('NE','Dambou','main','Niger'),
('NE','Kilishi','snack','Niger'),
('NE','Fura','drink','Niger'),
('NE','Brochettes','street food','Niger'),
('NE','Masa','street food','Niger'),
('NE','Riz Sauce','main','Niger'),
('NG','Jollof Rice','main','Nigeria'),
('NG','Egusi Soup','soup','Nigeria'),
('NG','Pounded Yam','side','Nigeria'),
('NG','Suya','street food','Nigeria'),
('NG','Pepper Soup','soup','Nigeria'),
('NG','Moi Moi','side','Nigeria'),
('NG','Akara','breakfast','Nigeria'),
('NG','Puff-Puff','dessert','Nigeria'),
('NG','Fried Plantain (Dodo)','side','Nigeria'),
('NG','Efo Riro','soup','Nigeria'),
('NG','Ofada Stew','sauce','Nigeria'),
('NG','Chin Chin','snack','Nigeria'),
('NI','Gallo Pinto','breakfast','Nicaragua'),
('NI','Nacatamal','main','Nicaragua'),
('NI','Vigorón','street food','Nicaragua'),
('NI','Indio Viejo','main','Nicaragua'),
('NI','Sopa de Mondongo','soup','Nicaragua'),
('NI','Quesillo','street food','Nicaragua'),
('NI','Baho','main','Nicaragua'),
('NI','Tostones','side','Nicaragua'),
('NI','Tres Leches','dessert','Nicaragua'),
('NI','Pinolillo','drink','Nicaragua'),
('NL','Stamppot','main','Netherlands'),
('NL','Erwtensoep','soup','Netherlands'),
('NL','Bitterballen','snack','Netherlands'),
('NL','Kroket','street food','Netherlands'),
('NL','Hutspot','main','Netherlands'),
('NL','Haring','street food','Netherlands'),
('NL','Poffertjes','dessert','Netherlands'),
('NL','Pannenkoeken','breakfast','Netherlands'),
('NL','Stroopwafel','dessert','Netherlands'),
('NL','Appeltaart','dessert','Netherlands'),
('NL','Kibbeling','street food','Netherlands'),
('NL','Oliebollen','dessert','Netherlands'),
('NO','Fårikål','main','Norway'),
('NO','Kjøttkaker','main','Norway'),
('NO','Raspeballer','main','Norway'),
('NO','Lutefisk','main','Norway'),
('NO','Gravlaks','side','Norway'),
('NO','Fiskesuppe','soup','Norway'),
('NO','Lefse','bread','Norway'),
('NO','Pinnekjøtt','main','Norway'),
('NO','Brunost','snack','Norway'),
('NO','Krumkake','dessert','Norway'),
('NO','Skillingsboller','dessert','Norway'),
('NO','Vafler','dessert','Norway'),
('NP','Dal Bhat','main','Nepal'),
('NP','Momo','street food','Nepal'),
('NP','Momo Achar','sauce','Nepal'),
('NP','Thukpa','soup','Nepal'),
('NP','Sel Roti','bread','Nepal'),
('NP','Gundruk','side','Nepal'),
('NP','Chatamari','street food','Nepal'),
('NP','Bara','street food','Nepal'),
('NP','Aloo Tama','soup','Nepal'),
('NP','Yomari','dessert','Nepal'),
('NR','Coconut Fish','main','Nauru'),
('NR','Coconut Crusted Fish','main','Nauru'),
('NR','Coconut Mousse','dessert','Nauru'),
('NR','Banana Coconut Cake','dessert','Nauru'),
('NZ','Hāngī','main','New Zealand'),
('NZ','Roast Lamb','main','New Zealand'),
('NZ','Pavlova','dessert','New Zealand'),
('NZ','Mince and Cheese Pie','street food','New Zealand'),
('NZ','Whitebait Fritters','main','New Zealand'),
('NZ','Boil-Up','soup','New Zealand'),
('NZ','Fish and Chips','main','New Zealand'),
('NZ','Rēwena Bread','bread','New Zealand'),
('NZ','Hokey Pokey Ice Cream','dessert','New Zealand'),
('NZ','Anzac Biscuits','dessert','New Zealand'),
('NZ','Lamington','dessert','New Zealand'),
('NZ','Kūmara Chips','side','New Zealand'),
('OM','Shuwa','main','Oman · Middle Eastern'),
('OM','Majboos','main','Oman · Middle Eastern'),
('OM','Mashuai','main','Oman · Middle Eastern'),
('OM','Harees','main','Oman · Middle Eastern'),
('OM','Omani Halwa','dessert','Oman · Middle Eastern'),
('OM','Mishkak','street food','Oman · Middle Eastern'),
('OM','Kahwa','drink','Oman · Middle Eastern'),
('OM','Khubz Ragag','bread','Oman · Middle Eastern'),
('PA','Sancocho','soup','Panama'),
('PA','Arroz con Pollo','main','Panama'),
('PA','Patacones','side','Panama'),
('PA','Ropa Vieja','main','Panama'),
('PA','Carimañolas','street food','Panama'),
('PA','Hojaldras','breakfast','Panama'),
('PA','Ceviche','salad','Panama'),
('PA','Arroz con Guandú','side','Panama'),
('PA','Tamal de Olla','main','Panama'),
('PA','Raspao','dessert','Panama'),
('PE','Ceviche','salad','Peru'),
('PE','Lomo Saltado','main','Peru'),
('PE','Ají de Gallina','main','Peru'),
('PE','Papa a la Huancaína','side','Peru'),
('PE','Huancaína Sauce','sauce','Peru'),
('PE','Anticuchos','street food','Peru'),
('PE','Pollo a la Brasa','main','Peru'),
('PE','Causa Limeña','side','Peru'),
('PE','Arroz con Pollo','main','Peru'),
('PE','Rocoto Relleno','main','Peru'),
('PE','Picarones','dessert','Peru'),
('PE','Chicha Morada','drink','Peru'),
('PG','Mumu','main','Papua New Guinea'),
('PG','Kokoda','salad','Papua New Guinea'),
('PG','Saksak','side','Papua New Guinea'),
('PG','Kaukau','side','Papua New Guinea'),
('PG','Chicken Pot','main','Papua New Guinea'),
('PG','Sago Pancakes','bread','Papua New Guinea'),
('PH','Chicken Adobo','main','Philippines'),
('PH','Sinigang','soup','Philippines'),
('PH','Lechon','main','Philippines'),
('PH','Pancit Canton','main','Philippines'),
('PH','Lumpia','street food','Philippines'),
('PH','Kare-Kare','main','Philippines'),
('PH','Sisig','main','Philippines'),
('PH','Tinola','soup','Philippines'),
('PH','Tapsilog','breakfast','Philippines'),
('PH','Halo-Halo','dessert','Philippines'),
('PH','Leche Flan','dessert','Philippines'),
('PH','Bibingka','dessert','Philippines'),
('PK','Chicken Biryani','main','Pakistan'),
('PK','Nihari','main','Pakistan'),
('PK','Chicken Karahi','main','Pakistan'),
('PK','Haleem','main','Pakistan'),
('PK','Seekh Kebab','street food','Pakistan'),
('PK','Chapli Kebab','street food','Pakistan'),
('PK','Saag','side','Pakistan'),
('PK','Naan','bread','Pakistan'),
('PK','Paratha','bread','Pakistan'),
('PK','Samosa','street food','Pakistan'),
('PK','Gulab Jamun','dessert','Pakistan'),
('PK','Lassi','drink','Pakistan'),
('PL','Pierogi','main','Poland'),
('PL','Bigos','main','Poland'),
('PL','Żurek','soup','Poland'),
('PL','Barszcz','soup','Poland'),
('PL','Gołąbki','main','Poland'),
('PL','Kotlet Schabowy','main','Poland'),
('PL','Placki Ziemniaczane','side','Poland'),
('PL','Rosół','soup','Poland'),
('PL','Kiełbasa','main','Poland'),
('PL','Zapiekanka','street food','Poland'),
('PL','Pączki','dessert','Poland'),
('PL','Sernik','dessert','Poland'),
('PT','Bacalhau à Brás','main','Portugal'),
('PT','Caldo Verde','soup','Portugal'),
('PT','Francesinha','main','Portugal'),
('PT','Pastel de Nata','dessert','Portugal'),
('PT','Piri-Piri Chicken','main','Portugal'),
('PT','Piri-Piri Sauce','sauce','Portugal'),
('PT','Bifana','street food','Portugal'),
('PT','Sardinhas Assadas','main','Portugal'),
('PT','Cozido à Portuguesa','main','Portugal'),
('PT','Arroz de Marisco','main','Portugal'),
('PT','Carne de Porco à Alentejana','main','Portugal'),
('PT','Arroz Doce','dessert','Portugal'),
('PW','Fruit Bat Soup','soup','Palau'),
('PW','Ulkoy','snack','Palau'),
('PW','Taro in Coconut Milk','side','Palau'),
('PW','Coconut Crab','main','Palau'),
('PW','Grilled Reef Fish','main','Palau'),
('PY','Sopa Paraguaya','bread','Paraguay'),
('PY','Chipa','bread','Paraguay'),
('PY','Chipa Guasu','side','Paraguay'),
('PY','Vori Vori','soup','Paraguay'),
('PY','Mbejú','bread','Paraguay'),
('PY','Bori Bori','soup','Paraguay'),
('PY','Pira Caldo','soup','Paraguay'),
('PY','Asado','main','Paraguay'),
('PY','Empanadas','street food','Paraguay'),
('PY','Tereré','drink','Paraguay'),
('QA','Machboos','main','Qatar · Middle Eastern'),
('QA','Harees','main','Qatar · Middle Eastern'),
('QA','Thareed','main','Qatar · Middle Eastern'),
('QA','Balaleet','breakfast','Qatar · Middle Eastern'),
('QA','Luqaimat','dessert','Qatar · Middle Eastern'),
('QA','Madrouba','main','Qatar · Middle Eastern'),
('QA','Karak Chai','drink','Qatar · Middle Eastern'),
('RO','Sarmale','main','Romania'),
('RO','Mămăligă','side','Romania'),
('RO','Mici','street food','Romania'),
('RO','Ciorbă de Burtă','soup','Romania'),
('RO','Ciorbă de Perișoare','soup','Romania'),
('RO','Tochitură','main','Romania'),
('RO','Zacuscă','sauce','Romania'),
('RO','Salată de Vinete','salad','Romania'),
('RO','Papanași','dessert','Romania'),
('RO','Cozonac','dessert','Romania'),
('RO','Drob de Miel','main','Romania'),
('RS','Ćevapi','main','Serbia'),
('RS','Pljeskavica','main','Serbia'),
('RS','Sarma','main','Serbia'),
('RS','Karađorđeva Šnicla','main','Serbia'),
('RS','Pasulj','soup','Serbia'),
('RS','Prebranac','side','Serbia'),
('RS','Gibanica','bread','Serbia'),
('RS','Burek','breakfast','Serbia'),
('RS','Proja','bread','Serbia'),
('RS','Ajvar','sauce','Serbia'),
('RS','Urnebes','sauce','Serbia'),
('RU','Borscht','soup','Russia'),
('RU','Pelmeni','main','Russia'),
('RU','Beef Stroganoff','main','Russia'),
('RU','Blini','breakfast','Russia'),
('RU','Shchi','soup','Russia'),
('RU','Olivier Salad','salad','Russia'),
('RU','Pirozhki','street food','Russia'),
('RU','Syrniki','breakfast','Russia'),
('RU','Solyanka','soup','Russia'),
('RU','Golubtsy','main','Russia'),
('RU','Herring Under a Fur Coat','salad','Russia'),
('RU','Medovik','dessert','Russia'),
('RW','Isombe','main','Rwanda'),
('RW','Brochettes','street food','Rwanda'),
('RW','Ugali','side','Rwanda'),
('RW','Matoke','main','Rwanda'),
('RW','Ibihaza','side','Rwanda'),
('RW','Agatogo','main','Rwanda'),
('RW','Sambaza','snack','Rwanda'),
('RW','Akabanga Chili Oil','sauce','Rwanda'),
('SA','Kabsa','main','Saudi Arabia · Middle Eastern'),
('SA','Mandi','main','Saudi Arabia · Middle Eastern'),
('SA','Jareesh','main','Saudi Arabia · Middle Eastern'),
('SA','Mutabbaq','street food','Saudi Arabia · Middle Eastern'),
('SA','Saleeg','main','Saudi Arabia · Middle Eastern'),
('SA','Shawarma','street food','Saudi Arabia · Middle Eastern'),
('SA','Harees','main','Saudi Arabia · Middle Eastern'),
('SA','Kleicha','dessert','Saudi Arabia · Middle Eastern'),
('SA','Luqaimat','dessert','Saudi Arabia · Middle Eastern'),
('SA','Arabic Coffee (Gahwa)','drink','Saudi Arabia · Middle Eastern'),
('SB','Solomon Poi','side','Solomon Islands'),
('SB','Motu','main','Solomon Islands'),
('SB','Fish in Coconut Cream','main','Solomon Islands'),
('SB','Slippery Cabbage','side','Solomon Islands'),
('SB','Cassava Pudding','dessert','Solomon Islands'),
('SB','Roasted Breadfruit','side','Solomon Islands'),
('SC','Octopus Curry','main','Seychelles'),
('SC','Fish Curry','main','Seychelles'),
('SC','Shark Chutney','side','Seychelles'),
('SC','Bouillon Brède','soup','Seychelles'),
('SC','Grilled Red Snapper','main','Seychelles'),
('SC','Ladob','dessert','Seychelles'),
('SC','Kat-Kat Banane','main','Seychelles'),
('SC','Palm Heart Salad','salad','Seychelles'),
('SD','Ful Medames','breakfast','Sudan'),
('SD','Kisra','bread','Sudan'),
('SD','Asida','side','Sudan'),
('SD','Mullah Weika','main','Sudan'),
('SD','Gurasa','bread','Sudan'),
('SD','Elmaraara','main','Sudan'),
('SD','Shaiyah','main','Sudan'),
('SD','Salata Aswad','salad','Sudan'),
('SD','Basbousa','dessert','Sudan'),
('SD','Karkade','drink','Sudan'),
('SE','Swedish Meatballs','main','Sweden'),
('SE','Gravlax','side','Sweden'),
('SE','Janssons Frestelse','side','Sweden'),
('SE','Raggmunk','main','Sweden'),
('SE','Pyttipanna','main','Sweden'),
('SE','Ärtsoppa','soup','Sweden'),
('SE','Toast Skagen','snack','Sweden'),
('SE','Kanelbulle','dessert','Sweden'),
('SE','Prinsesstårta','dessert','Sweden'),
('SE','Semla','dessert','Sweden'),
('SE','Knäckebröd','bread','Sweden'),
('SG','Hainanese Chicken Rice','main','Singapore'),
('SG','Chili Crab','main','Singapore'),
('SG','Laksa','soup','Singapore'),
('SG','Char Kway Teow','street food','Singapore'),
('SG','Hokkien Mee','street food','Singapore'),
('SG','Bak Kut Teh','soup','Singapore'),
('SG','Fish Head Curry','main','Singapore'),
('SG','Satay','street food','Singapore'),
('SG','Nasi Lemak','main','Singapore'),
('SG','Fried Carrot Cake','street food','Singapore'),
('SG','Roti Prata','breakfast','Singapore'),
('SG','Kaya Toast','breakfast','Singapore'),
('SI','Kranjska Klobasa','main','Slovenia'),
('SI','Idrijski Žlikrofi','main','Slovenia'),
('SI','Jota','soup','Slovenia'),
('SI','Ričet','soup','Slovenia'),
('SI','Bograč','soup','Slovenia'),
('SI','Štruklji','side','Slovenia'),
('SI','Potica','dessert','Slovenia'),
('SI','Prekmurska Gibanica','dessert','Slovenia'),
('SI','Kremšnita','dessert','Slovenia'),
('SK','Bryndzové Halušky','main','Slovakia'),
('SK','Kapustnica','soup','Slovakia'),
('SK','Strapačky','main','Slovakia'),
('SK','Pirohy','main','Slovakia'),
('SK','Vyprážaný Syr','main','Slovakia'),
('SK','Zemiakové Placky','side','Slovakia'),
('SK','Segedínsky Guláš','main','Slovakia'),
('SK','Lokše','bread','Slovakia'),
('SK','Šúľance','dessert','Slovakia'),
('SL','Cassava Leaf Stew','main','Sierra Leone'),
('SL','Potato Leaf Stew','main','Sierra Leone'),
('SL','Groundnut Soup','soup','Sierra Leone'),
('SL','Jollof Rice','main','Sierra Leone'),
('SL','Okra Soup','soup','Sierra Leone'),
('SL','Pepper Soup','soup','Sierra Leone'),
('SL','Akara','street food','Sierra Leone'),
('SL','Fried Plantains','side','Sierra Leone'),
('SL','Kanya','snack','Sierra Leone'),
('SL','Ginger Beer','drink','Sierra Leone'),
('SM','Torta Tre Monti','dessert','San Marino'),
('SM','Piadina','bread','San Marino'),
('SM','Nidi di Rondine','main','San Marino'),
('SM','Bustrengo','dessert','San Marino'),
('SM','Fagioli con le Cotiche','soup','San Marino'),
('SM','Cacciatello','dessert','San Marino'),
('SN','Thieboudienne','main','Senegal'),
('SN','Yassa Poulet','main','Senegal'),
('SN','Mafé','main','Senegal'),
('SN','Soupou Kandja','soup','Senegal'),
('SN','Thiéré','main','Senegal'),
('SN','Caldou','soup','Senegal'),
('SN','Dibi','street food','Senegal'),
('SN','Pastels','street food','Senegal'),
('SN','Fataya','street food','Senegal'),
('SN','Ndambé','breakfast','Senegal'),
('SN','Thiakry','dessert','Senegal'),
('SN','Bissap','drink','Senegal'),
('SO','Bariis Iskukaris','main','Somalia'),
('SO','Suqaar','main','Somalia'),
('SO','Canjeero','bread','Somalia'),
('SO','Sabaayad','bread','Somalia'),
('SO','Sambusa','street food','Somalia'),
('SO','Maraq','soup','Somalia'),
('SO','Baasto','main','Somalia'),
('SO','Muufo','bread','Somalia'),
('SO','Xalwo','dessert','Somalia'),
('SO','Shaah','drink','Somalia'),
('SR','Pom','main','Suriname'),
('SR','Roti','main','Suriname'),
('SR','Moksi Alesi','main','Suriname'),
('SR','Bami','main','Suriname'),
('SR','Nasi Goreng','main','Suriname'),
('SR','Saoto Soup','soup','Suriname'),
('SR','Pastei','main','Suriname'),
('SR','Bara','street food','Suriname'),
('SR','Fiadoe','dessert','Suriname'),
('SS','Kisra','bread','South Sudan'),
('SS','Asida','side','South Sudan'),
('SS','Mulah','main','South Sudan'),
('SS','Kajaik','main','South Sudan'),
('SS','Ful Medames','breakfast','South Sudan'),
('SS','Wala Wala','breakfast','South Sudan'),
('ST','Calulu','main','São Tomé and Príncipe'),
('ST','Molho no Fogo','main','São Tomé and Príncipe'),
('ST','Feijoada','main','São Tomé and Príncipe'),
('ST','Grilled Fish with Breadfruit','main','São Tomé and Príncipe'),
('SV','Pupusas','main','El Salvador'),
('SV','Curtido','side','El Salvador'),
('SV','Salsa Roja','sauce','El Salvador'),
('SV','Yuca Frita con Chicharrón','street food','El Salvador'),
('SV','Sopa de Pata','soup','El Salvador'),
('SV','Panes con Pollo','main','El Salvador'),
('SV','Tamales de Elote','snack','El Salvador'),
('SV','Pastelitos','street food','El Salvador'),
('SV','Quesadilla Salvadoreña','dessert','El Salvador'),
('SV','Atol de Elote','drink','El Salvador'),
('SY','Kibbeh','main','Syria · Middle Eastern'),
('SY','Shawarma','street food','Syria · Middle Eastern'),
('SY','Fattoush','salad','Syria · Middle Eastern'),
('SY','Tabbouleh','salad','Syria · Middle Eastern'),
('SY','Hummus','sauce','Syria · Middle Eastern'),
('SY','Muhammara','sauce','Syria · Middle Eastern'),
('SY','Baba Ganoush','sauce','Syria · Middle Eastern'),
('SY','Fatteh','breakfast','Syria · Middle Eastern'),
('SY','Shish Barak','main','Syria · Middle Eastern'),
('SY','Kibbeh Labanieh','main','Syria · Middle Eastern'),
('SY','Halawet el Jibn','dessert','Syria · Middle Eastern'),
('SY','Baklava','dessert','Syria · Middle Eastern'),
('SZ','Sishwala','side','Eswatini'),
('SZ','Emasi','side','Eswatini'),
('SZ','Sidvudvu','breakfast','Eswatini'),
('SZ','Umncweba','snack','Eswatini'),
('SZ','Siphuphe Setindlubu','side','Eswatini'),
('SZ','Umbidvo Wetintsanga','side','Eswatini'),
('TD','Boule','side','Chad'),
('TD','Daraba','main','Chad'),
('TD','Kissar','bread','Chad'),
('TD','Jarret de Boeuf','main','Chad'),
('TD','Esh','breakfast','Chad'),
('TD','Karkanji','drink','Chad'),
('TG','Fufu','side','Togo'),
('TG','Akoumé','side','Togo'),
('TG','Gboma Dessi','main','Togo'),
('TG','Ademe','main','Togo'),
('TG','Peanut Soup','soup','Togo'),
('TG','Koklo Meme','main','Togo'),
('TG','Ablo','bread','Togo'),
('TG','Kom','side','Togo'),
('TG','Akpan','dessert','Togo'),
('TG','Fried Yam','street food','Togo'),
('TH','Pad Thai','main','Thailand · Thai'),
('TH','Tom Yum Goong','soup','Thailand · Thai'),
('TH','Tom Kha Gai','soup','Thailand · Thai'),
('TH','Green Curry','main','Thailand · Thai'),
('TH','Massaman Curry','main','Thailand · Thai'),
('TH','Som Tam','salad','Thailand · Thai'),
('TH','Pad Kra Pao','main','Thailand · Thai'),
('TH','Khao Soi','soup','Thailand · Thai'),
('TH','Larb','salad','Thailand · Thai'),
('TH','Mango Sticky Rice','dessert','Thailand · Thai'),
('TH','Nam Prik','sauce','Thailand · Thai'),
('TH','Peanut Sauce','sauce','Thailand · Thai'),
('TH','Thai Iced Tea','drink','Thailand · Thai'),
('TJ','Qurutob','main','Tajikistan'),
('TJ','Plov','main','Tajikistan'),
('TJ','Sambusa','street food','Tajikistan'),
('TJ','Shorba','soup','Tajikistan'),
('TJ','Mantu','main','Tajikistan'),
('TJ','Laghman','soup','Tajikistan'),
('TJ','Non','bread','Tajikistan'),
('TJ','Shakarob','salad','Tajikistan'),
('TL','Ikan Sabuco','main','Timor-Leste'),
('TL','Batar Da''an','main','Timor-Leste'),
('TL','Tukir','main','Timor-Leste'),
('TL','Feijoada','main','Timor-Leste'),
('TL','Katupa','side','Timor-Leste'),
('TL','Budu','sauce','Timor-Leste'),
('TL','Ai Manas','sauce','Timor-Leste'),
('TM','Plov','main','Turkmenistan'),
('TM','Dograma','main','Turkmenistan'),
('TM','Ishlekli','main','Turkmenistan'),
('TM','Manti','main','Turkmenistan'),
('TM','Chorek','bread','Turkmenistan'),
('TM','Gutap','main','Turkmenistan'),
('TM','Shurpa','soup','Turkmenistan'),
('TM','Somsa','street food','Turkmenistan'),
('TN','Couscous','main','Tunisia · Mediterranean'),
('TN','Brik','street food','Tunisia · Mediterranean'),
('TN','Shakshuka','breakfast','Tunisia · Mediterranean'),
('TN','Lablabi','soup','Tunisia · Mediterranean'),
('TN','Harissa','sauce','Tunisia · Mediterranean'),
('TN','Salade Mechouia','salad','Tunisia · Mediterranean'),
('TN','Ojja','main','Tunisia · Mediterranean'),
('TN','Makroudh','dessert','Tunisia · Mediterranean'),
('TN','Fricassé','street food','Tunisia · Mediterranean'),
('TN','Kafteji','main','Tunisia · Mediterranean'),
('TO','Lu Pulu','main','Tonga'),
('TO','Lu Sipi','main','Tonga'),
('TO','Ota Ika','salad','Tonga'),
('TO','Kapisi Pulu','main','Tonga'),
('TO','Faikakai Topai','dessert','Tonga'),
('TO','''Otai','drink','Tonga'),
('TR','Doner Kebab','street food','Türkiye · Mediterranean Middle Eastern'),
('TR','Adana Kebab','main','Türkiye · Mediterranean Middle Eastern'),
('TR','Iskender Kebab','main','Türkiye · Mediterranean Middle Eastern'),
('TR','Lahmacun','street food','Türkiye · Mediterranean Middle Eastern'),
('TR','Pide','bread','Türkiye · Mediterranean Middle Eastern'),
('TR','Manti','main','Türkiye · Mediterranean Middle Eastern'),
('TR','Menemen','breakfast','Türkiye · Mediterranean Middle Eastern'),
('TR','Lentil Soup','soup','Türkiye · Mediterranean Middle Eastern'),
('TR','Imam Bayildi','main','Türkiye · Mediterranean Middle Eastern'),
('TR','Kofte','main','Türkiye · Mediterranean Middle Eastern'),
('TR','Baklava','dessert','Türkiye · Mediterranean Middle Eastern'),
('TR','Simit','bread','Türkiye · Mediterranean Middle Eastern'),
('TT','Doubles','street food','Trinidad and Tobago · Caribbean'),
('TT','Bake and Shark','street food','Trinidad and Tobago · Caribbean'),
('TT','Pelau','main','Trinidad and Tobago · Caribbean'),
('TT','Callaloo','soup','Trinidad and Tobago · Caribbean'),
('TT','Roti','bread','Trinidad and Tobago · Caribbean'),
('TT','Curry Goat','main','Trinidad and Tobago · Caribbean'),
('TT','Aloo Pie','street food','Trinidad and Tobago · Caribbean'),
('TT','Buss Up Shut','bread','Trinidad and Tobago · Caribbean'),
('TT','Coconut Bake','bread','Trinidad and Tobago · Caribbean'),
('TT','Sorrel','drink','Trinidad and Tobago · Caribbean'),
('TV','Pulaka','side','Tuvalu'),
('TV','Fekei','dessert','Tuvalu'),
('TV','Palusami','main','Tuvalu'),
('TV','Raw Fish in Coconut Milk','salad','Tuvalu'),
('TV','Coconut Crab','main','Tuvalu'),
('TZ','Ugali','side','Tanzania'),
('TZ','Nyama Choma','main','Tanzania'),
('TZ','Chipsi Mayai','street food','Tanzania'),
('TZ','Pilau','main','Tanzania'),
('TZ','Mishkaki','street food','Tanzania'),
('TZ','Ndizi Nyama','main','Tanzania'),
('TZ','Zanzibar Pizza','street food','Tanzania'),
('TZ','Mchuzi wa Samaki','main','Tanzania'),
('TZ','Urojo','soup','Tanzania'),
('TZ','Chapati','bread','Tanzania'),
('TZ','Mandazi','breakfast','Tanzania'),
('TZ','Wali wa Nazi','side','Tanzania'),
('UA','Borscht','soup','Ukraine'),
('UA','Varenyky','main','Ukraine'),
('UA','Holubtsi','main','Ukraine'),
('UA','Chicken Kyiv','main','Ukraine'),
('UA','Deruny','main','Ukraine'),
('UA','Pampushky','bread','Ukraine'),
('UA','Syrniki','breakfast','Ukraine'),
('UA','Salo','snack','Ukraine'),
('UA','Kyiv Cake','dessert','Ukraine'),
('UG','Rolex','street food','Uganda'),
('UG','Matoke','main','Uganda'),
('UG','Luwombo','main','Uganda'),
('UG','Groundnut Sauce','sauce','Uganda'),
('UG','Chapati','bread','Uganda'),
('UG','Katogo','breakfast','Uganda'),
('UG','Mandazi','snack','Uganda'),
('US','Hamburger','main','United States · American Southern'),
('US','Mac and Cheese','main','United States · American Southern'),
('US','Fried Chicken','main','United States · American Southern'),
('US','BBQ Ribs','main','United States · American Southern'),
('US','Buffalo Wings','snack','United States · American Southern'),
('US','Clam Chowder','soup','United States · American Southern'),
('US','Chili','main','United States · American Southern'),
('US','Pancakes','breakfast','United States · American Southern'),
('US','Apple Pie','dessert','United States · American Southern'),
('US','Hot Dog','street food','United States · American Southern'),
('US','BBQ Sauce','sauce','United States · American Southern'),
('US','Ranch Dressing','sauce','United States · American Southern'),
('US','Buffalo Sauce','sauce','United States · American Southern'),
('UY','Chivito','street food','Uruguay'),
('UY','Asado','main','Uruguay'),
('UY','Chimichurri','sauce','Uruguay'),
('UY','Milanesa','main','Uruguay'),
('UY','Empanadas','street food','Uruguay'),
('UY','Chaja','dessert','Uruguay'),
('UY','Dulce de Leche','sauce','Uruguay'),
('UY','Torta Frita','bread','Uruguay'),
('UY','Mate','drink','Uruguay'),
('UZ','Plov','main','Uzbekistan'),
('UZ','Samsa','street food','Uzbekistan'),
('UZ','Lagman','main','Uzbekistan'),
('UZ','Manti','main','Uzbekistan'),
('UZ','Shashlik','main','Uzbekistan'),
('UZ','Non','bread','Uzbekistan'),
('UZ','Shurpa','soup','Uzbekistan'),
('UZ','Achichuk','salad','Uzbekistan'),
('UZ','Chuchvara','soup','Uzbekistan'),
('VC','Roasted Breadfruit and Fried Jackfish','main','Saint Vincent and the Grenadines · Carib'),
('VC','Callaloo Soup','soup','Saint Vincent and the Grenadines · Carib'),
('VC','Buljol','breakfast','Saint Vincent and the Grenadines · Carib'),
('VC','Ducana','side','Saint Vincent and the Grenadines · Carib'),
('VC','Saltfish Cakes','snack','Saint Vincent and the Grenadines · Carib'),
('VC','Pelau','main','Saint Vincent and the Grenadines · Carib'),
('VE','Arepas','bread','Venezuela'),
('VE','Pabellon Criollo','main','Venezuela'),
('VE','Cachapas','breakfast','Venezuela'),
('VE','Hallacas','main','Venezuela'),
('VE','Tequenos','snack','Venezuela'),
('VE','Empanadas','street food','Venezuela'),
('VE','Asado Negro','main','Venezuela'),
('VE','Quesillo','dessert','Venezuela'),
('VE','Guasacaca','sauce','Venezuela'),
('VN','Pho','soup','Vietnam · Vietnamese'),
('VN','Banh Mi','street food','Vietnam · Vietnamese'),
('VN','Bun Cha','main','Vietnam · Vietnamese'),
('VN','Goi Cuon','snack','Vietnam · Vietnamese'),
('VN','Cha Gio','snack','Vietnam · Vietnamese'),
('VN','Bun Bo Hue','soup','Vietnam · Vietnamese'),
('VN','Com Tam','main','Vietnam · Vietnamese'),
('VN','Banh Xeo','street food','Vietnam · Vietnamese'),
('VN','Ca Kho To','main','Vietnam · Vietnamese'),
('VN','Bun Bo Nam Bo','salad','Vietnam · Vietnamese'),
('VN','Nuoc Cham','sauce','Vietnam · Vietnamese'),
('VN','Vietnamese Iced Coffee','drink','Vietnam · Vietnamese'),
('VU','Laplap','main','Vanuatu'),
('VU','Simboro','main','Vanuatu'),
('VU','Tuluk','main','Vanuatu'),
('VU','Nalot','side','Vanuatu'),
('VU','Kava','drink','Vanuatu'),
('WS','Palusami','side','Samoa'),
('WS','Oka','salad','Samoa'),
('WS','Sapasui','main','Samoa'),
('WS','Panipopo','dessert','Samoa'),
('WS','Koko Alaisa','dessert','Samoa'),
('WS','Pani Keke','snack','Samoa'),
('WS','Fa''alifu Fa''i','side','Samoa'),
('WS','Umu','main','Samoa'),
('YE','Saltah','main','Yemen · Middle Eastern'),
('YE','Mandi','main','Yemen · Middle Eastern'),
('YE','Fahsa','main','Yemen · Middle Eastern'),
('YE','Bint al-Sahn','dessert','Yemen · Middle Eastern'),
('YE','Zhug','sauce','Yemen · Middle Eastern'),
('YE','Lahoh','bread','Yemen · Middle Eastern'),
('YE','Aseeda','main','Yemen · Middle Eastern'),
('YE','Shafut','side','Yemen · Middle Eastern'),
('ZA','Bobotie','main','South Africa'),
('ZA','Bunny Chow','street food','South Africa'),
('ZA','Boerewors','main','South Africa'),
('ZA','Potjiekos','main','South Africa'),
('ZA','Chakalaka','sauce','South Africa'),
('ZA','Pap','side','South Africa'),
('ZA','Biltong','snack','South Africa'),
('ZA','Vetkoek','bread','South Africa'),
('ZA','Bredie','main','South Africa'),
('ZA','Malva Pudding','dessert','South Africa'),
('ZA','Koeksisters','dessert','South Africa'),
('ZA','Melktert','dessert','South Africa'),
('ZM','Nshima','side','Zambia'),
('ZM','Ifisashi','side','Zambia'),
('ZM','Kapenta','main','Zambia'),
('ZM','Chikanda','snack','Zambia'),
('ZM','Ifinkubala','snack','Zambia'),
('ZM','Village Chicken Stew','main','Zambia'),
('ZW','Sadza','side','Zimbabwe'),
('ZW','Nyama','main','Zimbabwe'),
('ZW','Muriwo Unedovi','side','Zimbabwe'),
('ZW','Dovi','main','Zimbabwe'),
('ZW','Matemba','main','Zimbabwe'),
('ZW','Mopane Worms','snack','Zimbabwe')
on conflict (country, lower(name)) do update set type = excluded.type, cuisine = excluded.cuisine;

-- ---------- passport stamps: one per country, paid once ----------
create table if not exists public.passport_stamps (
  user_id uuid not null references auth.users (id) on delete cascade,
  country text not null check (country ~ '^[A-Z]{2}$'),
  meal_id uuid references public.meals (id) on delete set null,
  coins integer not null default 5000,
  stamped_at timestamptz not null default now(),
  primary key (user_id, country)
);
alter table public.passport_stamps enable row level security;
revoke all on public.passport_stamps from public, anon, authenticated;
grant select on public.passport_stamps to authenticated;
drop policy if exists passport_stamps_read_own on public.passport_stamps;
create policy passport_stamps_read_own on public.passport_stamps for select to authenticated using (user_id = (select auth.uid()));

-- Meals keep the country they were logged with when they aren't from a recipe (only server functions insert meals).
create or replace function public._meal_country() returns trigger
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if new.web_recipe_id is not null then
    new.country := (select nullif(w.data ->> 'country', '') from web_recipes w where w.id = new.web_recipe_id);
  elsif tg_op = 'UPDATE' then
    new.country := old.country;
  end if;
  return new;
end $$;
revoke execute on function public._meal_country() from public, anon, authenticated;

-- The 10th meal from a country stamps it and pays 5,000 coins, once per country (193 stamps = 965,000 coins).
create or replace function public._award_stamp() returns trigger
language plpgsql security definer set search_path = public, pg_temp as $$
declare n int;
begin
  if new.country is null then return null; end if;
  select count(*) into n from meals m where m.user_id = new.user_id and m.country = new.country;
  if n >= 10 then
    insert into passport_stamps (user_id, country, meal_id) values (new.user_id, new.country, new.id) on conflict do nothing;
    if found then update profiles set coins = coins + 5000 where id = new.user_id; end if;
  end if;
  return null;
end $$;
revoke execute on function public._award_stamp() from public, anon, authenticated;
drop trigger if exists meals_stamp on public.meals;
create trigger meals_stamp after insert on public.meals for each row execute function public._award_stamp();

-- Stamps already earned before this migration get paid too.
with earned as (
  select m.user_id, m.country from public.meals m where m.country is not null group by 1, 2 having count(*) >= 10
), ins as (
  insert into public.passport_stamps (user_id, country) select user_id, country from earned on conflict do nothing returning user_id
)
update public.profiles p set coins = p.coins + 5000 * x.n from (select user_id, count(*) n from ins group by 1) x where p.id = x.user_id;

-- ---------- log_meal: a recipe, or any dish from the list ----------
drop function if exists public.log_meal(text, text, uuid, text);
create or replace function public.log_meal(p_recipe_id text, p_photo_path text, p_challenge_id uuid default null, p_notes text default null, p_dish text default null, p_country text default null)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare
  uid uuid := auth.uid();
  r web_recipes%rowtype;
  dsh dishes%rowtype;
  v_stamp text;
  v_meal uuid;
  xp_gain int := 0; coin_gain int := 0; completed boolean := false;
  ch weekly_challenges%rowtype;
  today date := _user_today(uid);
  wk date := date_trunc('week', _user_today(uid))::date;
  p profiles%rowtype;
  new_streak int; used_freeze boolean := false;
  n jsonb;
begin
  if uid is null then raise exception 'not signed in'; end if;
  if p_recipe_id is not null then
    select * into r from web_recipes w where w.id = p_recipe_id and w.active;
    if not found then raise exception 'unknown recipe'; end if;
  else
    -- a dish from Whisk's list of 193 countries (the server can't be told a made-up dish or country)
    select * into dsh from dishes d where d.country = p_country and lower(d.name) = lower(trim(p_dish));
    if not found then raise exception 'unknown dish'; end if;
  end if;
  if p_photo_path is null or split_part(p_photo_path, '/', 1) <> uid::text
     or not exists (select 1 from storage.objects o where o.bucket_id = 'meal-photos' and o.name = p_photo_path) then
    raise exception 'photo not found';
  end if;
  n := r.data -> 'nutrition';

  insert into meals (user_id, web_recipe_id, country, title, cuisine, notes, photo_path, calories, protein_g, carbs_g, fat_g)
  values (uid, r.id, dsh.country, left(coalesce(r.title, dsh.name), 120), left(coalesce(r.cuisine, dsh.cuisine), 40), left(p_notes, 500), p_photo_path,
          case when jsonb_typeof(n) = 'object' then least(5000, (n ->> 'calories')::int) end, case when jsonb_typeof(n) = 'object' then least(500, (n ->> 'protein_g')::int) end,
          case when jsonb_typeof(n) = 'object' then least(800, (n ->> 'carbs_g')::int) end, case when jsonb_typeof(n) = 'object' then least(400, (n ->> 'fat_g')::int) end)
  returning id into v_meal;
  if r.id is not null then insert into saved_recipes (user_id, recipe_id) values (uid, r.id) on conflict do nothing; end if;

  xp_gain := xp_gain + _award_xp(uid, 'cook', 50, 3);
  if not exists (select 1 from meals m where m.user_id = uid and lower(m.cuisine) = lower(coalesce(r.cuisine, dsh.cuisine)) and m.id <> v_meal) then
    xp_gain := xp_gain + _award_xp(uid, 'cuisine_stamp', 40, null);
  end if;

  select * into p from profiles where id = uid for update;
  if p.streak_freeze_week is null or p.streak_freeze_week < wk then
    update profiles set streak_freezes = 1, streak_freeze_week = wk where id = uid;
    p.streak_freezes := 1;
  end if;
  used_freeze := coalesce(p.streak_last_date = today - 2, false) and p.streak_freezes > 0;
  new_streak := case
    when p.streak_last_date = today then p.streak_days
    when p.streak_last_date = today - 1 then p.streak_days + 1
    when used_freeze then p.streak_days + 1
    else 1 end;
  update profiles set last_meal_at = now(), streak_days = new_streak, streak_last_date = today,
    streak_freezes = streak_freezes - (case when used_freeze then 1 else 0 end)
  where id = uid;
  if p.streak_last_date is distinct from today then xp_gain := xp_gain + _award_xp(uid, 'streak', 10, 1); end if;

  if p_challenge_id is not null then
    select * into ch from weekly_challenges w where w.id = p_challenge_id and w.user_id = uid for update;
    if found and ch.completed_at is null and ch.week_start = wk and r.id is not null and ch.recipe_id = r.id then
      update weekly_challenges set completed_at = now() where id = ch.id;
      update meals set challenge_id = ch.id where id = v_meal;
      update profiles set coins = coins + ch.coins where id = uid;
      coin_gain := ch.coins; completed := true;
      xp_gain := xp_gain + _award_xp(uid, 'challenge', 100, 3);
    end if;
  end if;

  -- 10th meal from a country: the stamp trigger already paid 5,000 coins; tell the app so it can celebrate
  select s.country into v_stamp from passport_stamps s where s.user_id = uid and s.meal_id = v_meal;
  if v_stamp is not null then coin_gain := coin_gain + 5000; end if;

  return jsonb_build_object('stamp', v_stamp, 'meal_id', v_meal, 'xp', xp_gain, 'coins', coin_gain, 'challenge_completed', completed, 'streak', new_streak, 'used_freeze', used_freeze);
end $$;
revoke execute on function public.log_meal(text, text, uuid, text, text, text) from public, anon;
grant execute on function public.log_meal(text, text, uuid, text, text, text) to authenticated;
